#!/usr/bin/env python3
import argparse
import hashlib
import json
import math
import random
from pathlib import Path

CLASSES = ['silence', 'speech-like', 'tone']
INPUTS = 3
HIDDEN = 8
SEED = 20260822


def softmax(values):
    m = max(values)
    exps = [math.exp(v - m) for v in values]
    total = sum(exps)
    return [v / total for v in exps]


def tanh(v):
    return math.tanh(v)


def make_dataset(seed=SEED):
    rng = random.Random(seed)
    rows = []
    for _ in range(120):
        energy = max(0.0, min(1.0, rng.gauss(0.03, 0.02)))
        zcr = max(0.0, min(1.0, rng.gauss(0.03, 0.02)))
        centroid = max(0.0, min(1.0, rng.gauss(0.04, 0.02)))
        rows.append(([energy, zcr, centroid], 0))
    for _ in range(120):
        energy = max(0.0, min(1.0, rng.gauss(0.62, 0.10)))
        zcr = max(0.0, min(1.0, rng.gauss(0.46, 0.12)))
        centroid = max(0.0, min(1.0, rng.gauss(0.54, 0.12)))
        rows.append(([energy, zcr, centroid], 1))
    for _ in range(120):
        energy = max(0.0, min(1.0, rng.gauss(0.68, 0.08)))
        zcr = max(0.0, min(1.0, rng.gauss(0.08, 0.03)))
        centroid = max(0.0, min(1.0, rng.gauss(0.80, 0.07)))
        rows.append(([energy, zcr, centroid], 2))
    rng.shuffle(rows)
    return rows


def init_matrix(rows, cols, rng, scale=0.25):
    return [[rng.uniform(-scale, scale) for _ in range(cols)] for _ in range(rows)]


def forward(x, w1, b1, w2, b2):
    hidden = []
    for j in range(HIDDEN):
        s = b1[j]
        for i in range(INPUTS):
            s += x[i] * w1[i][j]
        hidden.append(tanh(s))
    logits = []
    for k in range(len(CLASSES)):
        s = b2[k]
        for j in range(HIDDEN):
            s += hidden[j] * w2[j][k]
        logits.append(s)
    return hidden, softmax(logits)


def train(epochs=220, lr=0.08):
    rng = random.Random(SEED)
    rows = make_dataset()
    split = int(len(rows) * 0.8)
    train_rows = rows[:split]
    test_rows = rows[split:]
    w1 = init_matrix(INPUTS, HIDDEN, rng)
    b1 = [0.0] * HIDDEN
    w2 = init_matrix(HIDDEN, len(CLASSES), rng)
    b2 = [0.0] * len(CLASSES)
    history = []
    for epoch in range(1, epochs + 1):
        rng.shuffle(train_rows)
        loss_total = 0.0
        correct = 0
        for x, y in train_rows:
            hidden, probs = forward(x, w1, b1, w2, b2)
            loss_total += -math.log(max(1e-12, probs[y]))
            pred = max(range(len(probs)), key=lambda idx: probs[idx])
            correct += int(pred == y)
            dlogits = probs[:]
            dlogits[y] -= 1.0
            dhidden = [0.0] * HIDDEN
            for j in range(HIDDEN):
                for k in range(len(CLASSES)):
                    dhidden[j] += dlogits[k] * w2[j][k]
            for j in range(HIDDEN):
                for k in range(len(CLASSES)):
                    w2[j][k] -= lr * hidden[j] * dlogits[k]
            for k in range(len(CLASSES)):
                b2[k] -= lr * dlogits[k]
            for j in range(HIDDEN):
                dz = dhidden[j] * (1.0 - hidden[j] * hidden[j])
                for i in range(INPUTS):
                    w1[i][j] -= lr * x[i] * dz
                b1[j] -= lr * dz
        if epoch in (1, 10, 25, 50, 100, epochs):
            history.append({'epoch': epoch, 'loss': loss_total / len(train_rows), 'accuracy': correct / len(train_rows)})
    test_correct = 0
    confusion = [[0 for _ in CLASSES] for _ in CLASSES]
    for x, y in test_rows:
        _, probs = forward(x, w1, b1, w2, b2)
        pred = max(range(len(probs)), key=lambda idx: probs[idx])
        test_correct += int(pred == y)
        confusion[y][pred] += 1
    accuracy = test_correct / len(test_rows)
    model = {
        'service': 'ATLAS Model Factory',
        'model': 'ATLAS Audio Canary v1',
        'kind': 'neural-canary',
        'purpose': 'end-to-end model manufacturing and artifact integrity validation',
        'productionCapability': False,
        'trainingData': 'deterministic synthetic audio-feature vectors generated by ATLAS',
        'externalProviders': [],
        'inputFeatures': ['energy', 'zeroCrossingRate', 'spectralCentroid'],
        'classes': CLASSES,
        'architecture': {'input': INPUTS, 'hidden': HIDDEN, 'activation': 'tanh', 'output': len(CLASSES), 'loss': 'cross-entropy'},
        'seed': SEED,
        'weights': {'w1': w1, 'b1': b1, 'w2': w2, 'b2': b2},
        'metrics': {'holdoutAccuracy': accuracy, 'confusionMatrix': confusion},
        'history': history,
        'state': 'candidate-canary'
    }
    return model


def main():
    parser = argparse.ArgumentParser(description='Train the ATLAS Audio Canary v1 neural model')
    parser.add_argument('--out', default='build/models/atlas-audio-canary-v1.json')
    args = parser.parse_args()
    model = train()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(model, indent=2, sort_keys=True) + '\n'
    out.write_text(payload)
    sha = hashlib.sha256(payload.encode()).hexdigest()
    result = {
        'service': 'ATLAS Model Factory',
        'ok': True,
        'model': model['model'],
        'artifact': str(out),
        'sha256': sha,
        'metrics': model['metrics'],
        'state': model['state'],
        'externalProviders': [],
        'productionCapability': False
    }
    result_path = out.with_name('atlas-audio-canary-v1-result.json')
    result_path.write_text(json.dumps(result, indent=2, sort_keys=True) + '\n')
    print(json.dumps(result, indent=2))
    if model['metrics']['holdoutAccuracy'] < 0.90:
        raise SystemExit('ATLAS canary model accuracy gate failed')


if __name__ == '__main__':
    main()
