export function crmClientScript(){return `const app=document.getElementById('app');let token='',scope=null,scopes=[],currency='USD';
const views=[['dashboard','Dashboard'],['accounts','Accounts'],['contacts','Contacts'],['leads','Leads'],['opportunities','Opportunities'],['quotes','Quotes'],['activities','Activities']];
const readToken=()=>{try{const canonical=sessionStorage.getItem('atlas.session')||'';if(canonical)return canonical;const legacy=sessionStorage.getItem('atlas_session')||'';if(legacy){sessionStorage.setItem('atlas.session',legacy);sessionStorage.removeItem('atlas_session')}return legacy}catch{return''}};
const saveToken=value=>{token=value;try{sessionStorage.setItem('atlas.session',value);sessionStorage.removeItem('atlas_session')}catch{}};
const clearToken=()=>{token='';try{sessionStorage.removeItem('atlas.session');sessionStorage.removeItem('atlas_session')}catch{}};
const scopeKey=s=>s.organization.id+':'+s.dba.id,readSavedScope=()=>{try{return sessionStorage.getItem('atlas.workspace.scope')||sessionStorage.getItem('atlas.dashboard.scope')||''}catch{return''}},saveScope=s=>{try{const key=scopeKey(s);sessionStorage.setItem('atlas.workspace.scope',key);sessionStorage.setItem('atlas.dashboard.scope',key)}catch{}};
token=readToken();
const money=n=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:0}).format((Number(n)||0)/100)}catch{return ((Number(n)||0)/100).toLocaleString()+' '+currency}};
const el=(tag,cls,value)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(value!==undefined)node.textContent=String(value);return node};
const canWrite=()=>Boolean(scope&&(scope.permissions||[]).includes('crm.write'));
async function api(path,opt={}){const headers={...(opt.headers||{})};if(token)headers.authorization='Bearer '+token;if(scope){headers['x-atlas-organization']=scope.organization.id;headers['x-atlas-dba']=scope.dba.id}const response=await fetch(path,{...opt,headers,cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||('HTTP '+response.status));return body}
async function loadPreferences(){currency='USD';try{const d=await api('/api/settings'),preferred=String(d?.preferences?.['company.defaultCurrency']?.value||'USD').toUpperCase();if(/^[A-Z]{3}$/.test(preferred))currency=preferred}catch{}}
function showLogin(message=''){app.replaceChildren();const box=el('section','login');box.append(el('div','brand','ATLAS CRM'),el('p','muted','Secure enterprise customer relationship management.'));const form=el('form');const email=el('input'),password=el('input'),error=el('div','error'),button=el('button','', 'Sign in');email.type='email';email.placeholder='Email';email.required=true;password.type='password';password.placeholder='Password';password.required=true;error.textContent=message;form.append(email,password,error,button);form.addEventListener('submit',async event=>{event.preventDefault();error.textContent='';try{const result=await api('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});saveToken(result.sessionToken);await start()}catch(err){error.textContent=err.message}});box.append(form);app.append(box)}
async function signOut(){try{if(token)await api('/api/auth/logout',{method:'POST'})}catch{}clearToken();scope=null;scopes=[];location.assign('/login')}
const currentView=()=>{const v=(location.hash||'#dashboard').slice(1);return views.some(x=>x[0]===v)?v:'dashboard'};
function table(headers,rows){const wrap=el('div','table-wrap'),t=el('table','table'),thead=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th','',h)));thead.append(tr);const tbody=el('tbody');if(!rows.length){const empty=el('tr'),cell=el('td','empty','No records in this workspace yet.');cell.colSpan=headers.length;empty.append(cell);tbody.append(empty)}else rows.forEach(row=>{const r=el('tr');row.forEach(value=>r.append(el('td','',value==null?'':value)));tbody.append(r)});t.append(thead,tbody);wrap.append(t);return wrap}
function input(name,placeholder,type='text',required=false){const x=el('input');x.name=name;x.placeholder=placeholder;x.type=type;x.required=required;return x}
function select(name,options){const x=el('select');x.name=name;options.forEach(([value,label])=>{const o=el('option','',label);o.value=value;x.append(o)});return x}
function formPanel(title,fields,onSubmit){const p=el('section','panel');p.append(el('h2','',title));if(!canWrite()){p.append(el('div','notice','This role has CRM read access only.'));return p}const f=el('form','form-grid'),error=el('div','error wide');fields.forEach(x=>f.append(x));const b=el('button','wide','Save');b.type='submit';f.append(error,b);f.onsubmit=async event=>{event.preventDefault();error.textContent='';b.disabled=true;try{await onSubmit(f);f.reset();await renderCurrent()}catch(err){error.textContent=err.message}finally{b.disabled=false}};p.append(f);return p}
function heading(title,description){const h=el('section','hero'),left=el('div');left.append(el('div','eyebrow','ATLAS SALES & CRM'),el('h1','',title),el('p','',description));h.append(left);return h}
function shellLayout(){app.replaceChildren();const root=el('div','crm-app'),side=el('aside','crm-side'),brand=el('a','brand');brand.href='/dashboard';const mark=el('span','brand-mark','A'),copy=el('span');copy.append(el('b','','ATLAS'),el('small','','SALES & CRM'));brand.append(mark,copy);const nav=el('nav','crm-nav');views.forEach(([id,label])=>{const a=el('a','',label);a.href='#'+id;a.dataset.view=id;nav.append(a)});side.append(brand,nav,el('div','side-foot','Tenant-scoped CRM · audited mutations · ATLAS identity'));
const main=el('section','crm-main'),top=el('header','top'),title=el('div','top-title');title.append(el('b','','ATLAS CRM'),el('span','','Customers · pipeline · revenue'));const actions=el('div','row'),dot=el('span','dot'),scopeSelect=el('select'),refresh=el('button','secondary','Refresh'),logout=el('button','secondary','Sign out');scopeSelect.setAttribute('aria-label','ATLAS organization and DBA');scopes.forEach((s,i)=>{const o=el('option','',s.organization.name+' · '+s.dba.name);o.value=String(i);o.selected=scopeKey(s)===scopeKey(scope);scopeSelect.append(o)});actions.append(dot,scopeSelect,refresh,logout);top.append(title,actions);const content=el('div','content');content.id='crmContent';main.append(top,content);root.append(side,main);app.append(root);refresh.onclick=renderCurrent;logout.onclick=signOut;scopeSelect.onchange=async()=>{scope=scopes[Number(scopeSelect.value)||0]||scopes[0];saveScope(scope);scopeSelect.disabled=true;await loadPreferences();await renderCurrent();scopeSelect.disabled=false};addEventListener('hashchange',renderCurrent)}
function setActive(){const v=currentView();document.querySelectorAll('.crm-nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===v))}
function dashboardCards(counts,value){const grid=el('section','grid');[['Accounts',counts.accounts||0],['Contacts',counts.contacts||0],['Active leads',counts.leads||0],['Open deals',counts.opportunities||0],['Pipeline',money(value.pipelineCents||0)]].forEach(([label,val])=>{const c=el('article','card');c.append(el('div','k',label),el('div','v',val));grid.append(c)});return grid}
function pipelinePanel(stages){const p=el('section','panel');const head=el('div','panel-head');head.append(el('h2','','SALES PIPELINE'),el('span','muted',scope.dba.name+' · '+currency));p.append(head);const pipe=el('div','pipeline');(stages||[]).forEach(stage=>{const s=el('article','stage');s.append(el('h3','',stage.name),el('div','muted',(stage.opportunities||[]).length+' deals · '+money(stage.valueCents)));(stage.opportunities||[]).forEach(deal=>{const d=el('div','deal');d.append(el('b','',deal.name),el('div','muted',money(deal.amount_cents)+' · '+deal.probability+'%'));s.append(d)});pipe.append(s)});if(!(stages||[]).length)pipe.append(el('div','empty','No pipeline stages yet.'));p.append(pipe);return p}
async function renderDashboard(host){host.append(heading('CRM Command Center','Live customer, lead and pipeline data for '+scope.organization.name+' / '+scope.dba.name+'.'));const [counts,value,pipeline,leads]=await Promise.all([api('/api/crm/counts'),api('/api/crm/value'),api('/api/crm/pipeline'),api('/api/crm/leads?limit=10')]);host.append(dashboardCards(counts.counts||{},value));const panels=el('section','panels');panels.append(pipelinePanel(pipeline.pipeline));const right=el('section','panel');right.append(el('h2','','PRIORITY LEADS'));(leads.leads||[]).forEach(lead=>{const c=el('div','lead');c.append(el('b','',lead.title),el('div','muted','Score '+lead.score+' · '+money(lead.estimated_value_cents)),el('div','',lead.recommendedNextAction||''));right.append(c)});if(!(leads.leads||[]).length)right.append(el('div','empty','No leads yet.'));panels.append(right);host.append(panels)}
async function renderAccounts(host){host.append(heading('Accounts','Companies and organizations managed by the selected ATLAS workspace.'));const data=await api('/api/crm/accounts?limit=100'),rows=(data.accounts||[]).map(x=>[x.name,x.account_type,x.industry||'',x.email||'',x.phone||'',x.status]);const panels=el('section','panels'),list=el('section','panel');list.append(el('h2','','ACCOUNTS'),table(['Name','Type','Industry','Email','Phone','Status'],rows));const fields=[input('name','Account name','text',true),select('accountType',[['prospect','Prospect'],['customer','Customer'],['partner','Partner'],['vendor','Vendor'],['other','Other']]),input('industry','Industry'),input('email','Email','email'),input('phone','Phone'),input('city','City')];panels.append(list,formPanel('NEW ACCOUNT',fields,async f=>{const d=Object.fromEntries(new FormData(f));await api('/api/crm/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)})}));host.append(panels)}
async function renderContacts(host){host.append(heading('Contacts','People connected to CRM accounts and sales activity.'));const [data,accounts]=await Promise.all([api('/api/crm/contacts?limit=100'),api('/api/crm/accounts?limit=100')]),map=new Map((accounts.accounts||[]).map(x=>[x.id,x.name])),rows=(data.contacts||[]).map(x=>[x.display_name,map.get(x.account_id)||'',x.job_title||'',x.email||'',x.phone||'',x.status]);const panels=el('section','panels'),list=el('section','panel');list.append(el('h2','','CONTACTS'),table(['Name','Account','Title','Email','Phone','Status'],rows));const accountOptions=[['','No account']].concat((accounts.accounts||[]).map(x=>[x.id,x.name])),fields=[input('firstName','First name','text',true),input('lastName','Last name','text',true),select('accountId',accountOptions),input('jobTitle','Job title'),input('email','Email','email'),input('phone','Phone')];panels.append(list,formPanel('NEW CONTACT',fields,async f=>{const d=Object.fromEntries(new FormData(f));if(!d.accountId)delete d.accountId;await api('/api/crm/contacts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)})}));host.append(panels)}
async function renderLeads(host){host.append(heading('Leads','Capture, score and prioritize potential business.'));const data=await api('/api/crm/leads?limit=100'),rows=(data.leads||[]).map(x=>[x.title,x.company_name||'',x.person_name||'',x.status,'Score '+x.score,money(x.estimated_value_cents),x.recommendedNextAction||'']);const panels=el('section','panels'),list=el('section','panel');list.append(el('h2','','LEADS'),table(['Lead','Company','Contact','Status','Score','Value','Next action'],rows));const fields=[input('title','Lead / opportunity title','text',true),input('companyName','Company'),input('personName','Contact name'),input('email','Email','email'),input('phone','Phone'),input('estimatedValue','Estimated value','number')];panels.append(list,formPanel('NEW LEAD',fields,async f=>{const d=Object.fromEntries(new FormData(f));d.estimatedValueCents=Math.round((Number(d.estimatedValue)||0)*100);d.currency=currency;delete d.estimatedValue;await api('/api/crm/leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)})}));host.append(panels)}
async function renderOpportunities(host){host.append(heading('Opportunities','Open, won and lost revenue opportunities organized through the ATLAS pipeline.'));const [data,pipeline]=await Promise.all([api('/api/crm/opportunities?limit=100'),api('/api/crm/pipeline')]),rows=(data.opportunities||[]).map(x=>[x.name,x.stage_name,x.status,money(x.amount_cents),x.probability+'%',x.expected_close_date||'']);host.append(pipelinePanel(pipeline.pipeline));const panels=el('section','panels'),list=el('section','panel');list.append(el('h2','','OPPORTUNITIES'),table(['Name','Stage','Status','Amount','Probability','Expected close'],rows));const fields=[input('name','Opportunity name','text',true),input('amount','Amount','number'),input('probability','Probability %','number'),input('expectedCloseDate','Expected close date','date'),input('source','Source')];panels.append(list,formPanel('NEW OPPORTUNITY',fields,async f=>{const d=Object.fromEntries(new FormData(f));d.amountCents=Math.round((Number(d.amount)||0)*100);d.currency=currency;if(d.probability==='')delete d.probability;delete d.amount;await api('/api/crm/opportunities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)})}));host.append(panels)}
async function renderQuotes(host){host.append(heading('Quotes','Create commercial quotes directly from CRM with calculated line totals.'));const data=await api('/api/crm/quotes?limit=100'),rows=(data.quotes||[]).map(x=>[x.quote_number,x.title,x.status,money(x.subtotal_cents),money(x.tax_cents),money(x.total_cents),x.valid_until||'']);const panels=el('section','panels'),list=el('section','panel');list.append(el('h2','','QUOTES'),table(['Quote','Title','Status','Subtotal','Tax','Total','Valid until'],rows));const fields=[input('title','Quote title','text',true),input('description','Line description','text',true),input('quantity','Quantity','number'),input('unitPrice','Unit price','number'),input('discount','Discount','number'),input('tax','Tax','number'),input('validUntil','Valid until','date')];panels.append(list,formPanel('NEW QUOTE',fields,async f=>{const d=Object.fromEntries(new FormData(f)),line={description:d.description,quantity:Number(d.quantity)||1,unitPriceCents:Math.round((Number(d.unitPrice)||0)*100),discountCents:Math.round((Number(d.discount)||0)*100),taxCents:Math.round((Number(d.tax)||0)*100)};await api('/api/crm/quotes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:d.title,currency,validUntil:d.validUntil||null,lines:[line]})})}));host.append(panels)}
async function renderActivities(host){host.append(heading('Activities','Calls, meetings, tasks, follow-ups and other customer-facing work.'));const [data,opps]=await Promise.all([api('/api/crm/activities?limit=100'),api('/api/crm/opportunities?limit=100')]),oppMap=new Map((opps.opportunities||[]).map(x=>[x.id,x.name])),rows=(data.activities||[]).map(x=>[x.activity_type,x.subject,x.status,x.due_at||'',oppMap.get(x.opportunity_id)||'',x.completed_at||'']);const panels=el('section','panels'),list=el('section','panel');list.append(el('h2','','ACTIVITIES'),table(['Type','Subject','Status','Due','Opportunity','Completed'],rows));const oppOptions=[['','No opportunity']].concat((opps.opportunities||[]).map(x=>[x.id,x.name])),fields=[select('activityType',[['task','Task'],['call','Call'],['email','Email'],['meeting','Meeting'],['note','Note'],['sms','SMS'],['demo','Demo'],['follow_up','Follow-up']]),input('subject','Subject','text',true),select('opportunityId',oppOptions),input('dueAt','Due date / time','datetime-local'),input('description','Description')];panels.append(list,formPanel('NEW ACTIVITY',fields,async f=>{const d=Object.fromEntries(new FormData(f));if(!d.opportunityId)delete d.opportunityId;if(!d.dueAt)delete d.dueAt;await api('/api/crm/activities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)})}));host.append(panels)}
async function renderCurrent(){const host=document.getElementById('crmContent');if(!host)return;setActive();host.replaceChildren(el('div','notice','Loading '+scope.dba.name+' CRM data…'));try{host.replaceChildren();const view=currentView();if(view==='accounts')await renderAccounts(host);else if(view==='contacts')await renderContacts(host);else if(view==='leads')await renderLeads(host);else if(view==='opportunities')await renderOpportunities(host);else if(view==='quotes')await renderQuotes(host);else if(view==='activities')await renderActivities(host);else await renderDashboard(host)}catch(err){host.replaceChildren(heading('CRM unavailable','ATLAS could not load this workspace.'),el('div','notice',err.message||'CRM request failed'))}}
async function start(){if(!token)return showLogin();try{const context=await api('/api/core/context'),allowed=(context.scopes||[]).filter(item=>(item.permissions||[]).includes('crm.read'));if(!allowed.length)throw new Error('CRM access is not assigned to this user.');scopes=allowed;const saved=readSavedScope();scope=scopes.find(item=>scopeKey(item)===saved)||scopes[0];saveScope(scope);await loadPreferences();shellLayout();await renderCurrent()}catch(err){if(/authentication|required|invalid_session/i.test(err.message)){clearToken();showLogin('Your ATLAS session expired. Sign in again.');return}showLogin(err.message)}}
start();`}
