export function crmClientScript(){return `const app=document.getElementById('app');let token='',scope=null,scopes=[],currency='USD';
const readToken=()=>{try{const canonical=sessionStorage.getItem('atlas.session')||'';if(canonical)return canonical;const legacy=sessionStorage.getItem('atlas_session')||'';if(legacy){sessionStorage.setItem('atlas.session',legacy);sessionStorage.removeItem('atlas_session')}return legacy}catch{return''}};
const saveToken=value=>{token=value;try{sessionStorage.setItem('atlas.session',value);sessionStorage.removeItem('atlas_session')}catch{}};
const clearToken=()=>{token='';try{sessionStorage.removeItem('atlas.session');sessionStorage.removeItem('atlas_session')}catch{}};
const scopeKey=s=>s.organization.id+':'+s.dba.id,readSavedScope=()=>{try{return sessionStorage.getItem('atlas.workspace.scope')||sessionStorage.getItem('atlas.dashboard.scope')||''}catch{return''}},saveScope=s=>{try{const key=scopeKey(s);sessionStorage.setItem('atlas.workspace.scope',key);sessionStorage.setItem('atlas.dashboard.scope',key)}catch{}};
token=readToken();
const money=n=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:0}).format((Number(n)||0)/100)}catch{return ((Number(n)||0)/100).toLocaleString()+' '+currency}};
const el=(tag,cls,value)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(value!==undefined)node.textContent=String(value);return node};
async function api(path,opt={}){const headers={...(opt.headers||{})};if(token)headers.authorization='Bearer '+token;if(scope){headers['x-atlas-organization']=scope.organization.id;headers['x-atlas-dba']=scope.dba.id}const response=await fetch(path,{...opt,headers,cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||('HTTP '+response.status));return body}
async function loadPreferences(){currency='USD';try{const d=await api('/api/settings'),preferred=String(d?.preferences?.['company.defaultCurrency']?.value||'USD').toUpperCase();if(/^[A-Z]{3}$/.test(preferred))currency=preferred}catch{}}
function showLogin(message=''){app.replaceChildren();const box=el('section','panel login');box.append(el('div','brand','ATLAS CRM'),el('p','muted','Secure enterprise customer relationship management.'));const form=el('form');const email=el('input'),password=el('input'),error=el('div','error'),button=el('button','', 'Sign in');email.type='email';email.placeholder='Email';email.required=true;password.type='password';password.placeholder='Password';password.required=true;error.textContent=message;form.append(email,password,error,button);form.addEventListener('submit',async event=>{event.preventDefault();error.textContent='';try{const result=await api('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});saveToken(result.sessionToken);await start()}catch(err){error.textContent=err.message}});box.append(form);app.append(box)}
async function signOut(){try{if(token)await api('/api/auth/logout',{method:'POST'})}catch{}clearToken();scope=null;scopes=[];location.assign('/login')}
function layout(){app.replaceChildren();const shell=el('div','shell'),top=el('div','top'),left=el('div'),brand=el('div','brand','ATLAS CRM'),context=el('div','muted'),actions=el('div','row'),dot=el('span','dot'),version=el('span','muted','CRM v1'),scopeSelect=el('select'),refresh=el('button','secondary','Refresh'),logout=el('button','secondary','Sign out');context.id='ctx';scopeSelect.setAttribute('aria-label','ATLAS organization and DBA');scopeSelect.style.cssText='max-width:260px;border:1px solid rgba(170,211,255,.28);border-radius:12px;padding:9px 10px;background:#091827;color:#edf6ff';scopes.forEach((s,i)=>{const o=el('option');o.value=String(i);o.textContent=s.organization.name+' · '+s.dba.name;o.selected=scopeKey(s)===scopeKey(scope);scopeSelect.append(o)});left.append(brand,context);actions.append(dot,version,scopeSelect,refresh,logout);top.append(left,actions);const kpis=el('div','grid');kpis.id='kpis';const panels=el('div','panels'),pipelinePanel=el('section','panel'),formPanel=el('section','panel');pipelinePanel.append(el('h2','', 'Sales pipeline'));const pipeline=el('div','pipeline');pipeline.id='pipe';pipelinePanel.append(pipeline);formPanel.append(el('h2','', 'New lead'));const form=el('form');form.id='leadform';const fields=[['lt','Lead / opportunity title','text'],['lc','Company','text'],['lp','Contact name','text'],['le','Email','email'],['lv','Estimated value','number']];for(const [id,placeholder,type] of fields){const input=el('input');input.id=id;input.placeholder=placeholder;input.type=type;if(id==='lt')input.required=true;if(id==='lv'){input.min='0';input.step='1'}form.append(input)}const formError=el('div','error');formError.id='lead_error';form.append(formError,el('button','', 'Create lead'));formPanel.append(form,el('h2','', 'Priority leads'));const leads=el('div');leads.id='leads';formPanel.append(leads);panels.append(pipelinePanel,formPanel);shell.append(top,kpis,panels);app.append(shell);const renderContext=()=>{context.textContent=scope.organization.name+' · '+scope.dba.name+' · '+currency};renderContext();refresh.onclick=refreshAll;logout.onclick=signOut;form.onsubmit=createLead;scopeSelect.onchange=async()=>{scope=scopes[Number(scopeSelect.value)||0]||scopes[0];saveScope(scope);scopeSelect.disabled=true;await loadPreferences();renderContext();await refreshAll();scopeSelect.disabled=false}}
async function createLead(event){event.preventDefault();const error=document.getElementById('lead_error'),title=document.getElementById('lt'),company=document.getElementById('lc'),person=document.getElementById('lp'),email=document.getElementById('le'),value=document.getElementById('lv');error.textContent='';try{await api('/api/crm/leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:title.value,companyName:company.value,personName:person.value,email:email.value,estimatedValueCents:Math.round((Number(value.value)||0)*100),currency})});event.currentTarget.reset();await refreshAll()}catch(err){error.textContent=err.message}}
function renderKpis(data){const target=document.getElementById('kpis');target.replaceChildren();const c=data.counts||{},p=data.value||{};for(const [label,value] of [['Accounts',c.accounts||0],['Contacts',c.contacts||0],['Active leads',c.leads||0],['Open deals',c.opportunities||0],['Pipeline',money(p.pipelineCents||0)]]){const card=el('div','card');card.append(el('div','k',label),el('div','v',value));target.append(card)}}
function renderPipeline(stages){const target=document.getElementById('pipe');target.replaceChildren();for(const stage of stages||[]){const column=el('div','stage');column.append(el('h3','',stage.name),el('div','muted',(stage.opportunities||[]).length+' deals · '+money(stage.valueCents)));for(const deal of stage.opportunities||[]){const card=el('div','deal');card.append(el('b','',deal.name),el('div','muted',money(deal.amount_cents)+' · '+deal.probability+'%'));column.append(card)}target.append(column)}}
function renderLeads(rows){const target=document.getElementById('leads');target.replaceChildren();if(!(rows||[]).length){target.append(el('span','muted','No leads yet.'));return}for(const lead of rows){const card=el('div','lead');card.append(el('b','',lead.title),el('div','muted','Score '+lead.score+' · '+money(lead.estimated_value_cents)),el('div','',lead.recommendedNextAction||''));target.append(card)}}
async function refreshAll(){try{const [counts,value,pipeline,leads]=await Promise.all([api('/api/crm/counts'),api('/api/crm/value'),api('/api/crm/pipeline'),api('/api/crm/leads?limit=12')]);renderKpis({counts:counts.counts,value});renderPipeline(pipeline.pipeline);renderLeads(leads.leads)}catch(err){console.error('CRM refresh failed',err)}}
async function start(){if(!token)return showLogin();try{const context=await api('/api/core/context'),allowed=(context.scopes||[]).filter(item=>(item.permissions||[]).includes('crm.read'));if(!allowed.length)throw new Error('CRM access is not assigned to this user.');scopes=allowed;const saved=readSavedScope();scope=scopes.find(item=>scopeKey(item)===saved)||scopes[0];saveScope(scope);await loadPreferences();layout();await refreshAll()}catch(err){if(/authentication|required|invalid_session/i.test(err.message)){clearToken();showLogin('Your ATLAS session expired. Sign in again.');return}showLogin(err.message)}}
start();`}
