let ready=false,promise=null;
const statements=[
`CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,title TEXT NOT NULL,document_type TEXT NOT NULL DEFAULT 'document',status TEXT NOT NULL DEFAULT 'draft',owner_user_id TEXT,template_id TEXT,summary TEXT,current_version INTEGER NOT NULL DEFAULT 1,archived_at TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK(document_type IN ('document','policy','procedure','contract','memo','report','form','other')),CHECK(status IN ('draft','in_review','approved','rejected','archived')),CHECK(current_version>=1))`,
`CREATE INDEX IF NOT EXISTS idx_documents_scope ON documents(organization_id,dba_id,status,document_type,updated_at DESC)`,
`CREATE TABLE IF NOT EXISTS document_versions(id TEXT PRIMARY KEY,document_id TEXT NOT NULL,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,version_number INTEGER NOT NULL,title TEXT NOT NULL,content_text TEXT,change_note TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE,UNIQUE(document_id,version_number),CHECK(version_number>=1))`,
`CREATE INDEX IF NOT EXISTS idx_document_versions_scope ON document_versions(organization_id,dba_id,document_id,version_number DESC)`,
`CREATE TABLE IF NOT EXISTS document_templates(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,name TEXT NOT NULL,document_type TEXT NOT NULL DEFAULT 'document',description TEXT,content_text TEXT,status TEXT NOT NULL DEFAULT 'active',created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,dba_id,name),CHECK(status IN ('active','inactive','archived')))`,
`CREATE INDEX IF NOT EXISTS idx_document_templates_scope ON document_templates(organization_id,dba_id,status,name)`,
`CREATE TABLE IF NOT EXISTS document_approvals(id TEXT PRIMARY KEY,document_id TEXT NOT NULL,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,requested_by_user_id TEXT,approver_user_id TEXT,status TEXT NOT NULL DEFAULT 'pending',decision_note TEXT,decided_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE,CHECK(status IN ('pending','approved','rejected','cancelled')))`,
`CREATE INDEX IF NOT EXISTS idx_document_approvals_scope ON document_approvals(organization_id,dba_id,status,created_at DESC)`
];
export async function ensureDocumentsSchema(env){if(ready)return{ok:true,created:false};if(!env?.DB)return{ok:false,error:'identity_database_unavailable'};if(!promise)promise=(async()=>{for(const sql of statements)await env.DB.prepare(sql).run();ready=true;return{ok:true,created:true}})().catch(e=>{promise=null;throw e});return promise}
