import { requireTenantPermission } from './tenant.js';
import { appendAuditLedger } from './audit.js';
import { ensureGlobalPromoSchema } from './global-promo-schema.js';
import { globalPromoPage } from './global-promo-ui.js';

const JOB_STATUSES=new Set(['request','quoted','artwork','approval','materials','production','quality_control','packing','ready','delivered','cancelled']);
const JOB_PRIORITIES=new Set(['low','normal','high','urgent']);
const METHODS=new Set(['embroidery','screen_print','dtg','heat_transfer','promotional','mixed','other']);
const ART_STATUSES=new Set(['draft','submitted','approved','rejected','superseded']);
const MATERIAL_STATUSES=new Set(['required','ordered','received','allocated','issued','cancelled']);
const PO_STATUSES=new Set(['draft','pending_approval','approved','ordered','partial','received','cancelled']);
const WO_STATUSES=new Set(['planned','scheduled','in_progress','paused','completed','cancelled']);
const QC_RESULTS=new Set(['pass','fail','rework']);
const PACKAGE_STATUSES=new Set(['packing','packed','shipped','delivered','exception','cancelled']);
const TRANSITIONS={
 request:new Set(['quoted','cancelled']),quoted:new Set(['artwork','materials','cancelled']),artwork:new Set(['approval','cancelled']),approval:new Set(['artwork','materials','cancelled']),materials:new Set(['production','cancelled']),production:new Set(['quality_control','cancelled']),quality_control:new Set(['production','packing','cancelled']),packing:new Set(['ready','cancelled']),ready:new Set(['delivered','packing','cancelled']),delivered:new Set(),cancelled:new Set()
};
const PO_TRANSITIONS={draft:new Set(['pending_approval','cancelled']),pending_approval:new Set(['approved','draft','cancelled']),approved:new Set(['ordered','cancelled']),ordered:new Set(['partial','received','cancelled']),partial:new Set(['received','cancelled']),received:new Set(),cancelled:new Set()};
const WO_TRANSITIONS={planned:new Set(['scheduled','in_progress','cancelled']),scheduled:new Set(['in_progress','cancelled']),in_progress:new Set(['paused','completed','cancelled']),paused:new Set(['in_progress','completed','cancelled']),completed:new Set(),cancelled:new Set()};
const PACKAGE_TRANSITIONS={packing:new Set(['packed','cancelled']),packed:new Set(['shipped','packing','cancelled']),shipped:new Set(['delivered','exception']),exception:new Set(['shipped','delivered','cancelled']),delivered:new Set(),cancelled:new Set()};

const json=(body,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}});
const html=body=>new Response(body,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline' 'self'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"}});
function text(v,max=240){return String(v??'').trim().replace(/\s+/g,' ').slice(0,max)}
function nullable(v,max=1000){const x=text(v,max);return x||null}
function isoDate(v){const x=text(v,10);return /^\d{4}-\d{2}-\d{2}$/.test(x)?x:null}
function integer(v,min=0,max=Number.MAX_SAFE_INTEGER){const n=Number(v);if(!Number.isFinite(n))return null;const x=Math.round(n);return Number.isSafeInteger(x)&&x>=min&&x<=max?x:null}
function cents(v){const n=Number(v);if(!Number.isFinite(n)||n<0)return null;const x=Math.round(n*100);return Number.isSafeInteger(x)?x:null}
function milli(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return null;const x=Math.round(n*1000);return Number.isSafeInteger(x)?x:null}
async function bodyJson(request,maxBytes=524288){const raw=await request.text();if(raw.length>maxBytes)return{ok:false,status:413,error:'payload_too_large'};if(!raw.trim())return{ok:true,body:{}};try{return{ok:true,body:JSON.parse(raw)}}catch{return{ok:false,status:400,error:'invalid_json'}}}
async function authorize(request,env,permission,action){const authz=await requireTenantPermission(request,env,permission,action);if(!authz.ok)return{response:json({ok:false,error:authz.error},authz.status)};try{const schema=await ensureGlobalPromoSchema(env);if(!schema.ok)return{response:json({ok:false,error:schema.error},503)}}catch{return{response:json({ok:false,error:'global_promo_schema_unavailable'},503)}}return{authz}}
async function audit(env,a,action,type,id,metadata=null){try{await appendAuditLedger(env,{organizationId:a.organizationId,dbaId:a.dbaId,actorUserId:a.session.user_id,category:'global_promo',action,resourceType:type,resourceId:id,decision:'allow',severity:'info',correlationId:a.correlationId,metadata});return true}catch{return false}}
async function job(env,a,id){return env.DB.prepare(`SELECT * FROM global_promo_jobs WHERE id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first()}
async function scopedExists(env,table,id,a){if(!id)return true;try{return Boolean(await env.DB.prepare(`SELECT id FROM ${table} WHERE id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first())}catch{return false}}

async function overview(request,env){const g=await authorize(request,env,'module.read','global_promo.overview.read');if(g.response)return g.response;const{authz:a}=g;const [jobs,art,po,work,qc,pack]=await env.DB.batch([
 env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status NOT IN ('delivered','cancelled') THEN 1 ELSE 0 END) active,SUM(CASE WHEN due_date<CURRENT_DATE AND status NOT IN ('delivered','cancelled') THEN 1 ELSE 0 END) overdue FROM global_promo_jobs WHERE organization_id=? AND dba_id=?`).bind(a.organizationId,a.dbaId),
 env.DB.prepare(`SELECT COUNT(*) pending FROM global_promo_artwork_versions WHERE organization_id=? AND dba_id=? AND status='submitted'`).bind(a.organizationId,a.dbaId),
 env.DB.prepare(`SELECT COUNT(*) pending FROM global_promo_purchase_orders WHERE organization_id=? AND dba_id=? AND status IN ('draft','pending_approval','approved','ordered','partial')`).bind(a.organizationId,a.dbaId),
 env.DB.prepare(`SELECT COUNT(*) active FROM global_promo_work_orders WHERE organization_id=? AND dba_id=? AND status IN ('planned','scheduled','in_progress','paused')`).bind(a.organizationId,a.dbaId),
 env.DB.prepare(`SELECT COUNT(*) attention FROM global_promo_quality_checks WHERE organization_id=? AND dba_id=? AND result IN ('fail','rework') AND inspected_at>=datetime('now','-30 days')`).bind(a.organizationId,a.dbaId),
 env.DB.prepare(`SELECT COUNT(*) active FROM global_promo_packages WHERE organization_id=? AND dba_id=? AND status NOT IN ('delivered','cancelled')`).bind(a.organizationId,a.dbaId)
 ]);return json({ok:true,overview:{jobsTotal:Number(jobs.results?.[0]?.total||0),jobsActive:Number(jobs.results?.[0]?.active||0),jobsOverdue:Number(jobs.results?.[0]?.overdue||0),artworkPending:Number(art.results?.[0]?.pending||0),purchaseOrdersOpen:Number(po.results?.[0]?.pending||0),workOrdersActive:Number(work.results?.[0]?.active||0),qualityAttention30d:Number(qc.results?.[0]?.attention||0),packagesActive:Number(pack.results?.[0]?.active||0)}})}

async function listJobs(request,env){const g=await authorize(request,env,'module.read','global_promo.jobs.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT id,job_number,title,customer_account_id,quote_id,request_reference,production_method,quantity,status,requested_date,due_date,priority,notes,created_at,updated_at FROM global_promo_jobs WHERE organization_id=? AND dba_id=? ORDER BY CASE status WHEN 'request' THEN 0 WHEN 'quoted' THEN 1 WHEN 'artwork' THEN 2 WHEN 'approval' THEN 3 WHEN 'materials' THEN 4 WHEN 'production' THEN 5 WHEN 'quality_control' THEN 6 WHEN 'packing' THEN 7 WHEN 'ready' THEN 8 ELSE 9 END,COALESCE(due_date,'9999-12-31'),updated_at DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,jobs:rows.results||[]})}
async function createJob(request,env){const g=await authorize(request,env,'module.write','global_promo.job.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,title=text(b.title,220),method=text(b.productionMethod||'mixed',30),priority=text(b.priority||'normal',20),quantity=integer(b.quantity,1,10000000),requested=b.requestedDate?isoDate(b.requestedDate):null,due=b.dueDate?isoDate(b.dueDate):null,accountId=nullable(b.customerAccountId,128),quoteId=nullable(b.quoteId,128);if(title.length<2||!METHODS.has(method)||!JOB_PRIORITIES.has(priority)||quantity==null||(b.requestedDate&&!requested)||(b.dueDate&&!due))return json({ok:false,error:'valid_global_promo_job_required'},400);if(accountId&&!await scopedExists(env,'crm_accounts',accountId,a))return json({ok:false,error:'customer_account_not_found'},404);if(quoteId&&!await scopedExists(env,'crm_quotes',quoteId,a))return json({ok:false,error:'quote_not_found'},404);const id=crypto.randomUUID(),number=text(b.jobNumber||`GP-${Date.now().toString(36).toUpperCase()}`,80).toUpperCase();try{await env.DB.prepare(`INSERT INTO global_promo_jobs(id,organization_id,dba_id,job_number,title,customer_account_id,quote_id,request_reference,production_method,quantity,status,requested_date,due_date,priority,notes,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,'request',?,?,?,?,?)`).bind(id,a.organizationId,a.dbaId,number,title,accountId,quoteId,nullable(b.requestReference,300),method,quantity,requested,due,priority,nullable(b.notes,4000),a.session.user_id).run()}catch{return json({ok:false,error:'global_promo_job_number_conflict'},409)}return json({ok:true,job:{id,jobNumber:number,title,status:'request'},auditRecorded:await audit(env,a,'global_promo.job.create','global_promo_job',id,{jobNumber:number,method,quantity})},201)}
async function updateJob(request,env,id){const g=await authorize(request,env,'module.write','global_promo.job.update');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const current=await job(env,a,id);if(!current)return json({ok:false,error:'global_promo_job_not_found'},404);const status=text(p.body.status||current.status,30),priority=text(p.body.priority||current.priority,20),due=p.body.dueDate===undefined?current.due_date:(p.body.dueDate?isoDate(p.body.dueDate):null);if(!JOB_STATUSES.has(status)||!JOB_PRIORITIES.has(priority)||(p.body.dueDate&&!due))return json({ok:false,error:'invalid_global_promo_job_update'},400);if(status!==current.status&&!TRANSITIONS[current.status]?.has(status))return json({ok:false,error:'invalid_job_status_transition',from:current.status,to:status},409);
 if(status==='quality_control'){const row=await env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status NOT IN ('completed','cancelled') THEN 1 ELSE 0 END) incomplete FROM global_promo_work_orders WHERE job_id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(Number(row?.total||0)>0&&Number(row?.incomplete||0)>0)return json({ok:false,error:'work_orders_incomplete'},409)}
 if(status==='packing'){const row=await env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN result='pass' THEN 1 ELSE 0 END) passed FROM global_promo_quality_checks WHERE job_id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(Number(row?.total||0)>0&&Number(row?.passed||0)===0)return json({ok:false,error:'quality_pass_required'},409)}
 if(status==='delivered'){const row=await env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status NOT IN ('delivered','cancelled') THEN 1 ELSE 0 END) open FROM global_promo_packages WHERE job_id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(Number(row?.total||0)>0&&Number(row?.open||0)>0)return json({ok:false,error:'packages_not_delivered'},409)}
 await env.DB.prepare(`UPDATE global_promo_jobs SET status=?,priority=?,due_date=?,notes=COALESCE(?,notes),updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(status,priority,due,nullable(p.body.notes,4000),id).run();return json({ok:true,job:{id,status,priority,dueDate:due},auditRecorded:await audit(env,a,'global_promo.job.update','global_promo_job',id,{from:current.status,status,priority})})}

async function listArtwork(request,env){const g=await authorize(request,env,'module.read','global_promo.artwork.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT av.*,j.job_number,j.title AS job_title FROM global_promo_artwork_versions av JOIN global_promo_jobs j ON j.id=av.job_id WHERE av.organization_id=? AND av.dba_id=? ORDER BY av.created_at DESC,av.version_no DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,artwork:rows.results||[]})}
async function createArtwork(request,env){const g=await authorize(request,env,'module.write','global_promo.artwork.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,jobId=text(b.jobId,128),fileReference=text(b.fileReference,1000),submit=Boolean(b.submit),owner=await job(env,a,jobId);if(!owner||fileReference.length<2)return json({ok:false,error:'valid_artwork_required'},400);const row=await env.DB.prepare(`SELECT COALESCE(MAX(version_no),0)+1 next_version FROM global_promo_artwork_versions WHERE job_id=?`).bind(jobId).first(),version=Number(row?.next_version||1),id=crypto.randomUUID(),status=submit?'submitted':'draft';await env.DB.prepare(`INSERT INTO global_promo_artwork_versions(id,organization_id,dba_id,job_id,version_no,file_reference,mockup_reference,customer_note,internal_note,status,submitted_at,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,${submit?'CURRENT_TIMESTAMP':'NULL'},?)`).bind(id,a.organizationId,a.dbaId,jobId,version,fileReference,nullable(b.mockupReference,1000),nullable(b.customerNote,2000),nullable(b.internalNote,2000),status,a.session.user_id).run();if(submit&&owner.status==='artwork')await env.DB.prepare(`UPDATE global_promo_jobs SET status='approval',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(jobId).run();return json({ok:true,artwork:{id,jobId,version,status},auditRecorded:await audit(env,a,'global_promo.artwork.create','global_promo_artwork',id,{jobId,version,status})},201)}
async function decideArtwork(request,env,id){const g=await authorize(request,env,'module.write','global_promo.artwork.decide');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const decision=text(p.body.decision,20),evidence=nullable(p.body.evidenceReference,1000);if(!['approved','rejected'].includes(decision)||(decision==='approved'&&!evidence))return json({ok:false,error:'valid_artwork_decision_required'},400);const row=await env.DB.prepare(`SELECT * FROM global_promo_artwork_versions WHERE id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(!row)return json({ok:false,error:'artwork_not_found'},404);if(row.status!=='submitted')return json({ok:false,error:'artwork_not_submitted'},409);const ops=[env.DB.prepare(`UPDATE global_promo_artwork_versions SET status=?,customer_note=COALESCE(?,customer_note),decision_by_user_id=?,approval_evidence_reference=?,decided_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(decision,nullable(p.body.customerNote,2000),a.session.user_id,evidence,id)];if(decision==='approved'){ops.push(env.DB.prepare(`UPDATE global_promo_artwork_versions SET status='superseded',updated_at=CURRENT_TIMESTAMP WHERE job_id=? AND id<>? AND status='approved'`).bind(row.job_id,id));ops.push(env.DB.prepare(`UPDATE global_promo_jobs SET status=CASE WHEN status IN ('artwork','approval') THEN 'materials' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(row.job_id))}else ops.push(env.DB.prepare(`UPDATE global_promo_jobs SET status=CASE WHEN status='approval' THEN 'artwork' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(row.job_id));await env.DB.batch(ops);return json({ok:true,artwork:{id,status:decision,jobId:row.job_id},auditRecorded:await audit(env,a,'global_promo.artwork.decide','global_promo_artwork',id,{jobId:row.job_id,decision,evidenceReference:evidence})})}

async function listEmbroidery(request,env){const g=await authorize(request,env,'module.read','global_promo.embroidery.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT e.*,j.job_number,j.title AS job_title,ROUND(e.digitizing_cost_cents+(e.stitch_count/1000.0)*e.internal_cost_per_thousand_cents*e.quantity) AS estimated_cost_cents FROM global_promo_embroidery_specs e JOIN global_promo_jobs j ON j.id=e.job_id WHERE e.organization_id=? AND e.dba_id=? ORDER BY e.created_at DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,embroidery:rows.results||[]})}
async function createEmbroidery(request,env){const g=await authorize(request,env,'module.write','global_promo.embroidery.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,jobId=text(b.jobId,128),placement=text(b.placement,160),stitches=integer(b.stitchCount,0,10000000),quantity=integer(b.quantity,1,10000000),digitizing=cents(b.digitizingCost??0),perK=cents(b.internalCostPerThousand??0);if(!await job(env,a,jobId)||placement.length<2||stitches==null||quantity==null||digitizing==null||perK==null)return json({ok:false,error:'valid_embroidery_spec_required'},400);const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO global_promo_embroidery_specs(id,organization_id,dba_id,job_id,placement,thread_colors,width_mm,height_mm,stitch_count,quantity,digitizing_cost_cents,internal_cost_per_thousand_cents,machine_profile,notes,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,a.organizationId,a.dbaId,jobId,placement,nullable(b.threadColors,500),b.widthMm?integer(b.widthMm,1,10000):null,b.heightMm?integer(b.heightMm,1,10000):null,stitches,quantity,digitizing,perK,nullable(b.machineProfile,300),nullable(b.notes,2000),a.session.user_id).run();return json({ok:true,spec:{id,jobId,placement,stitchCount:stitches,quantity,estimatedCostCents:Math.round(digitizing+(stitches/1000)*perK*quantity)},auditRecorded:await audit(env,a,'global_promo.embroidery.create','global_promo_embroidery_spec',id,{jobId,stitches,quantity})},201)}

async function listMaterials(request,env){const g=await authorize(request,env,'module.read','global_promo.materials.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT m.*,j.job_number,j.title AS job_title FROM global_promo_material_requirements m JOIN global_promo_jobs j ON j.id=m.job_id WHERE m.organization_id=? AND m.dba_id=? ORDER BY CASE m.status WHEN 'required' THEN 0 WHEN 'ordered' THEN 1 WHEN 'received' THEN 2 WHEN 'allocated' THEN 3 WHEN 'issued' THEN 4 ELSE 5 END,m.created_at DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,materials:rows.results||[]})}
async function createMaterial(request,env){const g=await authorize(request,env,'module.write','global_promo.material.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,jobId=text(b.jobId,128),description=text(b.description,500),itemId=nullable(b.inventoryItemId,128),qty=milli(b.quantity),unitCost=cents(b.estimatedUnitCost??0),vendorId=nullable(b.supplierVendorId,128);if(!await job(env,a,jobId)||description.length<2||qty==null||unitCost==null)return json({ok:false,error:'valid_material_requirement_required'},400);if(itemId&&!await scopedExists(env,'inventory_items',itemId,a))return json({ok:false,error:'inventory_item_not_found'},404);if(vendorId&&!await scopedExists(env,'operations_vendors',vendorId,a))return json({ok:false,error:'supplier_vendor_not_found'},404);const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO global_promo_material_requirements(id,organization_id,dba_id,job_id,inventory_item_id,sku_reference,description,quantity_milli,estimated_unit_cost_cents,supplier_vendor_id,status,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,'required',?)`).bind(id,a.organizationId,a.dbaId,jobId,itemId,nullable(b.skuReference,120),description,qty,unitCost,vendorId,a.session.user_id).run();return json({ok:true,material:{id,jobId,description,quantityMilli:qty,status:'required'},auditRecorded:await audit(env,a,'global_promo.material.create','global_promo_material',id,{jobId,itemId,qty})},201)}
async function updateMaterial(request,env,id){const g=await authorize(request,env,'module.write','global_promo.material.update');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const row=await env.DB.prepare(`SELECT * FROM global_promo_material_requirements WHERE id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(!row)return json({ok:false,error:'material_requirement_not_found'},404);const status=text(p.body.status||row.status,30),allocated=p.body.allocatedQuantity===undefined?Number(row.allocated_milli):milli(p.body.allocatedQuantity);if(!MATERIAL_STATUSES.has(status)||allocated==null||allocated>Number(row.quantity_milli))return json({ok:false,error:'invalid_material_update'},400);await env.DB.prepare(`UPDATE global_promo_material_requirements SET status=?,allocated_milli=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(status,allocated,id).run();return json({ok:true,material:{id,status,allocatedMilli:allocated},auditRecorded:await audit(env,a,'global_promo.material.update','global_promo_material',id,{status,allocated})})}

async function listPurchaseOrders(request,env){const g=await authorize(request,env,'module.read','global_promo.purchasing.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT p.*,j.job_number,j.title AS job_title,(SELECT COUNT(*) FROM global_promo_purchase_order_lines l WHERE l.purchase_order_id=p.id) line_count FROM global_promo_purchase_orders p LEFT JOIN global_promo_jobs j ON j.id=p.job_id WHERE p.organization_id=? AND p.dba_id=? ORDER BY p.created_at DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,purchaseOrders:rows.results||[]})}
async function createPurchaseOrder(request,env){const g=await authorize(request,env,'module.write','global_promo.purchase_order.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request,1048576);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,vendorName=text(b.vendorName,220),vendorId=nullable(b.vendorId,128),jobId=nullable(b.jobId,128),orderDate=isoDate(b.orderDate)||new Date().toISOString().slice(0,10),expected=b.expectedDate?isoDate(b.expectedDate):null,lines=Array.isArray(b.lines)?b.lines.slice(0,100):[];if(vendorName.length<2||!lines.length||(b.expectedDate&&!expected))return json({ok:false,error:'valid_purchase_order_required'},400);if(jobId&&!await job(env,a,jobId))return json({ok:false,error:'global_promo_job_not_found'},404);if(vendorId&&!await scopedExists(env,'operations_vendors',vendorId,a))return json({ok:false,error:'supplier_vendor_not_found'},404);let subtotal=0;const normalized=[];for(let i=0;i<lines.length;i++){const line=lines[i],description=text(line?.description,500),quantity=Number(line?.quantity),unit=cents(line?.unitCost);if(description.length<2||!Number.isFinite(quantity)||quantity<=0||unit==null)return json({ok:false,error:'invalid_purchase_order_line'},400);const total=Math.round(quantity*unit);subtotal+=total;normalized.push({description,quantity,unit,total,itemId:nullable(line?.inventoryItemId,128),position:i})}const shipping=cents(b.shipping??0),tax=cents(b.tax??0);if(shipping==null||tax==null)return json({ok:false,error:'invalid_purchase_order_amount'},400);const id=crypto.randomUUID(),number=text(b.poNumber||`PO-${Date.now().toString(36).toUpperCase()}`,80).toUpperCase(),total=subtotal+shipping+tax,ops=[env.DB.prepare(`INSERT INTO global_promo_purchase_orders(id,organization_id,dba_id,po_number,job_id,vendor_id,vendor_name,order_date,expected_date,status,currency,subtotal_cents,shipping_cents,tax_cents,total_cents,notes,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,'draft',?,?,?,?,?,?,?)`).bind(id,a.organizationId,a.dbaId,number,jobId,vendorId,vendorName,orderDate,expected,text(b.currency||'USD',3).toUpperCase(),subtotal,shipping,tax,total,nullable(b.notes,3000),a.session.user_id)];for(const line of normalized)ops.push(env.DB.prepare(`INSERT INTO global_promo_purchase_order_lines(id,purchase_order_id,organization_id,dba_id,inventory_item_id,description,quantity,unit_cost_cents,line_total_cents,position) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,a.organizationId,a.dbaId,line.itemId,line.description,line.quantity,line.unit,line.total,line.position));try{await env.DB.batch(ops)}catch{return json({ok:false,error:'purchase_order_conflict'},409)}return json({ok:true,purchaseOrder:{id,poNumber:number,status:'draft',subtotalCents:subtotal,totalCents:total,lines:normalized.length},auditRecorded:await audit(env,a,'global_promo.purchase_order.create','global_promo_purchase_order',id,{poNumber:number,jobId,total})},201)}
async function updatePurchaseOrder(request,env,id){const g=await authorize(request,env,'module.write','global_promo.purchase_order.update');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const row=await env.DB.prepare(`SELECT * FROM global_promo_purchase_orders WHERE id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(!row)return json({ok:false,error:'purchase_order_not_found'},404);const status=text(p.body.status,30);if(!PO_STATUSES.has(status)||status===row.status||!PO_TRANSITIONS[row.status]?.has(status))return json({ok:false,error:'invalid_purchase_order_transition',from:row.status,to:status},409);if(status==='approved'&&!['owner','admin','manager'].includes(a.membership?.role))return json({ok:false,error:'purchase_order_approval_role_required'},403);await env.DB.prepare(`UPDATE global_promo_purchase_orders SET status=?,approved_by_user_id=CASE WHEN ?='approved' THEN ? ELSE approved_by_user_id END,approved_at=CASE WHEN ?='approved' THEN CURRENT_TIMESTAMP ELSE approved_at END,received_at=CASE WHEN ?='received' THEN CURRENT_TIMESTAMP ELSE received_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(status,status,a.session.user_id,status,status,id).run();return json({ok:true,purchaseOrder:{id,status},auditRecorded:await audit(env,a,'global_promo.purchase_order.update','global_promo_purchase_order',id,{from:row.status,status})})}

async function listWorkOrders(request,env){const g=await authorize(request,env,'module.read','global_promo.production.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT w.*,j.job_number,j.title AS job_title,ROUND((w.labor_minutes*w.labor_rate_cents_per_hour)/60.0)+w.machine_cost_cents AS estimated_cost_cents FROM global_promo_work_orders w JOIN global_promo_jobs j ON j.id=w.job_id WHERE w.organization_id=? AND w.dba_id=? ORDER BY CASE w.status WHEN 'in_progress' THEN 0 WHEN 'scheduled' THEN 1 WHEN 'planned' THEN 2 WHEN 'paused' THEN 3 ELSE 4 END,COALESCE(w.scheduled_start,'9999-12-31'),w.created_at DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,workOrders:rows.results||[]})}
async function createWorkOrder(request,env){const g=await authorize(request,env,'module.write','global_promo.work_order.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,jobId=text(b.jobId,128),operation=text(b.operation,220),quantity=integer(b.quantity,1,10000000),labor=integer(b.laborMinutes??0,0,10000000),rate=cents(b.laborRatePerHour??0),machine=cents(b.machineCost??0);if(!await job(env,a,jobId)||operation.length<2||quantity==null||labor==null||rate==null||machine==null)return json({ok:false,error:'valid_work_order_required'},400);const operator=nullable(b.operatorPersonId,128);if(operator&&!await scopedExists(env,'hr_people',operator,a))return json({ok:false,error:'operator_not_found'},404);const id=crypto.randomUUID(),number=text(b.workOrderNumber||`WO-${Date.now().toString(36).toUpperCase()}`,80).toUpperCase();try{await env.DB.prepare(`INSERT INTO global_promo_work_orders(id,organization_id,dba_id,job_id,work_order_number,operation,quantity,machine_reference,operator_person_id,scheduled_start,scheduled_end,status,labor_minutes,labor_rate_cents_per_hour,machine_cost_cents,instructions,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,'planned',?,?,?,?,?)`).bind(id,a.organizationId,a.dbaId,jobId,number,operation,quantity,nullable(b.machineReference,300),operator,nullable(b.scheduledStart,40),nullable(b.scheduledEnd,40),labor,rate,machine,nullable(b.instructions,4000),a.session.user_id).run()}catch{return json({ok:false,error:'work_order_number_conflict'},409)}return json({ok:true,workOrder:{id,workOrderNumber:number,status:'planned',estimatedCostCents:Math.round(labor*rate/60)+machine},auditRecorded:await audit(env,a,'global_promo.work_order.create','global_promo_work_order',id,{jobId,operation,quantity})},201)}
async function updateWorkOrder(request,env,id){const g=await authorize(request,env,'module.write','global_promo.work_order.update');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const row=await env.DB.prepare(`SELECT * FROM global_promo_work_orders WHERE id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(!row)return json({ok:false,error:'work_order_not_found'},404);const status=text(p.body.status,30);if(!WO_STATUSES.has(status)||status===row.status||!WO_TRANSITIONS[row.status]?.has(status))return json({ok:false,error:'invalid_work_order_transition',from:row.status,to:status},409);await env.DB.prepare(`UPDATE global_promo_work_orders SET status=?,started_at=CASE WHEN ?='in_progress' AND started_at IS NULL THEN CURRENT_TIMESTAMP ELSE started_at END,completed_at=CASE WHEN ?='completed' THEN CURRENT_TIMESTAMP ELSE completed_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(status,status,status,id).run();return json({ok:true,workOrder:{id,status},auditRecorded:await audit(env,a,'global_promo.work_order.update','global_promo_work_order',id,{from:row.status,status})})}

async function listQuality(request,env){const g=await authorize(request,env,'module.read','global_promo.quality.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT q.*,j.job_number,j.title AS job_title,w.work_order_number FROM global_promo_quality_checks q JOIN global_promo_jobs j ON j.id=q.job_id LEFT JOIN global_promo_work_orders w ON w.id=q.work_order_id WHERE q.organization_id=? AND q.dba_id=? ORDER BY q.inspected_at DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,qualityChecks:rows.results||[]})}
async function createQuality(request,env){const g=await authorize(request,env,'module.write','global_promo.quality.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,jobId=text(b.jobId,128),name=text(b.checklistName,220),result=text(b.result,20),checked=integer(b.quantityChecked,1,10000000),defects=integer(b.defectsFound??0,0,10000000),workOrderId=nullable(b.workOrderId,128),inspector=nullable(b.inspectorPersonId,128);if(!await job(env,a,jobId)||name.length<2||!QC_RESULTS.has(result)||checked==null||defects==null||defects>checked)return json({ok:false,error:'valid_quality_check_required'},400);if(workOrderId){const w=await env.DB.prepare(`SELECT id FROM global_promo_work_orders WHERE id=? AND job_id=? AND organization_id=? AND dba_id=?`).bind(workOrderId,jobId,a.organizationId,a.dbaId).first();if(!w)return json({ok:false,error:'work_order_not_found_for_job'},404)}if(inspector&&!await scopedExists(env,'hr_people',inspector,a))return json({ok:false,error:'inspector_not_found'},404);const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO global_promo_quality_checks(id,organization_id,dba_id,job_id,work_order_id,checklist_name,result,quantity_checked,defects_found,inspector_person_id,evidence_reference,notes,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,a.organizationId,a.dbaId,jobId,workOrderId,name,result,checked,defects,inspector,nullable(b.evidenceReference,1000),nullable(b.notes,3000),a.session.user_id).run();return json({ok:true,qualityCheck:{id,jobId,result,quantityChecked:checked,defectsFound:defects},auditRecorded:await audit(env,a,'global_promo.quality.create','global_promo_quality_check',id,{jobId,result,checked,defects})},201)}

async function listPackages(request,env){const g=await authorize(request,env,'module.read','global_promo.packing.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT p.*,j.job_number,j.title AS job_title FROM global_promo_packages p JOIN global_promo_jobs j ON j.id=p.job_id WHERE p.organization_id=? AND p.dba_id=? ORDER BY p.created_at DESC`).bind(a.organizationId,a.dbaId).all();return json({ok:true,packages:rows.results||[]})}
async function createPackage(request,env){const g=await authorize(request,env,'module.write','global_promo.package.create');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const b=p.body,jobId=text(b.jobId,128),quantity=integer(b.quantity,1,10000000);if(!await job(env,a,jobId)||quantity==null)return json({ok:false,error:'valid_package_required'},400);const id=crypto.randomUUID(),number=text(b.packageNumber||`PK-${Date.now().toString(36).toUpperCase()}`,80).toUpperCase();try{await env.DB.prepare(`INSERT INTO global_promo_packages(id,organization_id,dba_id,job_id,package_number,quantity,carrier,service_level,tracking_number,status,notes,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,'packing',?,?)`).bind(id,a.organizationId,a.dbaId,jobId,number,quantity,nullable(b.carrier,160),nullable(b.serviceLevel,160),nullable(b.trackingNumber,240),nullable(b.notes,2000),a.session.user_id).run()}catch{return json({ok:false,error:'package_number_conflict'},409)}return json({ok:true,package:{id,packageNumber:number,status:'packing'},auditRecorded:await audit(env,a,'global_promo.package.create','global_promo_package',id,{jobId,quantity})},201)}
async function updatePackage(request,env,id){const g=await authorize(request,env,'module.write','global_promo.package.update');if(g.response)return g.response;const{authz:a}=g,p=await bodyJson(request);if(!p.ok)return json({ok:false,error:p.error},p.status);const row=await env.DB.prepare(`SELECT * FROM global_promo_packages WHERE id=? AND organization_id=? AND dba_id=?`).bind(id,a.organizationId,a.dbaId).first();if(!row)return json({ok:false,error:'package_not_found'},404);const status=text(p.body.status,30);if(!PACKAGE_STATUSES.has(status)||status===row.status||!PACKAGE_TRANSITIONS[row.status]?.has(status))return json({ok:false,error:'invalid_package_transition',from:row.status,to:status},409);await env.DB.prepare(`UPDATE global_promo_packages SET status=?,carrier=COALESCE(?,carrier),service_level=COALESCE(?,service_level),tracking_number=COALESCE(?,tracking_number),delivery_reference=COALESCE(?,delivery_reference),packed_at=CASE WHEN ?='packed' THEN CURRENT_TIMESTAMP ELSE packed_at END,shipped_at=CASE WHEN ?='shipped' THEN CURRENT_TIMESTAMP ELSE shipped_at END,delivered_at=CASE WHEN ?='delivered' THEN CURRENT_TIMESTAMP ELSE delivered_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(status,nullable(p.body.carrier,160),nullable(p.body.serviceLevel,160),nullable(p.body.trackingNumber,240),nullable(p.body.deliveryReference,1000),status,status,status,id).run();return json({ok:true,package:{id,status},auditRecorded:await audit(env,a,'global_promo.package.update','global_promo_package',id,{from:row.status,status})})}

async function costing(request,env){const g=await authorize(request,env,'module.read','global_promo.costing.read');if(g.response)return g.response;const{authz:a}=g;const rows=await env.DB.prepare(`SELECT j.id,j.job_number,j.title,j.status,j.quote_id,
 (SELECT q.total_cents FROM crm_quotes q WHERE q.id=j.quote_id AND q.organization_id=j.organization_id AND q.dba_id=j.dba_id) quote_total_cents,
 COALESCE((SELECT SUM(p.total_cents) FROM global_promo_purchase_orders p WHERE p.job_id=j.id AND p.status NOT IN ('draft','cancelled')),0) procurement_cost_cents,
 COALESCE((SELECT SUM(ROUND(e.digitizing_cost_cents+(e.stitch_count/1000.0)*e.internal_cost_per_thousand_cents*e.quantity)) FROM global_promo_embroidery_specs e WHERE e.job_id=j.id),0) embroidery_cost_cents,
 COALESCE((SELECT SUM(ROUND((w.labor_minutes*w.labor_rate_cents_per_hour)/60.0)+w.machine_cost_cents) FROM global_promo_work_orders w WHERE w.job_id=j.id AND w.status!='cancelled'),0) production_cost_cents,
 COALESCE((SELECT SUM(ROUND((m.quantity_milli/1000.0)*m.estimated_unit_cost_cents)) FROM global_promo_material_requirements m WHERE m.job_id=j.id AND m.status!='cancelled'),0) estimated_material_cost_cents
 FROM global_promo_jobs j WHERE j.organization_id=? AND j.dba_id=? ORDER BY j.updated_at DESC`).bind(a.organizationId,a.dbaId).all();const items=(rows.results||[]).map(r=>{const procurement=Number(r.procurement_cost_cents||0),estimatedMaterials=Number(r.estimated_material_cost_cents||0),materialCost=procurement>0?procurement:estimatedMaterials,embroidery=Number(r.embroidery_cost_cents||0),production=Number(r.production_cost_cents||0),totalCost=materialCost+embroidery+production,revenue=r.quote_total_cents==null?null:Number(r.quote_total_cents),profit=revenue==null?null:revenue-totalCost,margin=revenue&&revenue>0?profit/revenue:null;return{id:r.id,jobNumber:r.job_number,title:r.title,status:r.status,quoteId:r.quote_id,revenueCents:revenue,materialCostCents:materialCost,procurementCostCents:procurement,estimatedMaterialCostCents:estimatedMaterials,embroideryCostCents:embroidery,productionCostCents:production,totalCostCents:totalCost,profitCents:profit,margin}});return json({ok:true,costing:items})}

function section(path){if(path==='/platform/global-promo')return'overview';const id=path.replace('/platform/global-promo/','');return ['jobs','artwork','embroidery','materials','purchasing','production','quality','packing','costing'].includes(id)?id:'overview'}
export async function globalPromoRoutes(request,env,url=new URL(request.url)){
 const path=url.pathname.length>1?url.pathname.replace(/\/+$/,''):url.pathname;
 if(path==='/api/global-promo/overview'&&request.method==='GET')return overview(request,env);
 if(path==='/api/global-promo/jobs'&&request.method==='GET')return listJobs(request,env);
 if(path==='/api/global-promo/jobs'&&request.method==='POST')return createJob(request,env);
 let match=path.match(/^\/api\/global-promo\/jobs\/([^/]+)$/);if(match&&request.method==='PATCH')return updateJob(request,env,decodeURIComponent(match[1]));
 if(path==='/api/global-promo/artwork'&&request.method==='GET')return listArtwork(request,env);
 if(path==='/api/global-promo/artwork'&&request.method==='POST')return createArtwork(request,env);
 match=path.match(/^\/api\/global-promo\/artwork\/([^/]+)\/decision$/);if(match&&request.method==='POST')return decideArtwork(request,env,decodeURIComponent(match[1]));
 if(path==='/api/global-promo/embroidery'&&request.method==='GET')return listEmbroidery(request,env);
 if(path==='/api/global-promo/embroidery'&&request.method==='POST')return createEmbroidery(request,env);
 if(path==='/api/global-promo/materials'&&request.method==='GET')return listMaterials(request,env);
 if(path==='/api/global-promo/materials'&&request.method==='POST')return createMaterial(request,env);
 match=path.match(/^\/api\/global-promo\/materials\/([^/]+)$/);if(match&&request.method==='PATCH')return updateMaterial(request,env,decodeURIComponent(match[1]));
 if(path==='/api/global-promo/purchase-orders'&&request.method==='GET')return listPurchaseOrders(request,env);
 if(path==='/api/global-promo/purchase-orders'&&request.method==='POST')return createPurchaseOrder(request,env);
 match=path.match(/^\/api\/global-promo\/purchase-orders\/([^/]+)$/);if(match&&request.method==='PATCH')return updatePurchaseOrder(request,env,decodeURIComponent(match[1]));
 if(path==='/api/global-promo/work-orders'&&request.method==='GET')return listWorkOrders(request,env);
 if(path==='/api/global-promo/work-orders'&&request.method==='POST')return createWorkOrder(request,env);
 match=path.match(/^\/api\/global-promo\/work-orders\/([^/]+)$/);if(match&&request.method==='PATCH')return updateWorkOrder(request,env,decodeURIComponent(match[1]));
 if(path==='/api/global-promo/quality'&&request.method==='GET')return listQuality(request,env);
 if(path==='/api/global-promo/quality'&&request.method==='POST')return createQuality(request,env);
 if(path==='/api/global-promo/packages'&&request.method==='GET')return listPackages(request,env);
 if(path==='/api/global-promo/packages'&&request.method==='POST')return createPackage(request,env);
 match=path.match(/^\/api\/global-promo\/packages\/([^/]+)$/);if(match&&request.method==='PATCH')return updatePackage(request,env,decodeURIComponent(match[1]));
 if(path==='/api/global-promo/costing'&&request.method==='GET')return costing(request,env);
 if(request.method==='GET'&&(path==='/platform/global-promo'||path.startsWith('/platform/global-promo/')))return html(globalPromoPage(section(path)));
 return null;
}
