let ready=false,promise=null;
const statements=[
`CREATE TABLE IF NOT EXISTS integration_connections(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,name TEXT NOT NULL,provider TEXT NOT NULL,connection_type TEXT NOT NULL DEFAULT 'api',status TEXT NOT NULL DEFAULT 'configured',scope_summary TEXT,sync_mode TEXT NOT NULL DEFAULT 'manual',last_sync_at TEXT,last_error TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,dba_id,name),CHECK(connection_type IN ('api','database','file','email','calendar','storage','messaging','other')),CHECK(status IN ('configured','active','paused','error','disabled')),CHECK(sync_mode IN ('manual','scheduled','event')))`,
`CREATE INDEX IF NOT EXISTS idx_integration_connections_scope ON integration_connections(organization_id,dba_id,status,provider,name)`,
`CREATE TABLE IF NOT EXISTS integration_webhooks(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,connection_id TEXT,name TEXT NOT NULL,event_name TEXT NOT NULL,target_url TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',last_delivery_at TEXT,failure_count INTEGER NOT NULL DEFAULT 0,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(connection_id) REFERENCES integration_connections(id) ON DELETE SET NULL,CHECK(status IN ('active','paused','disabled')),CHECK(failure_count>=0))`,
`CREATE INDEX IF NOT EXISTS idx_integration_webhooks_scope ON integration_webhooks(organization_id,dba_id,status,event_name)`,
`CREATE TABLE IF NOT EXISTS integration_api_clients(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,name TEXT NOT NULL,scopes_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'active',last_used_at TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,dba_id,name),CHECK(status IN ('active','revoked','disabled')))`,
`CREATE INDEX IF NOT EXISTS idx_integration_api_clients_scope ON integration_api_clients(organization_id,dba_id,status,name)`,
`CREATE TABLE IF NOT EXISTS integration_logs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,connection_id TEXT,level TEXT NOT NULL DEFAULT 'info',event_name TEXT NOT NULL,message TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(connection_id) REFERENCES integration_connections(id) ON DELETE SET NULL,CHECK(level IN ('info','warning','error')))`,
`CREATE INDEX IF NOT EXISTS idx_integration_logs_scope ON integration_logs(organization_id,dba_id,created_at DESC,level)`
];
export async function ensureIntegrationsSchema(env){if(ready)return{ok:true,created:false};if(!env?.DB)return{ok:false,error:'identity_database_unavailable'};if(!promise)promise=(async()=>{for(const sql of statements)await env.DB.prepare(sql).run();ready=true;return{ok:true,created:true}})().catch(e=>{promise=null;throw e});return promise}
