let ready=false,promise=null;
const statements=[
`CREATE TABLE IF NOT EXISTS operations_tasks(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT,priority TEXT NOT NULL DEFAULT 'normal',status TEXT NOT NULL DEFAULT 'open',assignee_person_id TEXT,due_date TEXT,completed_at TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(assignee_person_id) REFERENCES hr_people(id) ON DELETE SET NULL,CHECK(priority IN ('low','normal','high','urgent')),CHECK(status IN ('open','in_progress','blocked','completed','cancelled')))`,
`CREATE INDEX IF NOT EXISTS idx_operations_tasks_scope ON operations_tasks(organization_id,dba_id,status,priority,due_date)`,
`CREATE TABLE IF NOT EXISTS operations_workflows(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,name TEXT NOT NULL,description TEXT,trigger_type TEXT NOT NULL DEFAULT 'manual',status TEXT NOT NULL DEFAULT 'active',created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,dba_id,name),CHECK(trigger_type IN ('manual','scheduled','event')),CHECK(status IN ('draft','active','paused','archived')))`,
`CREATE INDEX IF NOT EXISTS idx_operations_workflows_scope ON operations_workflows(organization_id,dba_id,status,name)`,
`CREATE TABLE IF NOT EXISTS operations_workflow_steps(id TEXT PRIMARY KEY,workflow_id TEXT NOT NULL,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,step_order INTEGER NOT NULL,name TEXT NOT NULL,instruction TEXT,requires_approval INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(workflow_id) REFERENCES operations_workflows(id) ON DELETE CASCADE,UNIQUE(workflow_id,step_order),CHECK(step_order>=1),CHECK(requires_approval IN (0,1)))`,
`CREATE TABLE IF NOT EXISTS operations_approvals(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,title TEXT NOT NULL,resource_type TEXT,resource_id TEXT,requested_by_user_id TEXT,approver_user_id TEXT,status TEXT NOT NULL DEFAULT 'pending',decision_note TEXT,decided_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK(status IN ('pending','approved','rejected','cancelled')))`,
`CREATE INDEX IF NOT EXISTS idx_operations_approvals_scope ON operations_approvals(organization_id,dba_id,status,created_at DESC)`,
`CREATE TABLE IF NOT EXISTS operations_vendors(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,email TEXT,phone TEXT,category TEXT,status TEXT NOT NULL DEFAULT 'active',compliance_status TEXT NOT NULL DEFAULT 'pending',notes TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,dba_id,code),CHECK(status IN ('active','inactive','blocked')),CHECK(compliance_status IN ('pending','compliant','review','expired','blocked')))`,
`CREATE INDEX IF NOT EXISTS idx_operations_vendors_scope ON operations_vendors(organization_id,dba_id,status,compliance_status,name)`,
`CREATE TABLE IF NOT EXISTS operations_compliance_items(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,title TEXT NOT NULL,category TEXT,jurisdiction TEXT,owner_person_id TEXT,due_date TEXT,status TEXT NOT NULL DEFAULT 'open',evidence_reference TEXT,notes TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_person_id) REFERENCES hr_people(id) ON DELETE SET NULL,CHECK(status IN ('open','in_review','compliant','expired','waived')))`,
`CREATE INDEX IF NOT EXISTS idx_operations_compliance_scope ON operations_compliance_items(organization_id,dba_id,status,due_date,category)`
];
export async function ensureOperationsSchema(env){if(ready)return{ok:true,created:false};if(!env?.DB)return{ok:false,error:'identity_database_unavailable'};if(!promise)promise=(async()=>{for(const sql of statements)await env.DB.prepare(sql).run();ready=true;return{ok:true,created:true}})().catch(e=>{promise=null;throw e});return promise}
