let ready=false,promise=null;
const statements=[
`CREATE TABLE IF NOT EXISTS fleet_vehicles(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,unit_number TEXT NOT NULL,vin TEXT,license_plate TEXT,make TEXT,model TEXT,model_year INTEGER,vehicle_type TEXT NOT NULL DEFAULT 'car',odometer_miles_milli INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',notes TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,dba_id,unit_number),CHECK(model_year IS NULL OR model_year BETWEEN 1900 AND 2200),CHECK(vehicle_type IN ('car','suv','van','truck','bus','motorcycle','trailer','other')),CHECK(odometer_miles_milli>=0),CHECK(status IN ('active','maintenance','inactive','retired')))`,
`CREATE INDEX IF NOT EXISTS idx_fleet_vehicles_scope ON fleet_vehicles(organization_id,dba_id,status,unit_number)`,
`CREATE TABLE IF NOT EXISTS fleet_driver_assignments(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,vehicle_id TEXT NOT NULL,person_id TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT,status TEXT NOT NULL DEFAULT 'active',created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(vehicle_id) REFERENCES fleet_vehicles(id) ON DELETE RESTRICT,FOREIGN KEY(person_id) REFERENCES hr_people(id) ON DELETE RESTRICT,CHECK(status IN ('active','ended','cancelled')))`,
`CREATE INDEX IF NOT EXISTS idx_fleet_assignments_scope ON fleet_driver_assignments(organization_id,dba_id,status,vehicle_id,person_id)`,
`CREATE TABLE IF NOT EXISTS fleet_trips(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,vehicle_id TEXT NOT NULL,driver_person_id TEXT,origin TEXT,destination TEXT,scheduled_start TEXT,started_at TEXT,ended_at TEXT,distance_miles_milli INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'planned',purpose TEXT,reference TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(vehicle_id) REFERENCES fleet_vehicles(id) ON DELETE RESTRICT,FOREIGN KEY(driver_person_id) REFERENCES hr_people(id) ON DELETE SET NULL,CHECK(distance_miles_milli>=0),CHECK(status IN ('planned','dispatched','in_progress','completed','cancelled')))`,
`CREATE INDEX IF NOT EXISTS idx_fleet_trips_scope ON fleet_trips(organization_id,dba_id,status,scheduled_start,vehicle_id)`,
`CREATE TABLE IF NOT EXISTS fleet_maintenance(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,vehicle_id TEXT NOT NULL,service_type TEXT NOT NULL,description TEXT,due_date TEXT,due_odometer_miles_milli INTEGER,status TEXT NOT NULL DEFAULT 'open',completed_at TEXT,completed_odometer_miles_milli INTEGER,cost_cents INTEGER NOT NULL DEFAULT 0,vendor_id TEXT,reference TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(vehicle_id) REFERENCES fleet_vehicles(id) ON DELETE RESTRICT,CHECK(due_odometer_miles_milli IS NULL OR due_odometer_miles_milli>=0),CHECK(completed_odometer_miles_milli IS NULL OR completed_odometer_miles_milli>=0),CHECK(cost_cents>=0),CHECK(status IN ('open','scheduled','completed','cancelled')))`,
`CREATE INDEX IF NOT EXISTS idx_fleet_maintenance_scope ON fleet_maintenance(organization_id,dba_id,status,due_date,vehicle_id)`,
`CREATE TABLE IF NOT EXISTS fleet_fuel_logs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,dba_id TEXT NOT NULL,vehicle_id TEXT NOT NULL,driver_person_id TEXT,fuel_date TEXT NOT NULL,gallons_milli INTEGER NOT NULL,cost_cents INTEGER NOT NULL,odometer_miles_milli INTEGER,station TEXT,reference TEXT,created_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(vehicle_id) REFERENCES fleet_vehicles(id) ON DELETE RESTRICT,FOREIGN KEY(driver_person_id) REFERENCES hr_people(id) ON DELETE SET NULL,CHECK(gallons_milli>0),CHECK(cost_cents>=0),CHECK(odometer_miles_milli IS NULL OR odometer_miles_milli>=0))`,
`CREATE INDEX IF NOT EXISTS idx_fleet_fuel_scope ON fleet_fuel_logs(organization_id,dba_id,vehicle_id,fuel_date DESC)`
];
export async function ensureTransportationSchema(env){if(ready)return{ok:true,created:false};if(!env?.DB)return{ok:false,error:'identity_database_unavailable'};if(!promise)promise=(async()=>{for(const sql of statements)await env.DB.prepare(sql).run();ready=true;return{ok:true,created:true}})().catch(e=>{promise=null;throw e});return promise}
