const VE_PATHS=new Set(['/ve','/venezuela','/global/ve']);
const MODULES=[
['business','operacion','Business OS','NÚCLEO EMPRESARIAL','Panel unificado para operaciones, documentos, proyectos y control de la organización.','/dashboard','Disponible en ATLAS Core','A'],
['accounting','finanzas','Accounting VE','FINANZAS','Contabilidad y reporting preparados para configuración local venezolana y operación multimoneda.','/finance','Base disponible · capa fiscal por validar','$'],
['pay','finanzas','ATLAS Pay','PAGOS','Cobros y conciliación sobre proveedores autorizados, sin simular conexiones bancarias.','/finance/ar','Requiere proveedor autorizado','P'],
['pos','operacion','POS','COMERCIO','Punto de venta conectado con inventario y operaciones.','/operations/pos','Workspace disponible','▦'],
['inventory','operacion','Inventario','OPERACIONES','Productos, existencias y movimientos separados por organización.','/operations/inventory','Workspace disponible','□'],
['crm','operacion','CRM','RELACIONES','Clientes, partners y comunicaciones conectados con ATLAS Connect.','/connect','ATLAS Connect disponible','C'],
['hr','personas','HR & Payroll','PERSONAS','Empleados, evaluaciones y nómina con permisos y auditoría.','/hr','Workspace disponible','H'],
['marketplace','verticales','Marketplace','COMERCIO DIGITAL','Catálogo y comercio conectado con operación y movilidad.','/marketplace','Ruta disponible','M'],
['ride','verticales','Ride / Delivery','MOVILIDAD','Logística, entregas y movilidad mediante ATLAS RideOS.','/rideos','RideOS disponible','R'],
['health','verticales','Health','SALUD','Workspace de salud sujeto a permisos y fuentes autorizadas.','/health','Workspace disponible','+'],
['education','verticales','Education','EDUCACIÓN','Formación y aprendizaje conectados al Knowledge Atlas.','/knowledge/training','Knowledge Atlas disponible','E'],
['ai','operacion','IA','INTELIGENCIA','Conocimiento y asistencia sobre datos autorizados.','/knowledge','Knowledge Atlas disponible','✦'],
['security','operacion','Seguridad & Auditoría','GOBERNANZA','Zero Trust, trazabilidad, resiliencia y controles administrativos.','/security','Workspace disponible','S']
].map(([id,category,title,eyebrow,desc,route,status,icon])=>({id,category,title,eyebrow,desc,route,status,icon}));

const PILLARS=[
['mobility','Movilidad','/rideos','Transporte, delivery, flotas y rutas.','left',7.4],
['finance','Finanzas','/finance','Contabilidad, tesorería, cobros y pagos.','left',14],
['health','Salud','/health','Coordinación, teleatención y salud conectada.','left',20.7],
['housing','Vivienda',null,'Planeación urbana, vivienda y mantenimiento.','left',27.4],
['energy','Energía',null,'Planeación y observabilidad energética.','left',34.1],
['water','Agua',null,'Operación, incidencias y continuidad de servicio.','left',40.8],
['education','Educación','/knowledge/training','Aprendizaje y conocimiento institucional.','right',7.4],
['security','Seguridad','/security','Zero Trust, auditoría y resiliencia.','right',14],
['community','Comunidad','/connect','Personas, empresas e instituciones conectadas.','right',20.7],
['commerce','Comercio','/operations/pos','POS, inventario, marketplace y ventas.','right',27.4],
['rescue','Rescate',null,'Coordinación para incidencias y emergencias.','right',34.1],
['tourism','Turismo','/marketplace','Destinos, movilidad y experiencias.','right',40.8]
].map(([id,label,route,copy,side,top])=>({id,label,route,copy,side,top}));

const CITIES=[
['Caracas','Ávila Smart Metropolis'],['Maracaibo','Lake & Bridge of Progress'],['Valencia','Industry & Innovation'],
['La Guaira','Smart Port & Coast'],['Mérida','Mountains of Opportunity'],['Zulia','Energy & Lake Future'],['Los Roques & Choroní','Natural Paradise']
];

const CSS=`
:root{color-scheme:dark;--bg:#020712;--panel:#071828;--text:#f8fbff;--muted:#92a9bd;--cyan:#72dfff;--line:rgba(100,204,255,.24)}
*{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--bg)}body{margin:0;background:linear-gradient(#020712,#061426,#020712);color:var(--text);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:inherit}.wrap{width:min(1220px,calc(100% - 32px));margin:auto}
.top{position:fixed;inset:0 0 auto;z-index:50;background:linear-gradient(rgba(0,6,14,.78),rgba(0,6,14,.16));backdrop-filter:blur(14px);border-bottom:1px solid rgba(120,215,255,.12)}.topin{height:68px;display:flex;justify-content:flex-end;align-items:center}.nav{display:flex;gap:20px;align-items:center}.nav a{text-decoration:none;font-size:12px;color:#dcebf6;text-shadow:0 2px 12px #000}.nav .enter{padding:9px 14px;border-radius:999px;border:1px solid rgba(114,218,255,.42);background:rgba(4,35,61,.72)}.menu{display:none;background:#09233a;color:white;border:1px solid #2c648b;border-radius:9px;padding:8px 10px;margin-left:auto}
.hero{min-height:100vh;padding-top:68px;display:grid;place-items:center;position:relative;overflow:hidden;isolation:isolate}.hero:before{content:"";position:absolute;inset:-30px;z-index:-3;background:url('/assets/atlas-future-venezuela.webp') center/cover no-repeat;filter:blur(28px);opacity:.43;transform:scale(1.08)}.hero:after{content:"";position:absolute;inset:0;z-index:-2;background:linear-gradient(rgba(0,6,14,.34),rgba(0,6,14,.04) 35%,rgba(0,6,14,.06) 68%,rgba(0,6,14,.8))}
.poster{position:relative;width:min(900px,100%);aspect-ratio:1122/1402;background:url('/assets/atlas-future-venezuela.webp') center/100% 100% no-repeat;filter:drop-shadow(0 26px 80px rgba(0,0,0,.5))}.hot{position:absolute;width:17.5%;height:5.7%;border:1px solid transparent;border-radius:10px;background:transparent;cursor:pointer}.hot.left{left:1.6%}.hot.right{right:1.6%}.hot:hover,.hot:focus-visible{outline:none;border-color:#8be7ff;background:rgba(35,166,232,.14);box-shadow:0 0 26px rgba(50,190,255,.24)}.state{position:absolute;left:50%;bottom:2.2%;transform:translateX(-50%);padding:7px 11px;border-radius:999px;border:1px solid rgba(120,215,255,.28);background:rgba(1,14,27,.58);backdrop-filter:blur(10px);font-size:9px;white-space:nowrap}
.section{padding:72px 0}.head{display:flex;justify-content:space-between;align-items:end;gap:24px;margin-bottom:24px}.kicker{font-size:10px;letter-spacing:.18em;color:#78dcff;text-transform:uppercase;font-weight:750}.head h2{font-size:clamp(31px,4vw,52px);line-height:1.02;margin:8px 0 0;letter-spacing:-.04em}.head p{max-width:520px;margin:0;color:var(--muted);font-size:12px;line-height:1.65}
.info{display:grid;grid-template-columns:1.1fr .9fr;gap:14px;margin-bottom:22px}.panel{border:1px solid var(--line);border-radius:20px;padding:22px;background:linear-gradient(150deg,#0a2238,#051523)}.panel h3{margin:6px 0 8px;font-size:22px}.panel p{margin:0;color:var(--muted);font-size:11px;line-height:1.6}.nodata{margin-top:14px;padding:11px 12px;border:1px solid rgba(105,199,247,.15);border-radius:12px;background:#04111e;font-size:10px;color:#c9d9e6}
.controls{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:16px}.search{flex:1;min-width:210px;padding:11px 13px;border-radius:11px;border:1px solid #28506d;background:#061929;color:white}.pill{padding:9px 12px;border-radius:999px;border:1px solid #28506d;background:#071a2c;color:#a8bfd1;font-size:10px}.pill.on{background:#168bdc;color:#fff}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.card{min-height:202px;padding:17px;border:1px solid var(--line);border-radius:17px;background:linear-gradient(155deg,#0b2239,#051523);display:flex;flex-direction:column}.icon{width:40px;height:40px;display:grid;place-items:center;border-radius:11px;border:1px solid rgba(105,211,255,.3);color:#9ce9ff}.card small{margin-top:13px;color:#7399b5;font-size:8px;letter-spacing:.12em}.card h3{margin:7px 0;font-size:17px}.card p{margin:0 0 14px;color:#98aec1;font-size:10px;line-height:1.55}.foot{margin-top:auto;display:flex;justify-content:space-between;gap:8px;align-items:center}.status{font-size:8px;color:#76c5a5}.open{border:0;background:none;color:#7dddff;font-size:10px;font-weight:750;cursor:pointer}.empty{display:none;text-align:center;padding:25px;border:1px dashed #385872;border-radius:14px;color:#88a4b9}
.cities{display:grid;grid-template-columns:repeat(7,1fr);gap:9px}.city{min-height:115px;padding:14px;border:1px solid var(--line);border-radius:15px;background:#071a2c}.city b{display:block;font-size:12px}.city span{display:block;margin-top:8px;color:#6fd5ff;font-size:8px;line-height:1.4}.band{margin-top:16px;padding:23px;border:1px solid var(--line);border-radius:20px;background:radial-gradient(circle at 50% 0,rgba(27,143,220,.18),transparent 35%),#061827}.band h3{margin:0;font-size:25px}.band p{max-width:900px;color:var(--muted);font-size:11px;line-height:1.65}.meta{display:flex;gap:8px;flex-wrap:wrap}.meta span{padding:7px 9px;border-radius:999px;border:1px solid #284861;background:#071a2b;font-size:8px;color:#a9bfd0}
.footer{padding:26px 0 36px;border-top:1px solid rgba(255,255,255,.07);font-size:9px;color:#708ba2}.footerin{display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap}
dialog{width:min(540px,calc(100% - 26px));border:1px solid #306181;border-radius:19px;background:#071827;color:#fff;padding:0}dialog::backdrop{background:rgba(0,6,13,.8);backdrop-filter:blur(5px)}.din{padding:23px}.dtop{display:flex;justify-content:space-between}.dtop h3{margin:7px 0;font-size:24px}.close{width:34px;height:34px;border:0;border-radius:9px;background:#102a42;color:white}.dstatus{display:inline-block;margin:9px 0 12px;padding:6px 9px;border-radius:999px;background:#0c2d29;color:#7bd2b2;font-size:9px}.din p{color:#9eb4c7;line-height:1.6;font-size:11px}.action{display:inline-flex;margin-top:4px;text-decoration:none;padding:10px 13px;border-radius:10px;background:#158cdc;font-size:10px;font-weight:750}
@media(max-width:1000px){.grid{grid-template-columns:repeat(2,1fr)}.cities{grid-template-columns:repeat(4,1fr)}.info{grid-template-columns:1fr}}@media(max-width:720px){.topin{height:60px}.menu{display:block}.nav{display:none;position:absolute;top:56px;left:12px;right:12px;padding:13px;background:#061827;border:1px solid #28506d;border-radius:14px;flex-direction:column;align-items:stretch}.nav.open{display:flex}.hero{padding-top:60px;min-height:auto}.section{padding:54px 0}.head{display:block}.head p{margin-top:12px}.grid{grid-template-columns:1fr}.cities{grid-template-columns:1fr 1fr}.state{display:none}}@media(max-width:460px){.wrap{width:min(100% - 22px,1220px)}.cities{grid-template-columns:1fr}}
`;

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const gate=p=>`/identity?app=${encodeURIComponent(p)}`;
const hotspots=()=>PILLARS.map(p=>`<button class="hot ${p.side}" style="top:${p.top}%" data-p="${esc(p.id)}" aria-label="${esc(p.label)}"></button>`).join('');
const cards=()=>MODULES.map(m=>`<article class="card" data-cat="${m.category}" data-q="${esc((m.title+' '+m.eyebrow+' '+m.desc).toLowerCase())}"><div class="icon">${esc(m.icon)}</div><small>${esc(m.eyebrow)}</small><h3>${esc(m.title)}</h3><p>${esc(m.desc)}</p><div class="foot"><span class="status">${esc(m.status)}</span><button class="open" data-m="${esc(m.id)}">Ver módulo →</button></div></article>`).join('');
const cities=()=>CITIES.map(c=>`<article class="city"><b>${esc(c[0])}</b><span>${esc(c[1])}</span></article>`).join('');

function page(){
const js=`
const M=${JSON.stringify(MODULES)},P=${JSON.stringify(PILLARS)},nav=document.querySelector('#nav'),menu=document.querySelector('#menu'),dlg=document.querySelector('#dlg'),dt=document.querySelector('#dt'),db=document.querySelector('#db'),ds=document.querySelector('#ds'),da=document.querySelector('#da');
menu?.addEventListener('click',()=>nav?.classList.toggle('open'));nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
function show(x){if(!x)return;dt.textContent=x.title||x.label;db.textContent=x.desc||x.copy;ds.textContent=x.status||(x.route?'Disponible mediante ATLAS Identity':'Integración local pendiente');if(x.route){da.hidden=false;da.href='/identity?app='+encodeURIComponent(x.route)}else{da.hidden=true;da.removeAttribute('href')}dlg?.showModal()}
document.querySelectorAll('[data-p]').forEach(b=>b.addEventListener('click',()=>show(P.find(x=>x.id===b.dataset.p))));document.querySelectorAll('[data-m]').forEach(b=>b.addEventListener('click',()=>show(M.find(x=>x.id===b.dataset.m))));document.querySelector('#dc')?.addEventListener('click',()=>dlg?.close());dlg?.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
const search=document.querySelector('#search'),all=[...document.querySelectorAll('.card')],pills=[...document.querySelectorAll('.pill')],empty=document.querySelector('#empty');let f='todos';function apply(){const q=(search?.value||'').trim().toLowerCase();let n=0;all.forEach(c=>{const s=(f==='todos'||c.dataset.cat===f)&&(!q||c.dataset.q.includes(q));c.hidden=!s;if(s)n++});empty.style.display=n?'none':'block'}search?.addEventListener('input',apply);pills.forEach(p=>p.addEventListener('click',()=>{f=p.dataset.f;pills.forEach(x=>x.classList.toggle('on',x===p));apply()}));document.querySelector('#year').textContent=new Date().getFullYear();`;
return `<!doctype html><html lang="es-VE"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#020712"><meta name="description" content="ATLAS Venezuela · Sistema Operativo Empresarial"><title>ATLAS Venezuela · Sistema Operativo Empresarial</title><style>${CSS}</style></head><body>
<header class="top"><div class="wrap topin"><button class="menu" id="menu">☰</button><nav class="nav" id="nav"><a href="#modulos">Módulos</a><a href="#territorio">Territorio</a><a href="/global">ATLAS Global</a><a class="enter" href="${gate('/dashboard')}">Entrar a ATLAS</a></nav></div></header>
<main><section class="hero"><h1 style="position:absolute;left:-9999px">ATLAS Future Venezuela</h1><div class="poster" role="img" aria-label="ATLAS Future Venezuela">${hotspots()}<div class="state">ATLAS Venezuela · Sistema Operativo Empresarial</div></div></section>
<section class="section" id="modulos"><div class="wrap"><div class="head"><div><div class="kicker">ATLAS Venezuela</div><h2>Una nación conectada. Una plataforma operativa.</h2></div><p>La referencia visual es ahora el fondo principal y el logo central del poster es la marca dominante. Sus pilares funcionan como puntos interactivos conectados a ATLAS.</p></div>
<div class="info"><div class="panel"><div class="kicker">Arquitectura</div><h3>Sistema Operativo Empresarial</h3><p>Identidad, permisos, auditoría, operaciones, finanzas, personas y verticales comparten un mismo núcleo.</p><div class="nodata"><b>Sin datos conectados</b> · las métricas aparecen solo con fuentes autorizadas.</div></div><div class="panel"><div class="kicker">Capa VE</div><h3>es-VE · VES · Multiempresa</h3><p>Fiscalidad, banca, pagos y cumplimiento requieren reglas versionadas e integraciones autorizadas.</p></div></div>
<div class="controls"><input class="search" id="search" type="search" placeholder="Buscar módulos..."><button class="pill on" data-f="todos">Todos</button><button class="pill" data-f="operacion">Operación</button><button class="pill" data-f="finanzas">Finanzas</button><button class="pill" data-f="personas">Personas</button><button class="pill" data-f="verticales">Verticales</button></div><div class="grid">${cards()}</div><div class="empty" id="empty">No hay módulos que coincidan con la búsqueda.</div></div></section>
<section class="section" id="territorio"><div class="wrap"><div class="head"><div><div class="kicker">Red territorial</div><h2>Venezuela como una red de capacidades.</h2></div><p>Caracas, Maracaibo, Valencia, La Guaira, Mérida, Zulia, Los Roques y Choroní se conservan como ejes de la visión.</p></div><div class="cities">${cities()}</div><div class="band"><h3>ATLAS Venezuela</h3><p>Movilidad, Finanzas, Salud, Vivienda, Energía, Agua, Educación, Seguridad, Comunidad, Comercio, Rescate y Turismo comparten identidad, datos y auditoría. Los pilares existentes abren ATLAS mediante Identity; los demás muestran su dependencia real.</p><div class="meta"><span>VE</span><span>es-VE</span><span>VES</span><span>RBAC</span><span>Auditoría</span><span>Multiempresa</span></div></div></div></section></main>
<footer class="footer"><div class="wrap footerin"><span>© <span id="year"></span> ATLAS Enterprise Suite · Venezuela</span><span>Country layer VE · Cumplimiento local sujeto a validación</span></div></footer>
<dialog id="dlg"><div class="din"><div class="dtop"><div><div class="kicker">ATLAS Venezuela</div><h3 id="dt">Módulo</h3></div><button class="close" id="dc">×</button></div><span class="dstatus" id="ds"></span><p id="db"></p><a class="action" id="da" href="${gate('/dashboard')}">Abrir en ATLAS</a></div></dialog><script>${js}</script></body></html>`;
}

export function handleVenezuela(request){const u=new URL(request.url),p=u.pathname.replace(/\/+$/,'')||'/';if(!VE_PATHS.has(p))return null;return new Response(page(),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300','x-atlas-country':'VE'}})}
export {MODULES as VENEZUELA_MODULES};