import { ATLAS_VERSION } from './version.js';
import { ensureWebSchema } from './web-schema.js';

const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=(body,status=200,headers={})=>Response.json(body,{status,headers:{'cache-control':'no-store','content-security-policy':"default-src 'none'; frame-ancestors 'none'",...headers}});
const html=(body,status=200)=>new Response(body,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; img-src 'self' data:; style-src 'unsafe-inline'; script-src 'unsafe-inline' 'self'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"}});

const modules=[
 ['Enterprise Suite','/platform/enterprise-suite','Live','Finance, people, operations and administration.'],
 ['CRM','/platform/crm','Live','Leads, contacts, opportunities, quotes and activities.'],
 ['HR Knowledge','/platform/hr-payroll','Beta','People, skills, assessments and organizational knowledge.'],
 ['Voice & Vision','/platform/voice-vision','Foundation','Consent-first camera, microphone and multilingual sensory layer.'],
 ['ATLAS Bridge','/platform/bridge','Foundation','Secure continuity and handoff across devices.'],
 ['Portfolio Lab','/platform/invest','Beta','Investment intelligence and portfolio exploration.']
];

const css=`:root{color-scheme:dark;--bg:#050b14;--panel:#0b1b2e;--line:#1f3854;--text:#eef7ff;--muted:#9bb1c8;--accent:#a8d4ff;--ok:#73e2a0;--warn:#ffd27a;--bad:#ff9aa6}*{box-sizing:border-box}body{margin:0;background:linear-gradient(#0a1727,#050b14);color:var(--text);font-family:Inter,system-ui,sans-serif;min-height:100vh}a{color:inherit;text-decoration:none}.nav{position:sticky;top:0;background:#050b14e8;border-bottom:1px solid var(--line);z-index:10}.navin,.wrap,.foot{max-width:1180px;margin:auto;padding:18px 22px}.navin{display:flex;justify-content:space-between;gap:16px;align-items:center}.brand{font-weight:900;letter-spacing:.18em}.links{display:flex;gap:10px;flex-wrap:wrap}.links a,.btn{padding:10px 14px;border-radius:12px;border:1px solid var(--line);background:#ffffff08}.primary{background:linear-gradient(#e3f2ff,#9fcfff)!important;color:#06101c!important;font-weight:800}.wrap{padding-top:64px;padding-bottom:64px}.hero{display:grid;grid-template-columns:1.2fr .8fr;gap:28px;align-items:center}.eyebrow{color:var(--accent);font-size:.76rem;letter-spacing:.16em;text-transform:uppercase;font-weight:800}.hero h1,.page h1{font-size:clamp(2.7rem,7vw,5.6rem);line-height:.95;letter-spacing:-.05em;margin:14px 0 20px}.muted,p{color:var(--muted);line-height:1.65}.glass{border:1px solid var(--line);border-radius:22px;background:#0b1b2ecc;padding:22px}.grid,.kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.kpis{grid-template-columns:repeat(4,minmax(0,1fr))}.status{display:inline-flex;gap:7px;align-items:center;font-size:.78rem}.dot{width:8px;height:8px;border-radius:50%;background:var(--ok)}.dot.warn{background:var(--warn)}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.btn{display:inline-flex;cursor:pointer;color:var(--text)}.page{max-width:960px;margin:auto;padding:58px 22px}.form{display:grid;gap:14px;margin-top:22px}.field{display:grid;gap:7px}.field input,.field textarea,.field select{padding:12px 13px;border-radius:12px;border:1px solid var(--line);background:#ffffff08;color:var(--text);font:inherit}.field textarea{min-height:130px}.notice{padding:12px 14px;border-radius:12px;border:1px solid var(--line);margin-top:12px}.notice.ok{color:#bdf3d1}.notice.bad{color:#ffc1c8}.table{width:100%;border-collapse:collapse;margin-top:16px}.table th,.table td{text-align:left;padding:11px;border-bottom:1px solid var(--line)}footer{border-top:1px solid var(--line)}.foot{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;color:var(--muted);font-size:.82rem}.footnav{display:flex;gap:12px;flex-wrap:wrap}.skip{position:absolute;left:-9999px}.skip:focus{left:12px;top:12px;background:white;color:black;padding:8px;z-index:99}@media(max-width:800px){.hero,.grid,.kpis{grid-template-columns:1fr}.links a:not(.primary){display:none}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}`;

function nav(){return `<a class="skip" href="#main">Skip to content</a><header class="nav"><div class="navin"><a class="brand" href="/">ATLAS</a><nav class="links"><a href="/platform/enterprise-suite">Platform</a><a href="/trust/status">Status</a><a href="/contact">Contact</a><a href="/login">Sign in</a><a class="primary" href="/dashboard">Dashboard</a></nav></div></header>`}
function footer(){return `<footer><div class="foot"><span>© 2026 ATLAS Enterprise Suite · v${ATLAS_VERSION}</span><nav class="footnav"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/security">Security</a><a href="/trust/status">Status</a></nav></div></footer>`}
function doc({title,description,body,script='',robots='index,follow'}){const t=esc(title),d=esc(description||'ATLAS Enterprise Suite');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#07111f"><meta name="description" content="${d}"><meta name="robots" content="${robots}"><meta property="og:title" content="${t} · ATLAS"><meta property="og:description" content="${d}"><meta property="og:type" content="website"><meta property="og:image" content="/icon.svg"><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/icon.svg" type="image/svg+xml"><title>${t} · ATLAS</title><style>${css}</style></head><body>${nav()}<main id="main">${body}</main>${footer()}${script?`<script>${script}</script>`:''}</body></html>`}
}

function home(){const cards=modules.map(([name,path,state,copy])=>`<article class="glass"><span class="status"><span class="dot ${state==='Live'?'':'warn'}"></span>${state}</span><h3>${esc(name)}</h3><p>${esc(copy)}</p><a class="btn" href="${path}">Open</a></article>`).join('');return doc({title:'Enterprise Suite',description:'ATLAS unifies identity, CRM, HR, finance, operations and secure connected services.',body:`<div class="wrap"><section class="hero"><div><div class="eyebrow">Enterprise intelligence · Human-centered technology</div><h1>One platform.<br>Built to connect.</h1><p>ATLAS brings identity, people, finance, operations, CRM and intelligence into one coherent environment.</p><div class="actions"><a class="btn primary" href="/login">Enter ATLAS</a><a class="btn" href="/contact">Request a demo</a></div></div><aside class="glass"><div class="eyebrow">Release ${ATLAS_VERSION}</div><p>Identity & RBAC: Live</p><p>CRM: Live</p><p>ATLAS QA: Native</p><p>Backup integrity: SHA-256</p></aside></section><section><h2>Connected modules</h2><div class="grid">${cards}</div></section></div>`})}
function loginPage(){return doc({title:'Sign in',robots:'noindex,nofollow',body:`<section class="page"><div class="eyebrow">ATLAS ID</div><h1>Welcome back.</h1><form id="login" class="glass form"><div class="field"><label>Email</label><input name="email" type="email" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" minlength="12" required></div><button class="btn primary" type="submit">Sign in</button><div id="msg" aria-live="polite"></div></form></section>`,script:`const f=document.getElementById('login'),m=document.getElementById('msg');f.onsubmit=async e=>{e.preventDefault();m.textContent='Signing in…';try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:f.email.value,password:f.password.value})});const d=await r.json();if(!r.ok)throw new Error();sessionStorage.setItem('atlas.session',d.sessionToken);sessionStorage.setItem('atlas.user',JSON.stringify(d.user));location.assign('/dashboard')}catch{m.className='notice bad';m.textContent='Unable to sign in.'}};`})}
function dashboardPage(){const cards=modules.map(([n,p,s])=>`<article class="glass"><span class="status"><span class="dot ${s==='Live'?'':'warn'}"></span>${s}</span><h3>${esc(n)}</h3><a class="btn" href="${p}">Open module</a></article>`).join('');return doc({title:'Dashboard',robots:'noindex,nofollow',body:`<section class="page"><div class="eyebrow">Workspace</div><h1>ATLAS Dashboard</h1><p id="welcome">Verifying your session…</p><button id="logout" class="btn">Sign out</button><div class="grid" style="margin-top:24px">${cards}</div></section>`,script:`const t=sessionStorage.getItem('atlas.session'),w=document.getElementById('welcome');if(!t)location.replace('/login');else fetch('/api/auth/me',{headers:{authorization:'Bearer '+t}}).then(async r=>{const d=await r.json();if(!r.ok)throw 0;w.textContent='Signed in as '+d.user.displayName+' · '+d.user.email}).catch(()=>{sessionStorage.clear();location.replace('/login')});document.getElementById('logout').onclick=async()=>{if(t)await fetch('/api/auth/logout',{method:'POST',headers:{authorization:'Bearer '+t}}).catch(()=>{});sessionStorage.clear();location.replace('/login')};`})}
function statusPage(){return doc({title:'System Status',body:`<section class="page"><div class="eyebrow">Trust center</div><h1>System status.</h1><div id="health" class="glass"><span class="status"><span class="dot warn"></span>Checking</span></div></section>`,script:`const e=document.getElementById('health');fetch('/api/health',{cache:'no-store'}).then(async r=>{const d=await r.json();const state=r.ok&&d.ok?'Operational':'Degraded';const cls=r.ok&&d.ok?'':'warn';e.innerHTML='<span class="status"><span class="dot '+cls+'"></span>'+state+'</span><table class="table"><tr><th>Version</th><td>'+d.version+'</td></tr><tr><th>Identity DB</th><td>'+d.identityDatabase+'</td></tr><tr><th>QA</th><td>'+d.qa+'</td></tr></table>'}).catch(()=>{e.innerHTML='<div class="notice bad">Health endpoint unavailable.</div>'});`})}
function contactPage(){return doc({title:'Contact',body:`<section class="page"><div class="eyebrow">Business & partnerships</div><h1>Talk to ATLAS.</h1><form id="contact" class="glass form"><div class="field"><label>Name</label><input name="name" maxlength="120" required></div><div class="field"><label>Company</label><input name="company" maxlength="160"></div><div class="field"><label>Email</label><input name="email" type="email" maxlength="254" required></div><div class="field"><label>Interest</label><select name="interest"><option>Enterprise Suite</option><option>CRM / HR</option><option>Partnership</option><option>Deployment</option><option>Other</option></select></div><div class="field"><label>Message</label><textarea name="message" maxlength="4000" required></textarea></div><input name="website" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px"><button class="btn primary" type="submit">Send request</button><div id="msg" aria-live="polite"></div></form></section>`,script:`const f=document.getElementById('contact'),m=document.getElementById('msg');f.onsubmit=async e=>{e.preventDefault();m.textContent='Sending…';try{const r=await fetch('/api/web/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(f))) });const d=await r.json();if(!r.ok)throw new Error(d.error||'failed');m.className='notice ok';m.textContent='Request received. Reference: '+d.reference;f.reset()}catch(err){m.className='notice bad';m.textContent=err.message==='rate_limited'?'Too many requests. Please try later.':'Unable to submit right now.'}};`})}

const legal={
 '/privacy':['Privacy','ATLAS minimizes data collection, scopes access by identity and organization, and treats sensitive data as permission-bound.'],
 '/terms':['Terms','ATLAS is an evolving software platform. Beta and Foundation capabilities are not represented as production-complete.'],
 '/security':['Security','ATLAS uses centralized identity, scoped sessions, role-based authorization, tenant boundaries, audit evidence and native QA gates.']
};
const internal={
 '/platform/enterprise-suite':['Enterprise Suite','A connected workspace for finance, people, operations, intelligence and administration.'],
 '/platform/hr-payroll':['HR & Payroll','People operations, recruiting, assessments, skills and organizational knowledge.'],
 '/platform/finance':['Finance','Accounting, AP, AR, GL, reporting, controls and financial visibility.'],
 '/platform/operations':['Operations','Operational workflows, approvals, inventory and service coordination.'],
 '/platform/voice-vision':['Voice & Vision','Consent-based sensory foundations for camera, microphone, speech and multilingual intelligence.'],
 '/platform/bridge':['ATLAS Bridge','Secure continuity and connected experiences across authorized devices.'],
 '/ecosystem/health':['ATLAS Health','Health operations concepts remain separately gated before clinical use.'],
 '/ecosystem/ride':['ATLAS Ride','Mobility operations, trip intelligence, maintenance and platform finance.'],
 '/ecosystem/connect':['ATLAS Connect','Communication and service continuity across ATLAS modules.'],
 '/ecosystem/public-safety':['Public Safety','Situational awareness concepts with explicit privacy and safety boundaries.'],
 '/trust/audit':['Audit Evidence','Durable operational evidence and accountable activity trails.']
};
function simplePage(title,copy){return doc({title,description:copy,body:`<section class="page"><div class="eyebrow">ATLAS</div><h1>${esc(title)}</h1><p>${esc(copy)}</p><div class="actions"><a class="btn" href="/">← Home</a><a class="btn" href="/dashboard">Dashboard</a></div></section>`})}
function notFound(path){return doc({title:'404 · Not found',robots:'noindex,nofollow',body:`<section class="page"><div class="eyebrow">404</div><h1>Route not found.</h1><p>ATLAS could not find <strong>${esc(path)}</strong>.</p><a class="btn primary" href="/">Go home</a></section>`})}
function errorPage(){return doc({title:'500 · Service error',robots:'noindex,nofollow',body:`<section class="page"><div class="eyebrow">500</div><h1>ATLAS hit a service error.</h1><p>The request could not be completed safely.</p><a class="btn primary" href="/trust/status">Check status</a></section>`})}

async function sha256(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function rateLimit(request,env,scope,limit,windowSeconds){const ready=await ensureWebSchema(env);if(!ready.ok)return {ok:false,status:503,error:'database_unavailable'};const subject=request.headers.get('cf-connecting-ip')||request.headers.get('x-forwarded-for')||'unknown';const subjectHash=await sha256(subject);const bucket=Math.floor(Date.now()/1000/windowSeconds);await env.DB.prepare(`INSERT INTO web_rate_limits(scope,subject_hash,bucket,request_count) VALUES(?,?,?,1) ON CONFLICT(scope,subject_hash,bucket) DO UPDATE SET request_count=request_count+1,updated_at=CURRENT_TIMESTAMP`).bind(scope,subjectHash,bucket).run();const row=await env.DB.prepare('SELECT request_count FROM web_rate_limits WHERE scope=? AND subject_hash=? AND bucket=?').bind(scope,subjectHash,bucket).first();env.DB.prepare('DELETE FROM web_rate_limits WHERE bucket<?').bind(bucket-20).run().catch(()=>{});return Number(row?.request_count||0)>limit?{ok:false,status:429,error:'rate_limited'}:{ok:true}}
function validJsonRequest(request){const type=(request.headers.get('content-type')||'').toLowerCase();const len=Number(request.headers.get('content-length')||0);return type.includes('application/json')&&(len===0||len<=20000)}
async function contactApi(request,env){if(!validJsonRequest(request))return json({ok:false,error:'invalid_request'},415);const limited=await rateLimit(request,env,'contact',5,600);if(!limited.ok)return json({ok:false,error:limited.error},limited.status,limited.status===429?{'retry-after':'600'}:{});const body=await request.json().catch(()=>null);if(body?.website)return json({ok:true,reference:crypto.randomUUID()},201);const name=String(body?.name||'').trim().slice(0,120),company=String(body?.company||'').trim().slice(0,160),email=String(body?.email||'').trim().toLowerCase().slice(0,254),interest=String(body?.interest||'Other').trim().slice(0,80),message=String(body?.message||'').trim().slice(0,4000);if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||message.length<3)return json({ok:false,error:'valid_contact_fields_required'},400);const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO public_contact_requests(id,name,company,email,interest,message,status) VALUES(?,?,?,?,?,?,?)').bind(id,name,company||null,email,interest,message,'new').run();return json({ok:true,reference:id},201)}
async function telemetryApi(request,env){if(!validJsonRequest(request))return json({ok:false,error:'invalid_request'},415);const limited=await rateLimit(request,env,'telemetry',60,60);if(!limited.ok)return json({ok:false,error:limited.error},limited.status);const body=await request.json().catch(()=>null),type=String(body?.type||'').slice(0,40),path=String(body?.path||'').slice(0,240);if(!['client_error','route_404'].includes(type))return json({ok:false,error:'invalid_event'},400);await env.DB.prepare('INSERT INTO web_telemetry_events(id,event_type,path) VALUES(?,?,?)').bind(crypto.randomUUID(),type,path).run();return json({ok:true,stored:true})}

export async function webShellRoutes(request,env,url=new URL(request.url)){
 if(url.pathname==='/api/web/contact'&&request.method==='POST')return contactApi(request,env);
 if(url.pathname==='/api/web/telemetry'&&request.method==='POST')return telemetryApi(request,env);
 if(url.pathname==='/manifest.webmanifest')return new Response(JSON.stringify({name:'ATLAS Enterprise Suite',short_name:'ATLAS',start_url:'/',display:'standalone',background_color:'#050b14',theme_color:'#07111f',icons:[{src:'/icon.svg',sizes:'any',type:'image/svg+xml',purpose:'any maskable'}]}),{headers:{'content-type':'application/manifest+json','cache-control':'public,max-age=3600'}});
 if(url.pathname==='/icon.svg')return new Response(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="#07111f"/><path d="M128 382 238 114h38l108 268h-67l-22-61h-81l-22 61zm105-116h43l-21-67z" fill="#b8dcff"/></svg>`,{headers:{'content-type':'image/svg+xml','cache-control':'public,max-age=86400'}});
 if(url.pathname==='/sw.js')return new Response(`const C='atlas-${ATLAS_VERSION}';const A=['/','/login','/dashboard','/trust/status','/icon.svg','/manifest.webmanifest'];self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>c.addAll(A))));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==C).map(x=>caches.delete(x))))));self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||new URL(e.request.url).pathname.startsWith('/api/'))return;e.respondWith(fetch(e.request).then(r=>{const x=r.clone();caches.open(C).then(c=>c.put(e.request,x));return r}).catch(()=>caches.match(e.request).then(r=>r||caches.match('/'))))});`,{headers:{'content-type':'text/javascript; charset=utf-8','cache-control':'no-cache','service-worker-allowed':'/'}});
 if(url.pathname==='/robots.txt')return new Response('User-agent: *\nAllow: /\nDisallow: /dashboard\nDisallow: /login\nSitemap: /sitemap.xml\n',{headers:{'content-type':'text/plain; charset=utf-8'}});
 if(url.pathname==='/sitemap.xml'){const paths=['/','/platform/enterprise-suite','/platform/hr-payroll','/platform/finance','/platform/operations','/platform/voice-vision','/platform/bridge','/trust/status','/security','/privacy','/terms','/contact'];return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${url.origin}${p}</loc></url>`).join('')}</urlset>`,{headers:{'content-type':'application/xml; charset=utf-8'}})}
 if(request.method!=='GET')return null;
 if(url.pathname==='/')return html(home());
 if(url.pathname==='/login')return html(loginPage());
 if(url.pathname==='/dashboard')return html(dashboardPage());
 if(url.pathname==='/trust/status')return html(statusPage());
 if(url.pathname==='/contact')return html(contactPage());
 if(legal[url.pathname])return html(simplePage(...legal[url.pathname]));
 if(internal[url.pathname])return html(simplePage(...internal[url.pathname]));
 return null;
}

export { errorPage, notFound };
