export function webRuntimeScript(){return `(()=>{
if('serviceWorker'in navigator){addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}
const send=(type,path)=>{try{navigator.sendBeacon?.('/api/web/telemetry',new Blob([JSON.stringify({type,path})],{type:'application/json'}))||fetch('/api/web/telemetry',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type,path}),keepalive:true}).catch(()=>{})}catch{}};
addEventListener('error',()=>send('client_error',location.pathname));
addEventListener('unhandledrejection',()=>send('client_error',location.pathname));
const setNetwork=()=>{document.documentElement.dataset.network=navigator.onLine?'online':'offline';const items=document.querySelectorAll('.statusbar .sys');if(items[2]){const b=items[2].querySelector('b');if(b)b.textContent='NETWORK';const spans=items[2].querySelectorAll('span');if(spans[1]){spans[1].lastChild.textContent=navigator.onLine?'ONLINE':'OFFLINE'}}};
setNetwork();addEventListener('online',setNetwork);addEventListener('offline',setNetwork);
const validLanguage=v=>/^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8}){0,4}$/.test(v||'');
const validCountry=v=>/^[A-Za-z]{2}$/.test(v||'');
const qs=new URLSearchParams(location.search);const queryLanguage=qs.get('hl')||qs.get('lang');const queryCountry=qs.get('gl')||qs.get('country');
try{if(validLanguage(queryLanguage))localStorage.setItem('atlas.hl',queryLanguage);if(validCountry(queryCountry))localStorage.setItem('atlas.gl',queryCountry.toUpperCase())}catch{}
let hl=queryLanguage,gl=queryCountry;try{if(!validLanguage(hl))hl=localStorage.getItem('atlas.hl');if(!validCountry(gl))gl=localStorage.getItem('atlas.gl')}catch{}
const contextParams=new URLSearchParams;if(validLanguage(hl))contextParams.set('hl',hl);if(validCountry(gl))contextParams.set('gl',gl.toUpperCase());
fetch('/api/context'+(contextParams.size?'?'+contextParams.toString():''),{headers:{accept:'application/json'}}).then(r=>r.ok?r.json():null).then(ctx=>{if(!ctx?.ok)return;window.ATLAS_CONTEXT=Object.freeze(ctx);if(ctx.locale)document.documentElement.lang=ctx.locale;if(ctx.direction)document.documentElement.dir=ctx.direction;if(ctx.country)document.documentElement.dataset.country=ctx.country;if(ctx.timezone)document.documentElement.dataset.timezone=ctx.timezone;document.documentElement.dataset.atlasScope='global';dispatchEvent(new CustomEvent('atlas:context',{detail:ctx}))}).catch(()=>{});
const setText=(el,value)=>{if(el&&value!=null)el.textContent=String(value)};
const hydrateProfile=()=>{if(location.pathname!='/dashboard')return;const profile=document.querySelector('.profile');if(!profile)return;const avatar=profile.querySelector('.avatar'),name=profile.querySelector('strong'),meta=profile.querySelector('small');let token='';try{token=sessionStorage.getItem('atlas.session')||''}catch{}if(!token){setText(avatar,'A');setText(name,'ATLAS');setText(meta,'Preview workspace');return}fetch('/api/auth/me',{headers:{authorization:'Bearer '+token}}).then(async r=>{const d=await r.json();if(!r.ok||!d?.user)throw new Error('session');const display=d.user.displayName||d.user.email||'ATLAS User';setText(avatar,String(display).trim().charAt(0).toUpperCase()||'A');setText(name,display);setText(meta,'Authenticated workspace')}).catch(()=>{setText(avatar,'A');setText(name,'ATLAS');setText(meta,'Session unavailable')})};
const setStatus=(item,title,value)=>{if(!item)return;const b=item.querySelector('b');if(b)b.textContent=title;const spans=item.querySelectorAll('span');if(spans[1])spans[1].lastChild.textContent=value};
const hydrateHealth=()=>{const bar=document.querySelector('.statusbar');if(!bar)return;const items=bar.querySelectorAll('.sys');setStatus(items[0],'SYSTEM STATUS','CHECKING');setStatus(items[1],'CONNECTION',location.protocol==='https:'?'HTTPS':'LOCAL');setStatus(items[2],'NETWORK',navigator.onLine?'ONLINE':'OFFLINE');setStatus(items[3],'QA','CHECKING');setStatus(items[4],'BACKUP','CHECKING');fetch('/api/health',{cache:'no-store'}).then(async r=>{let d={};try{d=await r.json()}catch{}const ok=Boolean(r.ok&&d.ok);setStatus(items[0],'SYSTEM STATUS',ok?'OPERATIONAL':'DEGRADED');setStatus(items[3],'QA',String(d.qa||'UNKNOWN').toUpperCase());setStatus(items[4],'BACKUP',String(d.backupIntegrity||'UNKNOWN').toUpperCase());const realtime=document.querySelector('.realtime');if(realtime){realtime.textContent=ok?'Operational':'Degraded';realtime.dataset.state=ok?'operational':'degraded'}}).catch(()=>{setStatus(items[0],'SYSTEM STATUS','UNAVAILABLE');setStatus(items[3],'QA','UNKNOWN');setStatus(items[4],'BACKUP','UNKNOWN')})};
const installMobileNav=()=>{const host=document.querySelector('.site-nav-inner');if(!host||host.querySelector('.atlas-mobile-nav'))return;const style=document.createElement('style');style.textContent='.atlas-mobile-nav{display:none}@media(max-width:760px){.atlas-mobile-nav{display:block;position:relative}.atlas-mobile-nav summary{list-style:none;cursor:pointer;border:1px solid rgba(78,178,255,.3);border-radius:10px;padding:9px 12px;color:#f2f8ff;background:rgba(7,25,45,.92)}.atlas-mobile-nav summary::-webkit-details-marker{display:none}.atlas-mobile-panel{position:absolute;right:0;top:calc(100% + 8px);min-width:210px;padding:8px;border:1px solid rgba(78,178,255,.3);border-radius:14px;background:rgba(2,12,25,.98);box-shadow:0 16px 38px rgba(0,0,0,.42)}.atlas-mobile-panel a{display:block;padding:11px 12px;border-radius:9px;color:#d8e8f6}.atlas-mobile-panel a:hover,.atlas-mobile-panel a:focus{background:rgba(36,124,255,.16);color:white}}';document.head.appendChild(style);const details=document.createElement('details');details.className='atlas-mobile-nav';const summary=document.createElement('summary');summary.textContent='Menu';summary.setAttribute('aria-label','Open navigation');const panel=document.createElement('nav');panel.className='atlas-mobile-panel';panel.setAttribute('aria-label','Mobile primary');[['Platform','#platform'],['Solutions','#solutions'],['Vision','#vision'],['Trust','/trust/status'],['Contact','/contact']].forEach(([label,href])=>{const a=document.createElement('a');a.href=href;a.textContent=label;a.addEventListener('click',()=>{details.open=false});panel.appendChild(a)});details.append(summary,panel);host.appendChild(details)};
const rewriteDashboardLinks=()=>{if(location.pathname!='/dashboard')return;const map={'/platform/operations#inventory':'/platform/inventory','/platform/operations#products':'/platform/inventory#products','/platform/operations#categories':'/platform/inventory#categories','/platform/operations#warehouses':'/platform/inventory#warehouses','/platform/operations#stock-movements':'/platform/inventory#stock-movements','/platform/operations#adjustments':'/platform/inventory#adjustments','/platform/operations#cycle-counts':'/platform/inventory#cycle-counts','/platform/operations#logistics':'/platform/transportation','/platform/enterprise-suite#projects':'/platform/projects','/platform/enterprise-suite#documents':'/platform/documents','/platform/enterprise-suite#reports':'/platform/reports','/platform/enterprise-suite#bi':'/platform/reports#bi','/platform/enterprise-suite#custom-reports':'/platform/reports#custom-reports','/platform/enterprise-suite#visualization':'/platform/reports#visualization','/platform/enterprise-suite#kpis':'/platform/reports#kpis','/platform/enterprise-suite#trends':'/platform/reports#trends','/platform/enterprise-suite#comparisons':'/platform/reports#comparisons','/platform/enterprise-suite#performance':'/platform/reports#performance','/dashboard#settings':'/platform/settings'};document.querySelectorAll('a[href]').forEach(a=>{const next=map[a.getAttribute('href')];if(next)a.setAttribute('href',next)});const logistics=document.querySelector('[data-menu-group="logistics"]');if(logistics){logistics.dataset.menuGroup='transportation';const label=logistics.querySelector('.nav-label');if(label)label.textContent='Transportation';const link=logistics.querySelector('.nav-link');if(link)link.href='/platform/transportation'}const menu=document.querySelector('.menu');if(menu&&!menu.querySelector('[data-menu-group="integrations"]')){const settings=menu.querySelector('[data-menu-group="settings"]');const group=document.createElement('div');group.className='nav-group';group.dataset.menuGroup='integrations';group.dataset.search='integrations connections sync webhooks api access logs';group.innerHTML='<div class="nav-row"><a class="nav-link" href="/platform/integrations"><span class="nav-icon">⌘</span><span class="nav-label">Integrations</span></a></div>';menu.insertBefore(group,settings||null)}};
const boot=()=>{rewriteDashboardLinks();hydrateProfile();hydrateHealth();installMobileNav()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();`}
