const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'};
const HTML_HEADERS={'content-type':'text/html; charset=utf-8','cache-control':'no-store'};

export const WORKBENCH_CAPABILITIES=[
  {id:'builder',name:'App Builder',status:'implemented-v1',runtime:'node',description:'Deterministic ATLAS module scaffolding without an external visual-builder dependency.',command:'npm run atlas:workbench -- app scaffold billing --description "Billing workspace"'},
  {id:'files',name:'File Studio',status:'implemented-v1',runtime:'node',description:'Workspace-safe list, read, write and exact replacement operations. Secret-like paths are blocked.',command:'npm run atlas:workbench -- fs list modules --depth 2'},
  {id:'search',name:'Code Search',status:'implemented-v1',runtime:'node',description:'Literal or regex search across the repository with result caps and secret-directory exclusions.',command:'npm run atlas:workbench -- fs grep handleBrowser modules'},
  {id:'tasks',name:'Task Runner',status:'implemented-v1',runtime:'node',description:'Runs package scripts. Deploy/release class tasks require an explicit apply flag.',command:'npm run atlas:workbench -- task run check:browser'},
  {id:'checkpoints',name:'Forge Checkpoints',status:'implemented-v2',runtime:'node',description:'Full-workspace snapshots, inspect, diff and guarded restore with optional prune.',command:'npm run atlas:forge -- snapshot before-refactor'},
  {id:'schemas',name:'Schema Studio',status:'implemented-v1',runtime:'node',description:'Local JSON-schema-style entity definitions for ATLAS prototypes and tools.',command:'npm run atlas:model -- schema list'},
  {id:'entities',name:'Entity Engine',status:'implemented-v1',runtime:'node',description:'Create, query, update and delete local entity records with schema validation and Mongo-like filters.',command:'npm run atlas:model -- entity query Project --query "{\"status\":\"active\"}"'},
  {id:'connectors',name:'Connector Registry',status:'implemented-v1',runtime:'node',description:'Non-secret connector catalog, capabilities and environment readiness checks.',command:'npm run atlas:connectors -- status'},
  {id:'release',name:'Release Manager',status:'existing',runtime:'node',description:'Stage, promote and rollback ATLAS release bundles independently of the hosting provider.',command:'npm run atlas:deploy -- status'},
  {id:'build',name:'Build & Verification',status:'existing',runtime:'node-ci',description:'Syntax, finance, launch, browser and Worker bundle validation.',command:'npm run atlas:verify'},
  {id:'deployment',name:'Provider Deployment',status:'adapter',runtime:'ci',description:'Provider deployment remains adapter-based. A provider credential can fail without blocking local ATLAS development.',command:'npm run deploy:provider'},
  {id:'audit',name:'Change Audit',status:'implemented-by-design',runtime:'node-git',description:'Dry-run-by-default mutations, hashes, checkpoints and Git history provide reconstructable change evidence.',command:'git diff --stat'},
];

const escapeHtml=(value)=>String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slugify=(value)=>String(value||'module').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'module';
const pascal=(slug)=>slug.split('-').filter(Boolean).map((p)=>p[0].toUpperCase()+p.slice(1)).join('');

export function createWorkbenchScaffold(name,description=''){
  const slug=slugify(name);
  const symbol=pascal(slug);
  const title=String(name||slug).trim();
  const desc=description||`${title} module generated by ATLAS Workbench.`;
  return {
    id:slug,
    title,
    description:desc,
    files:[`modules/${slug}-worker.js`,`scripts/validate-${slug}.mjs`,`modules/${slug}.atlas.json`],
    route:`/${slug}`,
    statusRoute:`/api/${slug}/status`,
    handler:`handle${symbol}`,
    routerImport:`import {handle${symbol}} from './modules/${slug}-worker.js';`,
    routerCall:`const ${slug.replace(/-/g,'_')}=handle${symbol}(request,env,ctx); if(${slug.replace(/-/g,'_')}) return ${slug.replace(/-/g,'_')};`,
    packageScript:`\"check:${slug}\": \"node scripts/validate-${slug}.mjs\"`,
    generatedBy:'ATLAS Workbench',
    persistence:'none-web-preview',
  };
}

function page(){
  const cards=WORKBENCH_CAPABILITIES.map((c)=>`<article class="card"><div class="head"><span>${escapeHtml(c.name)}</span><b class="${c.status.startsWith('implemented')||c.status==='existing'?'ok':''}">${escapeHtml(c.status)}</b></div><p>${escapeHtml(c.description)}</p><small>${escapeHtml(c.runtime)}</small><code>${escapeHtml(c.command)}</code></article>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATLAS Workbench</title><meta name="description" content="Sovereign ATLAS developer workbench for files, scaffolding, checkpoints, data models, connectors and releases."><style>
:root{--bg:#030812;--panel:#081523;--panel2:#0d2033;--line:#1c4668;--text:#f4f8fc;--muted:#91a8bc;--cyan:#63dcff;--green:#54dda3;--amber:#ffc96b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 78% 0,#103a5d 0,transparent 32%),var(--bg);color:var(--text);font:14px Inter,system-ui,sans-serif}a{color:inherit}.shell{display:grid;grid-template-columns:230px 1fr;min-height:100vh}.side{position:sticky;top:0;height:100vh;border-right:1px solid var(--line);background:#030a14;padding:20px 14px}.brand{font-size:22px;letter-spacing:.22em;font-weight:800}.sub{color:var(--cyan);font-size:9px;letter-spacing:.14em;margin:6px 0 22px}.nav{display:block;text-decoration:none;color:#a9bdcf;padding:10px 11px;border-radius:9px;margin:3px 0}.nav:hover,.nav.on{background:#0d2944;color:#fff}.main{min-width:0}.top{height:66px;display:flex;align-items:center;gap:10px;padding:0 22px;border-bottom:1px solid var(--line);background:rgba(3,8,18,.86);backdrop-filter:blur(16px);position:sticky;top:0;z-index:4}.top b{margin-right:auto}.badge{border:1px solid #356a8e;border-radius:999px;padding:6px 9px;color:#aadbf7;font-size:10px}.content{max-width:1500px;margin:auto;padding:26px}.hero{border:1px solid var(--line);border-radius:20px;padding:28px;background:linear-gradient(145deg,#0c2945,#07131f)}.eyebrow{color:var(--cyan);font-size:10px;letter-spacing:.16em}.hero h1{font-size:42px;margin:10px 0}.hero p{color:#b1c2d2;line-height:1.6;max-width:880px}.notice{margin-top:14px;border:1px solid #7c622b;background:#31270e;color:#f3d995;padding:12px;border-radius:12px;font-size:11px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:16px}.card{border:1px solid var(--line);border-radius:15px;background:linear-gradient(145deg,var(--panel2),var(--panel));padding:16px;min-width:0}.head{display:flex;gap:8px;align-items:center}.head span{font-weight:700}.head b{margin-left:auto;color:var(--amber);font-size:9px}.head b.ok{color:var(--green)}.card p{color:var(--muted);font-size:11px;line-height:1.55;min-height:50px}.card small{display:block;color:#6dcdf1;text-transform:uppercase;letter-spacing:.12em;font-size:8px}.card code{display:block;margin-top:10px;background:#030a12;border:1px solid #173650;border-radius:9px;padding:9px;color:#c6d9e8;white-space:pre-wrap;font-size:9px}.builder{display:grid;grid-template-columns:.8fr 1.2fr;gap:12px;margin-top:18px}.panel{border:1px solid var(--line);border-radius:16px;background:#071421;padding:18px}.field{width:100%;margin:6px 0 10px;background:#030b14;border:1px solid #28506f;border-radius:9px;padding:10px;color:#fff}.btn{border:1px solid #2d779f;background:#0e4168;color:white;padding:10px 13px;border-radius:9px;cursor:pointer}.btn.primary{background:linear-gradient(135deg,#167bcb,#24a6d1)}pre{white-space:pre-wrap;word-break:break-word;background:#02070d;border:1px solid #17364f;padding:13px;border-radius:11px;min-height:160px;color:#bcd3e6;font-size:10px}.foot{color:#758ba0;font-size:10px;margin-top:20px}@media(max-width:1000px){.grid{grid-template-columns:1fr 1fr}.builder{grid-template-columns:1fr}}@media(max-width:720px){.shell{grid-template-columns:1fr}.side{display:none}.grid{grid-template-columns:1fr}.content{padding:14px}.hero h1{font-size:34px}}
</style></head><body><div class="shell"><aside class="side"><div class="brand">ATLAS</div><div class="sub">SOVEREIGN WORKBENCH</div><a class="nav" href="/dashboard">Dashboard</a><a class="nav on" href="/workbench">Workbench</a><a class="nav" href="/browser">Browser</a><a class="nav" href="/studio">Studio</a><a class="nav" href="/connect">Connect</a></aside><main class="main"><header class="top"><b>ATLAS Workbench</b><span class="badge">Dependency-resistant development</span></header><div class="content"><section class="hero"><span class="eyebrow">ATLAS CORE · DEVELOPER PLATFORM</span><h1>Build the tools we depend on.</h1><p>ATLAS Workbench recreates the essential developer operations previously supplied by external builders and app platforms: project scaffolding, filesystem operations, search, safe edits, checkpoints, model storage, connector readiness, validation and release controls.</p><div class="notice">The web surface is a control and scaffold preview. Repository mutations execute through the ATLAS Node CLI or CI, not through an unauthenticated public HTTP endpoint.</div></section><section class="grid">${cards}</section><section class="builder"><div class="panel"><h2>Module scaffold generator</h2><p style="color:var(--muted);font-size:11px">Generate a deterministic ATLAS module plan without calling an external builder.</p><label>Name</label><input id="name" class="field" value="Vendor Portal"><label>Description</label><textarea id="description" class="field" rows="4">Secure vendor document and statement workspace.</textarea><button id="generate" class="btn primary">Generate scaffold plan</button></div><div class="panel"><h2>Generated plan</h2><pre id="result">Press “Generate scaffold plan”.</pre><button id="copy" class="btn">Copy JSON</button></div></section><p class="foot">No credentials are stored in this surface. The connector registry records metadata and environment-variable names only.</p></div></main></div><script>
const result=document.getElementById('result');async function generate(){const n=document.getElementById('name').value;const d=document.getElementById('description').value;const r=await fetch('/api/workbench/scaffold?name='+encodeURIComponent(n)+'&description='+encodeURIComponent(d));result.textContent=JSON.stringify(await r.json(),null,2)}document.getElementById('generate').onclick=generate;document.getElementById('copy').onclick=()=>navigator.clipboard?.writeText(result.textContent);generate();
</script></body></html>`;
}

export function handleWorkbench(request,env){
  const url=new URL(request.url);
  const path=url.pathname.replace(/\/+$/,'')||'/';
  if(path==='/api/workbench/status') return new Response(JSON.stringify({ok:true,service:'ATLAS Sovereign Workbench',version:1,capabilities:WORKBENCH_CAPABILITIES.length,webMutationEndpoint:false,providerDeployment:'adapter-based'}),{headers:JSON_HEADERS});
  if(path==='/api/workbench/catalog') return new Response(JSON.stringify({ok:true,capabilities:WORKBENCH_CAPABILITIES}),{headers:JSON_HEADERS});
  if(path==='/api/workbench/scaffold') return new Response(JSON.stringify({ok:true,scaffold:createWorkbenchScaffold(url.searchParams.get('name')||'New Module',url.searchParams.get('description')||'')}),{headers:JSON_HEADERS});
  if(path==='/workbench'||path==='/forge'||path==='/developer') return new Response(page(),{headers:HTML_HEADERS});
  return null;
}
