(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,today=()=>new Date().toISOString().slice(0,10),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const KEY='atlas-enterprise-v1';
const empty=()=>({customers:[],invoices:[],expenses:[],products:[],employees:[],journals:[],audit:[],modules:{core:true,crm:true,accounting:true,inventory:true,hr:true,freight:true,documents:true,ride:false,cars:false,health:false,safety:false,community:true}});
const initial=()=>({auth:false,page:'dashboard',company:'atlas',theme:'dark',lang:'ES',companies:[{id:'atlas',name:'ATLAS Demo LLC',industry:'Technology & Professional Services'},{id:'uh4h',name:'United Hands for Humanity',industry:'Community Impact'}],data:{atlas:{...empty(),customers:[{id:uid(),name:'Orlando Pilot Client',email:'pilot@example.com',phone:'407-555-0101',status:'active'}],invoices:[{id:uid(),number:'INV-1001',customer:'Orlando Pilot Client',date:today(),total:1250,balance:1250,status:'open'}],expenses:[{id:uid(),vendor:'Cloud Infrastructure',category:'Technology',date:today(),amount:89,status:'paid'}],products:[{id:uid(),sku:'ATLAS-CORE',name:'ATLAS Core Setup',qty:10,reorder:3,cost:120,price:499,status:'active'}],employees:[{id:uid(),name:'Winder Aranguren',department:'Executive',role:'Founder',rate:0,status:'active'}],audit:[{a:'system.ready',x:'ATLAS Visual Core initialized',t:new Date().toISOString()}]},uh4h:empty()}});
let state;try{state={...initial(),...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{state=initial()}
const data=()=>state.data[state.company],save=()=>localStorage.setItem(KEY,JSON.stringify(state)),company=()=>state.companies.find(c=>c.id===state.company),log=(a,x)=>{data().audit.unshift({a,x,t:new Date().toISOString()});save()},toast=(a,x='')=>{const n=document.createElement('div');n.className='toast';n.innerHTML=`<strong>${esc(a)}</strong><span>${esc(x)}</span>`;$('#toast-root').append(n);setTimeout(()=>n.remove(),2600)};
const groups=[
 ['COMMAND',['dashboard','Command Center','⌂']],
 ['BUSINESS',['crm','CRM & Sales','◎'],['invoices','Invoices & AR','$'],['expenses','Expenses & AP','↘'],['accounting','Accounting & GL','≡'],['inventory','Inventory','□'],['employees','HR & Payroll','♙'],['reports','Reports & Intelligence','◫']],
 ['ECOSYSTEM',['freight','Freight & Partners','⇄'],['documents','Documents & Sign','▤'],['ride','ATLAS Ride','◇'],['cars','ATLAS Cars','◈'],['health','ATLAS Health','✚'],['safety','Public Safety','⬡'],['community','Community Hub','♡']],
 ['SYSTEM',['modules','Module Center','⬢'],['audit','Audit Trail','✓'],['settings','Settings','⚙']]
];
const titleMap=Object.fromEntries(groups.flatMap(g=>g.slice(1).map(i=>[i[0],i[1]])));
function shell(){
 $('#company-select').innerHTML=state.companies.map(c=>`<option value="${c.id}" ${c.id===state.company?'selected':''}>${esc(c.name)}</option>`).join('');
 $('#main-nav').innerHTML=groups.map(g=>`<div class="nav-group">${g[0]}</div>${g.slice(1).map(i=>`<button class="nav-item ${state.page===i[0]?'active':''}" data-page="${i[0]}"><span class="nav-icon">${i[2]}</span>${i[1]}</button>`).join('')}`).join('');
 $$('#main-nav [data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;save();shell();render();$('#sidebar').classList.remove('open')});
 $('#company-select').onchange=e=>{state.company=e.target.value;state.page='dashboard';save();shell();render()};
 $('#page-title').textContent=titleMap[state.page]||'ATLAS';
}
const kpi=(label,value,note,cls='')=>`<article class="card kpi"><span class="kpi-label">${label}</span><div class="kpi-value">${value}</div><span class="kpi-trend ${cls}">${note}</span></article>`;
function dashboard(){const d=data(),rev=d.invoices.reduce((a,b)=>a+(+b.total||0),0),ar=d.invoices.reduce((a,b)=>a+(+b.balance||0),0),exp=d.expenses.reduce((a,b)=>a+(+b.amount||0),0),active=Object.values(d.modules).filter(Boolean).length,total=Object.keys(d.modules).length;return `
<section class="hero"><div class="hero-content"><div><p class="eyebrow">ATLAS COMMAND CENTER</p><h1>${esc(company().name)}</h1><p>Visión consolidada de finanzas, operaciones, personas y crecimiento. Este entorno funciona como demo local y está preparado para conectarse a Supabase.</p><div class="hero-status"><span class="pill">● Core online</span><span class="pill">● Multiempresa</span><span class="pill">● Bilingüe</span><span class="pill">● Responsive</span></div></div><button class="button primary" data-add="customers">＋ Nuevo registro</button></div></section>
<div class="grid kpi-grid">${kpi('Revenue',money(rev),'+12.8% vs. prior period')}${kpi('Accounts Receivable',money(ar),'1 open invoice','warn')}${kpi('Operating Expenses',money(exp),'Controlled spending')}${kpi('Net Result',money(rev-exp),'Healthy margin')}</div>
<div class="grid two-grid"><article class="card"><div class="card-head"><div><h3>Operational readiness</h3><p>Activation status across the ATLAS ecosystem</p></div><strong>${active}/${total}</strong></div><div class="card-pad"><div class="progress"><span style="width:${Math.round(active/total*100)}%"></span></div><div class="grid module-grid" style="margin-top:18px">${Object.entries(d.modules).slice(0,6).map(([m,on])=>`<div><span class="kpi-label">${m.toUpperCase()}</span><p style="margin:6px 0"><span class="status ${on?'active':'draft'}">${on?'Active':'Planned'}</span></p></div>`).join('')}</div></div></article><article class="card"><div class="card-head"><div><h3>Recent activity</h3><p>Latest actions in this workspace</p></div></div><div class="activity">${activity(6)}</div></article></div>`}
function activity(limit=100){return data().audit.length?data().audit.slice(0,limit).map(x=>`<div class="activity-row"><span class="activity-dot"></span><div><strong>${esc(x.a)}</strong><p>${esc(x.x)}</p></div><time>${new Date(x.t).toLocaleString()}</time></div>`).join(''):`<div class="empty-state">No activity yet</div>`}
const specs={
 customers:{label:'Customer',fields:[['name','Name'],['email','Email','email'],['phone','Phone'],['status','Status','active,inactive']],headers:['Customer','Email','Phone','Status'],row:x=>`<td><strong>${esc(x.name)}</strong></td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td><span class="status ${x.status}">${x.status}</span></td>`},
 invoices:{label:'Invoice',fields:[['number','Number'],['customer','Customer'],['date','Date','date'],['total','Total','number'],['balance','Balance','number'],['status','Status','draft,open,paid,overdue']],headers:['Invoice','Customer','Date','Total','Balance','Status'],row:x=>`<td><strong>${esc(x.number)}</strong></td><td>${esc(x.customer)}</td><td>${esc(x.date)}</td><td>${money(x.total)}</td><td>${money(x.balance)}</td><td><span class="status ${x.status}">${x.status}</span></td>`},
 expenses:{label:'Expense',fields:[['vendor','Vendor'],['category','Category'],['date','Date','date'],['amount','Amount','number'],['status','Status','pending,paid']],headers:['Vendor','Category','Date','Amount','Status'],row:x=>`<td><strong>${esc(x.vendor)}</strong></td><td>${esc(x.category)}</td><td>${esc(x.date)}</td><td>${money(x.amount)}</td><td><span class="status ${x.status}">${x.status}</span></td>`},
 products:{label:'Product',fields:[['sku','SKU'],['name','Name'],['qty','Quantity','number'],['reorder','Reorder point','number'],['cost','Cost','number'],['price','Price','number'],['status','Status','active,inactive']],headers:['SKU','Product','Qty','Reorder','Cost','Price'],row:x=>`<td><strong>${esc(x.sku)}</strong></td><td>${esc(x.name)}</td><td>${x.qty}</td><td>${x.reorder}</td><td>${money(x.cost)}</td><td>${money(x.price)}</td>`},
 employees:{label:'Employee',fields:[['name','Name'],['department','Department'],['role','Role'],['rate','Hourly rate','number'],['status','Status','active,inactive']],headers:['Employee','Department','Role','Rate','Status'],row:x=>`<td><strong>${esc(x.name)}</strong></td><td>${esc(x.department)}</td><td>${esc(x.role)}</td><td>${money(x.rate)}/h</td><td><span class="status ${x.status}">${x.status}</span></td>`}
};
function list(type){const s=specs[type],rows=data()[type].map(x=>`<tr data-find="${esc(JSON.stringify(x))}">${s.row(x)}<td><button class="button small ghost" data-edit="${type}" data-id="${x.id}">Edit</button> <button class="button small danger" data-del="${type}" data-id="${x.id}">Delete</button></td></tr>`).join('');return `<div class="toolbar"><input data-filter placeholder="Search records..."><div><button class="button ghost" data-csv="${type}">Export CSV</button> <button class="button primary" data-add="${type}">＋ New ${s.label}</button></div></div><div class="card table-wrap"><table class="data-table"><thead><tr>${s.headers.map(h=>`<th>${h}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows||`<tr><td colspan="${s.headers.length+1}"><div class="empty-state">No records yet</div></td></tr>`}</tbody></table></div>`}
function accounting(){const rows=data().journals.map(x=>`<tr><td>${x.date}</td><td>${esc(x.number)}</td><td>${esc(x.memo)}</td><td>${money(x.debit)}</td><td>${money(x.credit)}</td></tr>`).join('');return `<div class="page-actions"><button class="button primary" data-add="journals">＋ Journal entry</button></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Number</th><th>Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody>${rows||'<tr><td colspan="5"><div class="empty-state">No journal entries</div></td></tr>'}</tbody></table></div>`}
function reports(){const d=data(),rev=d.invoices.reduce((a,b)=>a+(+b.total||0),0),exp=d.expenses.reduce((a,b)=>a+(+b.amount||0),0);return `<div class="page-actions"><button class="button primary" onclick="print()">Print / PDF</button></div><section class="report-sheet"><p class="eyebrow">EXECUTIVE INTELLIGENCE</p><h2>${esc(company().name)}</h2><p class="muted">Generated ${today()}</p><div class="report-metrics"><div class="report-metric"><span>Revenue</span><strong>${money(rev)}</strong></div><div class="report-metric"><span>Expenses</span><strong>${money(exp)}</strong></div><div class="report-metric"><span>Net result</span><strong>${money(rev-exp)}</strong></div></div></section>`}
const moduleInfo={core:['Core Administration','Unified command, permissions and multi-company control.'],crm:['CRM & Sales','Leads, customers, opportunities and proposals.'],accounting:['Accounting','GL, AP, AR, reconciliations and financial statements.'],inventory:['Inventory','Stock, warehouses, purchasing and fulfillment.'],hr:['HR & Payroll','People, time, payroll, learning and certification.'],freight:['Freight Network','Carrier intelligence, rates, claims and partner negotiation.'],documents:['Documents & Sign','Files, approvals, NDA, signatures and audit history.'],ride:['ATLAS Ride','Driver sessions, income, mileage and vehicle analytics.'],cars:['ATLAS Cars','Connected vehicle concepts, safety and 360° cameras.'],health:['ATLAS Health','Smart rooms, care workflows and medical intelligence.'],safety:['Public Safety','Incident intelligence, maps and digital twins.'],community:['Community Hub','Programs, assistance, donations and measurable impact.']};
function modules(){return `<div class="grid module-grid">${Object.entries(moduleInfo).map(([k,v])=>`<article class="card module-card"><div class="module-top"><span class="module-icon">${k[0].toUpperCase()}</span><span class="status ${data().modules[k]?'active':'draft'}">${data().modules[k]?'Active':'Planned'}</span></div><h3>${v[0]}</h3><p>${v[1]}</p><div style="margin-top:16px"><button class="button small ghost" data-module="${k}">${data().modules[k]?'Disable':'Activate'}</button></div></article>`).join('')}</div>`}
function ecosystem(key){const info=moduleInfo[key]||[titleMap[key],'Module specification in progress.'];return `<section class="hero"><div class="hero-content"><div><p class="eyebrow">ATLAS ECOSYSTEM</p><h1>${info[0]}</h1><p>${info[1]}</p><div class="hero-status"><span class="pill">Architecture ready</span><span class="pill">Supabase-ready</span><span class="pill">Role-based access</span></div></div><button class="button primary" data-module="${key}">${data().modules[key]?'Module active':'Activate module'}</button></div></section><div class="grid kpi-grid">${kpi('Status',data().modules[key]?'Active':'Planned','Configuration controlled')}${kpi('Data layer','Prepared','Supabase integration')}${kpi('Security','RBAC','Audit-ready')}${kpi('Experience','Responsive','Desktop · Tablet · Mobile')}</div>`}
function settings(){const c=company();return `<article class="card card-pad"><p class="eyebrow">WORKSPACE SETTINGS</p><h3>Active organization</h3><label>Name<input id="company-name" value="${esc(c.name)}"></label><label>Industry<input id="company-industry" value="${esc(c.industry)}"></label><div class="page-actions" style="margin-top:18px"><button id="save-company" class="button primary">Save</button><button id="add-company" class="button ghost">Add company</button><button id="reset-demo" class="button danger">Reset demo</button></div></article>`}
function render(){const map={dashboard,crm:()=>list('customers'),invoices:()=>list('invoices'),expenses:()=>list('expenses'),accounting,inventory:()=>list('products'),employees:()=>list('employees'),reports,modules,audit:()=>`<article class="card"><div class="card-head"><div><h3>Audit trail</h3><p>Immutable-style activity history for this demo workspace</p></div></div><div class="activity">${activity()}</div></article>`,settings,freight:()=>ecosystem('freight'),documents:()=>ecosystem('documents'),ride:()=>ecosystem('ride'),cars:()=>ecosystem('cars'),health:()=>ecosystem('health'),safety:()=>ecosystem('safety'),community:()=>ecosystem('community')};$('#content').innerHTML=(map[state.page]||dashboard)();bind();}
function modal(type,id){const spec=type==='journals'?{label:'Journal entry',fields:[['date','Date','date'],['number','Number'],['memo','Description'],['debit','Debit','number'],['credit','Credit','number']]}:specs[type],arr=data()[type],old=arr.find(x=>x.id===id)||{};const fields=spec.fields.map(([k,l,t='text'])=>t.includes(',')?`<label>${l}<select name="${k}">${t.split(',').map(v=>`<option ${old[k]===v?'selected':''}>${v}</option>`).join('')}</select></label>`:`<label>${l}<input name="${k}" type="${t}" value="${esc(old[k]??(t==='date'?today():''))}"></label>`).join('');$('#modal-root').innerHTML=`<div class="modal-backdrop"><form id="record-form" class="modal-card"><div class="modal-head"><h3>${id?'Edit':'Create'} ${spec.label}</h3><button type="button" class="icon-button" data-close>✕</button></div><div class="modal-body">${fields}</div><div class="modal-foot"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Save</button></div></form></div>`;$$('[data-close]').forEach(b=>b.onclick=()=>$('#modal-root').innerHTML='');$('#record-form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),record={...old,id:old.id||uid()};spec.fields.forEach(([k,,t='text'])=>record[k]=t==='number'?Number(fd.get(k)):fd.get(k));if(type==='journals'&&record.debit!==record.credit)return toast('Journal not balanced','Debit and credit must match.');if(type==='invoices'&&!id&&!record.balance)record.balance=record.total;id?Object.assign(old,record):arr.unshift(record);log(`${type}.${id?'update':'create'}`,record.name||record.number||record.vendor||record.memo);$('#modal-root').innerHTML='';render()}}
function csv(type){const rows=data()[type];if(!rows.length)return toast('Nothing to export');const keys=Object.keys(rows[0]).filter(k=>k!=='id'),text=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text]));a.download=`atlas-${type}-${today()}.csv`;a.click()}
function bind(){$$('[data-add]').forEach(b=>b.onclick=()=>modal(b.dataset.add));$$('[data-edit]').forEach(b=>b.onclick=()=>modal(b.dataset.edit,b.dataset.id));$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this record?')){const t=b.dataset.del;data()[t]=data()[t].filter(x=>x.id!==b.dataset.id);log(`${t}.delete`,b.dataset.id);render()}});$$('[data-csv]').forEach(b=>b.onclick=()=>csv(b.dataset.csv));$$('[data-filter]').forEach(i=>i.oninput=()=>$$('[data-find]').forEach(r=>r.hidden=!r.dataset.find.toLowerCase().includes(i.value.toLowerCase())));$$('[data-module]').forEach(b=>b.onclick=()=>{const k=b.dataset.module;data().modules[k]=!data().modules[k];log('module.toggle',k);render()});if($('#save-company'))$('#save-company').onclick=()=>{company().name=$('#company-name').value;company().industry=$('#company-industry').value;log('organization.update',company().name);shell();render()};if($('#add-company'))$('#add-company').onclick=()=>{const name=prompt('Company name');if(name){const id=uid();state.companies.push({id,name,industry:''});state.data[id]=empty();state.company=id;save();shell();render()}};if($('#reset-demo'))$('#reset-demo').onclick=()=>{if(confirm('Reset all local demo data?')){localStorage.removeItem(KEY);location.reload()}}}
function openApp(){state.auth=true;save();$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');document.documentElement.classList.toggle('light',state.theme==='light');shell();render()}
$('#login-form').onsubmit=e=>{e.preventDefault();if($('#login-email').value==='demo@atlas.local'&&$('#login-password').value==='Atlas2026!'){$('#login-form').classList.add('hidden');$('#otp-form').classList.remove('hidden')}else toast('Incorrect credentials')};$('#otp-form').onsubmit=e=>{e.preventDefault();$('#otp-code').value==='246810'?openApp():toast('Incorrect verification code')};$('#back-to-login').onclick=()=>{$('#otp-form').classList.add('hidden');$('#login-form').classList.remove('hidden')};$('#toggle-password').onclick=()=>$('#login-password').type=$('#login-password').type==='password'?'text':'password';$('#logout-btn').onclick=()=>{state.auth=false;save();location.reload()};$('#menu-btn').onclick=()=>$('#sidebar').classList.add('open');$('#sidebar-close').onclick=()=>$('#sidebar').classList.remove('open');$('#theme-btn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.classList.toggle('light',state.theme==='light');save()};$('#language-btn').onclick=()=>{state.lang=state.lang==='ES'?'EN':'ES';$('#language-btn').textContent=state.lang;toast('Language preference saved',state.lang);save()};$('#quick-add-btn').onclick=()=>modal('customers');
const openSearch=()=>{$('#search-overlay').classList.remove('hidden');$('#global-search-input').focus();search('')},closeSearch=()=>$('#search-overlay').classList.add('hidden');$('#global-search-btn').onclick=openSearch;$('#close-search').onclick=closeSearch;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSearch()});$('#global-search-input').oninput=e=>search(e.target.value);
function search(q){const items=[...groups.flatMap(g=>g.slice(1).map(i=>({title:i[1],type:'Module',page:i[0]}))),...data().customers.map(x=>({title:x.name,type:'Customer',page:'crm'})),...data().invoices.map(x=>({title:x.number,type:'Invoice',page:'invoices'})),...data().employees.map(x=>({title:x.name,type:'Employee',page:'employees'}))].filter(x=>`${x.title} ${x.type}`.toLowerCase().includes(q.toLowerCase())).slice(0,12);$('#search-results').innerHTML=items.map(x=>`<button class="search-result" data-search-page="${x.page}"><strong>${esc(x.title)}</strong><div class="muted">${x.type}</div></button>`).join('')||'<div class="empty-state">No results</div>';$$('[data-search-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.searchPage;save();shell();render();closeSearch()})}
$('#notifications-btn').onclick=()=>toast('ATLAS notifications','3 system notices are ready for review.');if(state.auth)openApp();
})();