(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=()=>window.ATLASDataFabric,i=()=>window.ATLASIntelligence;
const privateRecordOptions=()=>({subjectUserId:f().session()?.user?.id||null});
let view='overview';
let analysis=[];
const MB=1024*1024;
function toast(msg){const root=$('#mail-toast');const el=document.createElement('div');el.textContent=msg;root.append(el);setTimeout(()=>el.remove(),3200)}
function bytes(v){const n=Number(v)||0;if(n>=1024*1024*1024)return `${(n/(1024*1024*1024)).toFixed(2)} GB`;if(n>=MB)return `${(n/MB).toFixed(1)} MB`;if(n>=1024)return `${(n/1024).toFixed(1)} KB`;return `${n} B`}
function ageDays(date){const t=new Date(date||0).getTime();return Number.isFinite(t)?Math.floor((Date.now()-t)/86400000):0}
function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
function title(){return {overview:'Inbox Health',recommendations:'Recommendations',subscriptions:'Subscriptions',analyze:'Analyze Metadata',connectors:'Mail Connectors',privacy:'Privacy Controls'}[view]||'ATLAS Mail'}
function table(cols,rows){if(!rows.length)return '<div class="mail-empty">No production records yet.</div>';return `<div class="mail-table-wrap"><table class="mail-table"><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[2]==='bytes'?bytes(r[c[0]]):esc(r[c[0]]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
async function data(){const [recs,subs,plans,connectors,events]=await Promise.all([
 f().moduleRecords('mail','recommendation'),
 f().moduleRecords('mail','subscription'),
 f().moduleRecords('mail','cleanup_plan'),
 f().list('atlas_connectors',{order:'updated_at',limit:100}).catch(()=>[]),
 f().listEvents({limit:100}).catch(()=>[])
]);
 return{recs,subs,plans,connectors:connectors.filter(x=>x.connector_key?.includes('mail')||x.config?.provider||x.kind==='messaging'),events:events.filter(x=>x.source_module==='mail'||x.target_module==='mail')};}
function savedPayload(rows){return rows.map(x=>({id:x.id,status:x.status,updated_at:x.updated_at,...(x.payload||{})}))}
function overview(d){const recs=savedPayload(d.recs),subs=savedPayload(d.subs);const reclaim=recs.filter(x=>x.status!=='dismissed').reduce((s,x)=>s+Number(x.estimated_bytes||0),0);const actionable=recs.filter(x=>!['dismissed','completed'].includes(String(x.status||''))).length;const inactive=subs.filter(x=>x.status==='inactive'||x.recommendation==='unsubscribe').length;return `<section class="mail-hero"><div><p class="mail-eyebrow">METADATA-FIRST · HUMAN CONFIRMATION</p><h2>Keep the inbox useful without giving ATLAS permission to delete blindly.</h2><p>ATLAS Mail turns message metadata into explainable cleanup recommendations. Provider execution stays disconnected until an authorized connector exists, and destructive actions remain confirmation-gated.</p></div><div class="mail-orb">✦</div></section><section class="mail-kpis"><article class="mail-kpi"><span>Saved recommendations</span><strong>${recs.length}</strong></article><article class="mail-kpi"><span>Estimated reclaimable</span><strong>${bytes(reclaim)}</strong></article><article class="mail-kpi"><span>Actionable</span><strong>${actionable}</strong></article><article class="mail-kpi"><span>Inactive lists</span><strong>${inactive}</strong></article></section><section class="mail-grid two"><article class="mail-card"><h3>Inbox Intelligence status</h3><div class="mail-status"><div class="mail-status-row"><span>Metadata analysis</span><b class="ok">ACTIVE</b></div><div class="mail-status-row"><span>Recommendation storage</span><b class="ok">ACTIVE</b></div><div class="mail-status-row"><span>Delete / unsubscribe execution</span><b class="pending">CONFIRM + CONNECTOR REQUIRED</b></div><div class="mail-status-row"><span>Message body ingestion</span><b class="ok">NOT REQUIRED</b></div></div></article><article class="mail-card"><h3>Latest recommendations</h3>${recommendationCards(recs.slice(0,5),false)}</article></section><article class="mail-card"><h3>Mail events</h3>${table([['occurred_at','Time'],['event_type','Event'],['target_module','Target']],d.events.slice(0,12))}</article>`}
function recommendationCards(rows,actions=true){if(!rows.length)return '<div class="mail-empty">No recommendations yet. Analyze metadata or connect a mail provider.</div>';return `<div class="mail-recommendations">${rows.map(x=>`<article class="mail-rec"><div><h4>${esc(x.title||x.category||'Recommendation')}</h4><p>${esc(x.reason||x.summary||'Explainable cleanup recommendation')}</p><div class="mail-rec-meta"><span class="mail-pill">${esc(x.category||'cleanup')}</span><span class="mail-pill ok">${bytes(x.estimated_bytes||0)}</span><span class="mail-pill">${Number(x.message_count||0)} messages</span><span class="mail-pill ${x.requires_confirmation===false?'ok':'warn'}">${x.requires_confirmation===false?'No delete action':'Confirmation required'}</span>${x.status?`<span class="mail-pill">${esc(x.status)}</span>`:''}</div></div>${actions&&x.status!=='dismissed'?`<div class="mail-rec-actions"><button class="mail-btn primary" data-plan="${esc(x.id)}">Add to plan</button><button class="mail-btn" data-dismiss="${esc(x.id)}">Dismiss</button></div>`:''}</article>`).join('')}</div>`}
function recommendations(d){const recs=savedPayload(d.recs);return `<div class="mail-grid two"><article class="mail-card"><h2>Explainable recommendations</h2><p>Every item states why ATLAS recommends it, how much storage may be recovered, and whether a destructive provider action would be required.</p></article><article class="mail-card"><h2>Cleanup plans</h2><p>${d.plans.length} plan item(s) are staged. Staging does not delete or unsubscribe anything.</p></article></div><article class="mail-card">${recommendationCards(recs,true)}</article>`}
function subscriptions(d){const rows=savedPayload(d.subs).map(x=>({sender:x.sender||x.list_name||'',last_seen:x.last_seen||'',messages:x.message_count||0,status:x.status||'',recommendation:x.recommendation||''}));return `<section class="mail-grid two"><article class="mail-card"><h2>Mailing-list intelligence</h2><p>ATLAS can flag high-volume or long-inactive lists from metadata. An unsubscribe action is never executed from this page without a live authorized connector and explicit confirmation.</p></article><article class="mail-card"><h2>Current state</h2><div class="mail-status"><div class="mail-status-row"><span>Saved lists</span><b>${rows.length}</b></div><div class="mail-status-row"><span>Automatic unsubscribe</span><b class="pending">OFF</b></div></div></article></section><article class="mail-card">${table([['sender','Sender / list'],['last_seen','Last seen'],['messages','Messages'],['status','Status'],['recommendation','Recommendation']],rows)}</article>`}
function analyze(){return `<section class="mail-grid two"><article class="mail-card"><h2>Analyze exported metadata</h2><p>Import a JSON array containing message metadata. ATLAS processes it in memory and does not upload the raw list. Only recommendations you explicitly save are written to production.</p><div class="mail-drop"><strong>Metadata JSON</strong><p class="mail-note">Accepted fields include sender/from, date/receivedAt, category, sizeBytes/size, mailingList/listId and opened.</p><input id="metadata-file" type="file" accept="application/json,.json"></div></article><article class="mail-card"><h2>Analysis rules</h2><div class="mail-privacy"><div><span>01</span><p><b>Old promotions</b><br>Promotion messages older than 180 days.</p></div><div><span>02</span><p><b>Large stale messages</b><br>Messages over 5 MB and older than 90 days.</p></div><div><span>03</span><p><b>Inactive mailing lists</b><br>Unopened list traffic older than 90 days.</p></div><div><span>04</span><p><b>Stale notifications</b><br>Social or notification mail older than 180 days.</p></div></div></article></section><article class="mail-card"><div class="mail-actions"><button id="save-analysis" class="mail-btn primary" ${analysis.length?'':'disabled'}>Save recommendations</button><button id="clear-analysis" class="mail-btn" ${analysis.length?'':'disabled'}>Clear local analysis</button></div><h3>Local analysis results</h3>${recommendationCards(analysis.map((x,n)=>({...x,id:`local-${n}`})),false)}</article>`}
function connectors(d){const rows=d.connectors.map(x=>({name:x.display_name||x.connector_key,provider:x.config?.provider||'',kind:x.kind,status:x.status,updated_at:x.updated_at}));return `<section class="mail-grid two"><article class="mail-card"><h2>Register a mail connector</h2><form id="connector-form" class="mail-form"><label>Provider<select name="provider"><option value="icloud_mail">iCloud Mail</option><option value="gmail_mail">Gmail</option><option value="outlook_mail">Outlook</option><option value="imap_mail">Standards-based mail</option></select></label><label>Display name<input name="display_name" placeholder="My mail account" required></label><button class="mail-btn primary">Register connector metadata</button></form><p class="mail-note">This stores connector metadata only. Passwords, API keys and mail credentials are never requested or stored in browser records.</p></article><article class="mail-card"><h2>Provider boundary</h2><div class="mail-status"><div class="mail-status-row"><span>Connector registry</span><b class="ok">ACTIVE</b></div><div class="mail-status-row"><span>Secrets</span><b class="ok">SERVER-ONLY</b></div><div class="mail-status-row"><span>Provider execution</span><b class="pending">ACTIVATE PER PROVIDER</b></div></div></article></section><article class="mail-card"><h3>Registered mail connectors</h3>${table([['name','Name'],['provider','Provider'],['kind','Kind'],['status','Status'],['updated_at','Updated']],rows)}</article>`}
function privacy(){return `<section class="mail-grid two"><article class="mail-card"><h2>Privacy by design</h2><div class="mail-privacy"><div><span>✓</span><p><b>Metadata first.</b><br>Sender, date, category, size and list identifiers are enough for the baseline cleanup engine.</p></div><div><span>✓</span><p><b>No body required.</b><br>The baseline recommendation engine does not need the message body.</p></div><div><span>✓</span><p><b>Ephemeral import.</b><br>Imported metadata is analyzed in memory and discarded unless the user saves aggregate recommendations.</p></div><div><span>✓</span><p><b>Per-user storage.</b><br>Saved mail-intelligence records are tied to the authenticated user rather than exposed as ordinary organization records.</p></div><div><span>✓</span><p><b>Confirmation gate.</b><br>Delete and unsubscribe actions remain staged until a user explicitly approves execution through an authorized provider connector.</p></div></div></article><article class="mail-card"><h2>What ATLAS will not claim</h2><p>ATLAS does not claim that iCloud, Gmail, Outlook or another mailbox has been scanned unless a live provider adapter actually performed that read. A registered connector marked disconnected is configuration metadata, not proof of provider access.</p></article></section>`}
async function render(){const root=$('#mail-content');$('#mail-title').textContent=title();$$('#mail-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));root.innerHTML='<article class="mail-card"><p>Loading production…</p></article>';try{const d=await data();if(view==='overview')root.innerHTML=overview(d);else if(view==='recommendations')root.innerHTML=recommendations(d);else if(view==='subscriptions')root.innerHTML=subscriptions(d);else if(view==='analyze')root.innerHTML=analyze();else if(view==='connectors')root.innerHTML=connectors(d);else root.innerHTML=privacy();bind(d);}catch(e){root.innerHTML=`<article class="mail-card"><h3>Production error</h3><p>${esc(e.message)}</p></article>`}}
function normalizeMessage(x){return{sender:String(x.sender||x.from||x.fromAddress||'Unknown'),date:x.date||x.receivedAt||x.received_at||x.timestamp||null,category:String(x.category||x.type||'').toLowerCase(),size:Number(x.sizeBytes||x.size_bytes||x.size||0),list:String(x.mailingList||x.listId||x.list_id||''),opened:x.opened===true||Boolean(x.lastOpenedAt||x.last_opened_at)}}
function analyzeMessages(input){const rows=input.map(normalizeMessage).filter(x=>x.date);const result=[];const add=(category,title,items,reason)=>{if(!items.length)return;result.push({category,title,message_count:items.length,estimated_bytes:items.reduce((s,x)=>s+x.size,0),reason,requires_confirmation:true})};add('old_promotions','Old promotions',rows.filter(x=>x.category.includes('promo')&&ageDays(x.date)>180),'Promotional messages older than 180 days are strong cleanup candidates.');add('large_stale','Large stale messages',rows.filter(x=>x.size>=5*MB&&ageDays(x.date)>90),'Large messages older than 90 days may recover meaningful storage.');add('stale_notifications','Stale notifications',rows.filter(x=>(x.category.includes('social')||x.category.includes('notification'))&&ageDays(x.date)>180),'Old social and notification messages often have low long-term value.');const inactive=rows.filter(x=>(x.list||x.category.includes('newsletter'))&&!x.opened&&ageDays(x.date)>90);add('inactive_lists','Inactive mailing lists',inactive,'Mailing-list traffic not opened for more than 90 days may be worth reviewing or unsubscribing from.');return result}
async function saveAnalysis(){if(!analysis.length)return;try{for(const item of analysis){const row=await f().createModuleRecord('mail','recommendation',item,{...privateRecordOptions(),status:'open'});await i().emit('mail.recommendation.created','mail',{targetModule:'analytics',entityType:'mail_recommendation',entityId:row.id,payload:{category:item.category,message_count:item.message_count,estimated_bytes:item.estimated_bytes}})}analysis=[];toast('Recommendations saved to production');view='recommendations';render()}catch(e){toast(e.message)}}
async function addPlan(id,d){const source=d.recs.find(x=>x.id===id);if(!source)return;const p=source.payload||{};try{const row=await f().createModuleRecord('mail','cleanup_plan',{recommendation_id:id,title:p.title||p.category,category:p.category,estimated_bytes:p.estimated_bytes||0,message_count:p.message_count||0,requires_confirmation:true},{...privateRecordOptions(),status:'draft'});await i().emit('mail.cleanup_plan.staged','mail',{targetModule:'security',entityType:'cleanup_plan',entityId:row.id,payload:{requires_confirmation:true,category:p.category}});toast('Cleanup plan staged — nothing deleted');render()}catch(e){toast(e.message)}}
async function dismiss(id,d){const source=d.recs.find(x=>x.id===id);if(!source)return;try{await f().updateModuleRecord(id,source.payload||{},{status:'dismissed',moduleCode:'mail',recordType:'recommendation',subjectUserId:f().session().user.id});await i().emit('mail.recommendation.dismissed','mail',{targetModule:'analytics',entityType:'mail_recommendation',entityId:id});toast('Recommendation dismissed');render()}catch(e){toast(e.message)}}
function bind(d){
 $('#metadata-file')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!Array.isArray(parsed))throw new Error('Metadata JSON must be an array');analysis=analyzeMessages(parsed);toast(`${analysis.length} recommendation group(s) found locally`);render()}catch(err){analysis=[];toast(err.message)}});
 $('#save-analysis')?.addEventListener('click',saveAnalysis);
 $('#clear-analysis')?.addEventListener('click',()=>{analysis=[];render()});
 $$('[data-plan]').forEach(b=>b.onclick=()=>addPlan(b.dataset.plan,d));
 $$('[data-dismiss]').forEach(b=>b.onclick=()=>dismiss(b.dataset.dismiss,d));
 $('#connector-form')?.addEventListener('submit',async e=>{e.preventDefault();const x=new FormData(e.currentTarget),provider=String(x.get('provider'));try{await f().insert('atlas_connectors',{connector_key:provider,display_name:x.get('display_name'),kind:'messaging',mode:'production',status:'disconnected',config:{provider,scope:'metadata-first',destructive_actions:'confirmation-required'},updated_by:f().session().user.id});await i().emit('mail.connector.registered','mail',{targetModule:'security',payload:{provider,status:'disconnected'}});toast('Connector metadata registered');render()}catch(err){toast(err.message)}});
}
async function exportSnapshot(){try{const d=await data();download(`atlas-mail-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify({organization:f().activeOrg(),exportedAt:new Date().toISOString(),recommendations:savedPayload(d.recs),subscriptions:savedPayload(d.subs),cleanupPlans:savedPayload(d.plans),connectors:d.connectors.map(x=>({connector_key:x.connector_key,display_name:x.display_name,kind:x.kind,status:x.status,config:x.config,updated_at:x.updated_at}))},null,2));toast('Mail snapshot exported')}catch(e){toast(e.message)}}
async function init(){await f().initialize();if(!f().session()){location.href='index.html';return}const orgs=await f().organizations();if(!orgs.length){location.href='cloud-auth.html';return}f().setActiveOrg(f().activeOrg()||orgs[0]);await i().start();$$('#mail-nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#refresh-btn').onclick=render;$('#export-btn').onclick=exportSnapshot;render()}
init().catch(e=>toast(e.message));
})();