import baseWorker from './worker.js';
import {handleFinance} from './modules/finance-worker.js';
import {handleWeather} from './modules/weather-worker.js';
import {handleEnterpriseAccounting} from './modules/enterprise-accounting-worker.js';
import {handleDemoCenter} from './modules/demo-center-worker.js';
import {handleIdentity} from './modules/identity-worker.js';
import {handleAutonomousAccounting} from './modules/autonomous-accounting-worker.js';
import {handleVideo} from './modules/video-worker.js';
import {handleWorkManagement} from './modules/work-management-worker.js';
import {handleMobilityCommerce} from './modules/mobility-commerce-worker.js';
import {handleLaunchQueue} from './modules/launch-queue-worker.js';

function decodeBase64Asset(text){const clean=text.trim();const raw=atob(clean);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes;}
async function weatherImage(request,env){if(!env?.ASSETS)return new Response('Weather asset unavailable',{status:503});const assetUrl=new URL('/weather/current.webp.b64',request.url);const source=await env.ASSETS.fetch(new Request(assetUrl,request));if(!source.ok)return new Response('Weather asset unavailable',{status:source.status});const bytes=decodeBase64Asset(await source.text());return new Response(bytes,{headers:{'content-type':'image/webp','cache-control':'public, max-age=86400'}});}
async function decorate(response){const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();const sideNeedle='href="/climate"><span class="ico">☁</span>ATLAS Climate</a>';if(html.includes(sideNeedle)&&!html.includes('href="/weather"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/weather"><span class="ico">☀</span>ATLAS Weather View</a>');if(html.includes(sideNeedle)&&!html.includes('href="/identity"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/identity"><span class="ico">◈</span>ATLAS Identity</a>');if(html.includes(sideNeedle)&&!html.includes('href="/video"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/video"><span class="ico">◉</span>ATLAS Video</a>');if(html.includes(sideNeedle)&&!html.includes('href="/accounting"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/accounting"><span class="ico">$</span>Autonomous Accounting</a>');if(html.includes(sideNeedle)&&!html.includes('href="/launch-queue"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/launch-queue"><span class="ico">◷</span>Launch Queue</a><a class="nav" href="/work"><span class="ico">▣</span>Work Management</a><a class="nav" href="/ride"><span class="ico">◆</span>ATLAS Ride</a><a class="nav" href="/driver"><span class="ico">◈</span>ATLAS Driver</a><a class="nav" href="/marketplace"><span class="ico">▤</span>Marketplace</a><a class="nav" href="/driver-finance"><span class="ico">$</span>Driver Finance</a>');const footNeedle='<a href="/climate">☁ Climate</a>';if(html.includes(footNeedle)&&!html.includes('href="/weather">☀ Weather'))html=html.replace(footNeedle,footNeedle+'<a href="/weather">☀ Weather</a>');if(html.includes(footNeedle)&&!html.includes('href="/video">◉ Video'))html=html.replace(footNeedle,footNeedle+'<a href="/video">◉ Video</a>');if(html.includes(footNeedle)&&!html.includes('href="/accounting">$ Accounting'))html=html.replace(footNeedle,footNeedle+'<a href="/accounting">$ Accounting</a>');if(html.includes(footNeedle)&&!html.includes('href="/launch-queue">◷ Launch Queue'))html=html.replace(footNeedle,footNeedle+'<a href="/launch-queue">◷ Launch Queue</a><a href="/work">▣ Work</a><a href="/ride">◆ Ride</a>');const headers=new Headers(response.headers);headers.set('content-length',String(new TextEncoder().encode(html).length));return new Response(html,{status:response.status,statusText:response.statusText,headers});}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==='/identity'||url.pathname.startsWith('/api/identity/')){const response=handleIdentity(request);if(response)return response;}if(url.pathname==='/video'||url.pathname.startsWith('/video/')){const response=handleVideo(request);if(response)return response;}if(url.pathname==='/work'||url.pathname.startsWith('/work/')||url.pathname.startsWith('/api/work/')){const response=handleWorkManagement(request);if(response)return response;}if(url.pathname==='/ride'||url.pathname.startsWith('/ride/')||url.pathname==='/driver'||url.pathname.startsWith('/driver/')||url.pathname==='/marketplace'||url.pathname.startsWith('/marketplace/')||url.pathname==='/driver-finance'||url.pathname.startsWith('/driver-finance/')||url.pathname.startsWith('/api/mobility/')){const response=handleMobilityCommerce(request);if(response)return response;}if(url.pathname==='/launch-queue'||url.pathname.startsWith('/launch-queue/')||url.pathname.startsWith('/api/launch-queue')){const response=handleLaunchQueue(request);if(response)return response;}if(url.pathname==='/weather/current.webp')return weatherImage(request,env);if(url.pathname==='/weather'){const response=await handleWeather(request,env,ctx);if(response)return response;}if(url.pathname==='/demos'||url.pathname.startsWith('/demos/')){const response=handleDemoCenter(request);if(response)return response;}if(url.pathname==='/accounting'||url.pathname.startsWith('/accounting/')){const response=handleAutonomousAccounting(request);if(response)return response;}if(url.pathname.startsWith('/finance/multi-entity')||url.pathname.startsWith('/finance/fpa')||url.pathname.startsWith('/finance/reporting/management')||url.pathname.startsWith('/finance/reporting/kpis')||url.pathname.startsWith('/finance/reporting/audit')||url.pathname==='/finance/revenue-recognition'||url.pathname==='/finance/controls'){const response=handleEnterpriseAccounting(request);if(response)return response;}if(url.pathname==='/api/finance/capabilities'||url.pathname==='/api/finance/health'||url.pathname==='/finance'||url.pathname.startsWith('/finance/')){const response=await handleFinance(request,env,ctx);if(response)return decorate(response);}const response=await baseWorker.fetch(request,env,ctx);return decorate(response);},async scheduled(controller,env,ctx){if(typeof baseWorker.scheduled==='function')return baseWorker.scheduled(controller,env,ctx);ctx?.waitUntil?.(Promise.resolve());console.log('atlas_scheduled_ok',{cron:controller?.cron??null,scheduledTime:controller?.scheduledTime??null});}};
