import baseWorker from './worker.js';
import {handleFinance} from './modules/finance-worker.js';
import {handleWeather} from './modules/weather-worker.js';
import {handleEnterpriseAccounting} from './modules/enterprise-accounting-worker.js';
import {handleDemoCenter} from './modules/demo-center-worker.js';
import {handleIdentity} from './modules/identity-worker.js';
import {handleAutonomousAccounting} from './modules/autonomous-accounting-worker.js';
import {handleVideo} from './modules/video-worker.js';
export {VideoRoom} from './modules/video-signal-room.js';

function decodeBase64Asset(text){const clean=text.trim();const raw=atob(clean);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes;}
async function weatherImage(request,env){if(!env?.ASSETS)return new Response('Weather asset unavailable',{status:503});const assetUrl=new URL('/weather/current.webp.b64',request.url);const source=await env.ASSETS.fetch(new Request(assetUrl,request));if(!source.ok)return new Response('Weather asset unavailable',{status:source.status});const bytes=decodeBase64Asset(await source.text());return new Response(bytes,{headers:{'content-type':'image/webp','cache-control':'public, max-age=86400'}});}
async function videoSignal(request,env){if(!env?.VIDEO_ROOMS)return Response.json({ok:false,error:'Video signaling binding unavailable'},{status:503});const url=new URL(request.url);const room=String(url.searchParams.get('room')||'').replace(/[^A-Za-z0-9_-]/g,'').slice(0,80);if(!room)return Response.json({ok:false,error:'room is required'},{status:400});const id=env.VIDEO_ROOMS.idFromName(room);return env.VIDEO_ROOMS.get(id).fetch(request);}
async function decorate(response){const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();const sideNeedle='href="/climate"><span class="ico">☁</span>ATLAS Climate</a>';if(html.includes(sideNeedle)&&!html.includes('href="/weather"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/weather"><span class="ico">☀</span>ATLAS Weather View</a>');if(html.includes(sideNeedle)&&!html.includes('href="/identity"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/identity"><span class="ico">◈</span>ATLAS Identity</a>');if(html.includes(sideNeedle)&&!html.includes('href="/video"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/video"><span class="ico">◉</span>ATLAS Video</a>');if(html.includes(sideNeedle)&&!html.includes('href="/accounting"'))html=html.replace(sideNeedle,sideNeedle+'<a class="nav" href="/accounting"><span class="ico">$</span>Autonomous Accounting</a>');const footNeedle='<a href="/climate">☁ Climate</a>';if(html.includes(footNeedle)&&!html.includes('href="/weather">☀ Weather'))html=html.replace(footNeedle,footNeedle+'<a href="/weather">☀ Weather</a>');if(html.includes(footNeedle)&&!html.includes('href="/video">◉ Video'))html=html.replace(footNeedle,footNeedle+'<a href="/video">◉ Video</a>');if(html.includes(footNeedle)&&!html.includes('href="/accounting">$ Accounting'))html=html.replace(footNeedle,footNeedle+'<a href="/accounting">$ Accounting</a>');const headers=new Headers(response.headers);headers.set('content-length',String(new TextEncoder().encode(html).length));return new Response(html,{status:response.status,statusText:response.statusText,headers});}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==='/api/video/signal')return videoSignal(request,env);if(url.pathname==='/identity'||url.pathname.startsWith('/api/identity/')){const response=handleIdentity(request);if(response)return response;}if(url.pathname==='/video'||url.pathname.startsWith('/video/')){const response=handleVideo(request);if(response)return response;}if(url.pathname==='/weather/current.webp')return weatherImage(request,env);if(url.pathname==='/weather'){const response=await handleWeather(request,env,ctx);if(response)return response;}if(url.pathname==='/demos'||url.pathname.startsWith('/demos/')){const response=handleDemoCenter(request);if(response)return response;}if(url.pathname==='/accounting'||url.pathname.startsWith('/accounting/')){const response=handleAutonomousAccounting(request);if(response)return response;}if(url.pathname.startsWith('/finance/multi-entity')||url.pathname.startsWith('/finance/fpa')||url.pathname.startsWith('/finance/reporting/management')||url.pathname.startsWith('/finance/reporting/kpis')||url.pathname.startsWith('/finance/reporting/audit')||url.pathname==='/finance/revenue-recognition'||url.pathname==='/finance/controls'){const response=handleEnterpriseAccounting(request);if(response)return response;}if(url.pathname==='/api/finance/capabilities'||url.pathname==='/api/finance/health'||url.pathname==='/finance'||url.pathname.startsWith('/finance/')){const response=await handleFinance(request,env,ctx);if(response)return decorate(response);}const response=await baseWorker.fetch(request,env,ctx);return decorate(response);},async scheduled(controller,env,ctx){if(typeof baseWorker.scheduled==='function')return baseWorker.scheduled(controller,env,ctx);ctx?.waitUntil?.(Promise.resolve());console.log('atlas_scheduled_ok',{cron:controller?.cron??null,scheduledTime:controller?.scheduledTime??null});}};
