(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,today=()=>new Date().toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(+n||0),num=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(+n||0);
const KEY='atlas-suite-functional-v4',MAX_IMG=850*1024;
const modules={
 dashboard:['Centro de Mando','⌂',null,'Visión consolidada de todo ATLAS.'],crm:['CRM y Ventas','◎','customers','Clientes y relaciones comerciales.'],invoices:['Facturas y CxC','$','invoices','Facturación, saldos y cobros.'],expenses:['Gastos y CxP','↘','expenses','Gastos, proveedores y conciliación.'],accounting:['Contabilidad y GL','≡','journals','Asientos, débitos y créditos.'],inventory:['Inventario','□','products','Existencias, costos y precios.'],employees:['RR. HH. y Nómina','♙','employees','Personas, roles y compensación.'],reports:['Reportes e Inteligencia','◫',null,'Indicadores y exportaciones.'],wallet:['ATLAS Wallet','◩','wallet','Identidades, licencias, credenciales y tarjetas enmascaradas.'],documents:['Documentos y Firma','▤','documents','Documentos, vigencia, firma y auditoría.'],rewards:['ATLAS Rewards','★','rewards','Puntos, niveles, bonos y canjes.'],ride:['ATLAS Ride','◇','ride','Apps gig, viajes, entregas, millaje e ingresos.'],marketplace:['ATLAS Marketplace','▦','marketplace','Órdenes, comercios, recibos y tarjetas operativas.'],freight:['Freight y Socios','⇄','shipments','Envíos, transportistas y rutas.'],cars:['ATLAS Cars','◈','vehicles','Vehículos, seguro y mantenimiento.'],health:['ATLAS Health','✚','health','Citas y seguimiento administrativo.'],safety:['Seguridad Pública','⬡','safety','Incidentes, prioridad y resolución.'],community:['Community Hub','♡','community','Programas, casos y ayudas.'],modules:['Centro de Módulos','⬢',null,'Activación de módulos.'],audit:['Auditoría','✓',null,'Historial local de acciones.'],settings:['Configuración','⚙',null,'Empresa, respaldo y privacidad.']
};
const groups=[['COMMAND','dashboard'],['BUSINESS','crm','invoices','expenses','accounting','inventory','employees','reports'],['IDENTITY & FINANCE','wallet','documents','rewards'],['OPERATIONS','ride','marketplace','freight','cars'],['IMPACT','health','safety','community'],['SYSTEM','modules','audit','settings']];
const S=(label,fields,cols)=>({label,fields,cols});
const schemas={
 customers:S('Cliente',[['name','Nombre','text',1],['company','Empresa'],['email','Correo','email'],['phone','Teléfono'],['status','Estado','select',1,['active','lead','inactive']],['notes','Notas','textarea']],[['name','Cliente'],['company','Empresa'],['email','Correo'],['status','Estado']]),
 invoices:S('Factura',[['number','Número','text',1],['customer','Cliente','text',1],['date','Fecha','date',1],['due','Vencimiento','date'],['total','Total','number',1],['balance','Saldo','number'],['status','Estado','select',1,['draft','open','paid','overdue']]],[['number','Factura'],['customer','Cliente'],['date','Fecha','date'],['total','Total','money'],['balance','Saldo','money'],['status','Estado']]),
 expenses:S('Gasto',[['vendor','Proveedor','text',1],['category','Categoría','text',1],['date','Fecha','date',1],['amount','Importe','number',1],['cardLast4','Tarjeta · últimos 4'],['use','Uso','select',1,['personal','business','mixed']],['status','Estado','select',1,['pending','paid','reconciled']],['notes','Notas','textarea']],[['vendor','Proveedor'],['category','Categoría'],['date','Fecha','date'],['amount','Importe','money'],['cardLast4','Tarjeta'],['use','Uso'],['status','Estado']]),
 journals:S('Asiento',[['date','Fecha','date',1],['number','Número','text',1],['account','Cuenta','text',1],['memo','Descripción','text',1],['debit','Débito','number'],['credit','Crédito','number'],['status','Estado','select',1,['draft','posted']]],[['date','Fecha','date'],['number','Número'],['account','Cuenta'],['memo','Descripción'],['debit','Débito','money'],['credit','Crédito','money'],['status','Estado']]),
 products:S('Producto',[['sku','SKU','text',1],['name','Nombre','text',1],['qty','Cantidad','number',1],['reorder','Reorden','number'],['cost','Costo','number'],['price','Precio','number'],['status','Estado','select',1,['active','inactive']]],[['sku','SKU'],['name','Producto'],['qty','Cantidad','number'],['reorder','Reorden','number'],['cost','Costo','money'],['price','Precio','money'],['status','Estado']]),
 employees:S('Empleado',[['name','Nombre','text',1],['department','Departamento','text',1],['role','Rol','text',1],['email','Correo','email'],['rate','Tarifa','number'],['status','Estado','select',1,['active','leave','inactive']]],[['name','Empleado'],['department','Departamento'],['role','Rol'],['email','Correo'],['rate','Tarifa','money'],['status','Estado']]),
 wallet:S('Credencial',[['title','Nombre','text',1],['category','Tipo','select',1,['identity','driver_license','immigration','professional','employment','financial','membership','insurance','other']],['issuer','Emisor','text',1],['region','País / estado'],['maskedId','Identificador enmascarado'],['issued','Emisión','date'],['expires','Vencimiento','date'],['status','Estado','select',1,['active','expiring','expired','replaced','archived']],['notes','Notas','textarea'],['frontImage','Imagen frontal','file'],['backImage','Imagen posterior','file']],[['title','Credencial'],['category','Tipo'],['issuer','Emisor'],['maskedId','Identificador'],['expires','Vencimiento','date'],['status','Estado']]),
 documents:S('Documento',[['title','Título','text',1],['category','Categoría','select',1,['contract','tax','legal','policy','receipt','other']],['issuer','Emisor'],['owner','Titular'],['expires','Vencimiento','date'],['reference','Referencia enmascarada'],['status','Estado','select',1,['draft','active','signed','expired','archived']],['notes','Notas','textarea'],['frontImage','Vista previa','file']],[['title','Documento'],['category','Categoría'],['issuer','Emisor'],['owner','Titular'],['expires','Vencimiento','date'],['status','Estado']]),
 ride:S('Actividad',[['platform','Plataforma','select',1,['Uber','Uber Eats','DoorDash','Instacart','Lyft','Shipt','Spark','Amazon Flex','Grubhub','Other']],['type','Tipo','select',1,['ride','delivery','shopping','payout','bonus','adjustment']],['date','Fecha','date',1],['reference','Referencia'],['gross','Ingreso bruto','number'],['tips','Propinas','number'],['miles','Millas','number'],['expense','Gasto','number'],['payoutAccount','Cuenta de depósito'],['cardLast4','Tarjeta · últimos 4'],['status','Conciliación','select',1,['pending','matched','paid','exception']],['notes','Notas','textarea']],[['platform','Plataforma'],['type','Tipo'],['date','Fecha','date'],['reference','Referencia'],['gross','Bruto','money'],['tips','Propinas','money'],['miles','Millas','number'],['cardLast4','Tarjeta'],['status','Estado']]),
 marketplace:S('Orden',[['orderNumber','Orden','text',1],['platform','Plataforma','select',1,['Instacart','DoorDash','Uber Eats','Shipt','Spark','Grubhub','Other']],['merchant','Comercio','text',1],['date','Fecha','date',1],['orderTotal','Total de compra','number'],['workerPay','Pago al trabajador','number'],['cardLast4','Tarjeta operativa · últimos 4'],['receiptStatus','Recibo','select',1,['missing','uploaded','matched']],['status','Estado','select',1,['accepted','shopping','delivering','completed','cancelled','exception']],['notes','Notas','textarea']],[['orderNumber','Orden'],['platform','Plataforma'],['merchant','Comercio'],['date','Fecha','date'],['orderTotal','Compra','money'],['workerPay','Pago','money'],['cardLast4','Tarjeta'],['receiptStatus','Recibo'],['status','Estado']]),
 rewards:S('Movimiento',[['date','Fecha','date',1],['member','Miembro','text',1],['source','Origen','select',1,['ride','marketplace','purchase','referral','promotion','manual','redemption']],['description','Descripción','text',1],['points','Puntos (+/-)','number',1],['tier','Nivel','select',1,['Member','Silver','Gold','Platinum']],['status','Estado','select',1,['pending','posted','reversed']]],[['date','Fecha','date'],['member','Miembro'],['source','Origen'],['description','Descripción'],['points','Puntos','number'],['tier','Nivel'],['status','Estado']]),
 shipments:S('Envío',[['reference','Referencia','text',1],['carrier','Transportista','text',1],['origin','Origen','text',1],['destination','Destino','text',1],['pickup','Recogida','date'],['delivery','Entrega','date'],['cost','Costo','number'],['status','Estado','select',1,['quoted','booked','in_transit','delivered','exception']]],[['reference','Referencia'],['carrier','Transportista'],['origin','Origen'],['destination','Destino'],['pickup','Recogida','date'],['cost','Costo','money'],['status','Estado']]),
 vehicles:S('Vehículo',[['name','Vehículo','text',1],['year','Año','number'],['make','Marca'],['model','Modelo'],['plate','Placa enmascarada'],['mileage','Millaje','number'],['insuranceExpires','Vence seguro','date'],['nextService','Próximo servicio','date'],['status','Estado','select',1,['active','service_due','inactive']]],[['name','Vehículo'],['year','Año','number'],['make','Marca'],['model','Modelo'],['plate','Placa'],['mileage','Millaje','number'],['nextService','Servicio','date'],['status','Estado']]),
 health:S('Registro',[['date','Fecha','date',1],['person','Persona','text',1],['type','Tipo','select',1,['appointment','wellness','medication','document','follow_up']],['provider','Proveedor'],['summary','Resumen','textarea',1],['status','Estado','select',1,['scheduled','completed','monitoring','archived']]],[['date','Fecha','date'],['person','Persona'],['type','Tipo'],['provider','Proveedor'],['summary','Resumen'],['status','Estado']]),
 safety:S('Incidente',[['reference','Referencia','text',1],['date','Fecha','date',1],['type','Tipo','text',1],['location','Ubicación','text',1],['priority','Prioridad','select',1,['low','medium','high','critical']],['owner','Responsable'],['status','Estado','select',1,['open','investigating','resolved','closed']],['summary','Resumen','textarea',1]],[['reference','Referencia'],['date','Fecha','date'],['type','Tipo'],['location','Ubicación'],['priority','Prioridad'],['owner','Responsable'],['status','Estado']]),
 community:S('Caso / programa',[['name','Nombre','text',1],['type','Tipo','select',1,['program','case','donation','volunteer','grant']],['beneficiary','Beneficiario'],['date','Fecha','date'],['amount','Valor','number'],['owner','Responsable'],['status','Estado','select',1,['planned','active','completed','closed']],['impact','Impacto','textarea']],[['name','Nombre'],['type','Tipo'],['beneficiary','Beneficiario'],['date','Fecha','date'],['amount','Valor','money'],['owner','Responsable'],['status','Estado']])
};
const empty=()=>Object.fromEntries([...Object.keys(schemas).map(k=>[k,[]]),['audit',[]],['modules',Object.fromEntries(Object.keys(modules).filter(k=>!['dashboard','reports','modules','audit','settings'].includes(k)).map(k=>[k,true]))]]);
function initial(){const d=empty();d.customers.push({id:uid(),name:'Orlando Pilot Client',company:'Pilot Company',email:'pilot@example.com',phone:'',status:'active',notes:''});d.invoices.push({id:uid(),number:'INV-1001',customer:'Orlando Pilot Client',date:today(),due:today(),total:1250,balance:1250,status:'open'});d.wallet.push({id:uid(),title:'Credencial de demostración',category:'identity',issuer:'ATLAS Demo Authority',region:'US',maskedId:'•••• 0000',issued:today(),expires:'',status:'active',notes:'Ejemplo seguro.',frontImage:'',backImage:''});d.audit.push({a:'system.ready',x:'ATLAS module suite initialized',t:new Date().toISOString()});return{auth:false,page:'dashboard',company:'atlas',theme:'dark',lang:'ES',companies:[{id:'atlas',name:'ATLAS Demo LLC',industry:'Technology & Professional Services'},{id:'uh4h',name:'United Hands for Humanity',industry:'Community Impact'}],data:{atlas:d,uh4h:empty()}}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.data)return migrate(x)}catch{}return initial()}
function migrate(s){for(const c of s.companies||[]){s.data[c.id]=s.data[c.id]||empty();const d=s.data[c.id];for(const k of Object.keys(schemas))d[k]=Array.isArray(d[k])?d[k]:[];d.audit=Array.isArray(d.audit)?d.audit:[];d.modules={...empty().modules,...(d.modules||{})};for(const k in d.modules)d.modules[k]=true}return{...initial(),...s}}
let state=load();const data=()=>state.data[state.company],company=()=>state.companies.find(x=>x.id===state.company),save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function log(a,x){data().audit.unshift({a,x,t:new Date().toISOString()});data().audit=data().audit.slice(0,500);save()}
function toast(a,b=''){const n=document.createElement('div');n.className='toast';n.innerHTML=`<strong>${esc(a)}</strong>${b?`<span>${esc(b)}</span>`:''}`;$('#toast-root').append(n);setTimeout(()=>n.remove(),3000)}
const statusClass=v=>['active','paid','posted','completed','delivered','signed','matched','reconciled','resolved','closed'].includes(String(v).toLowerCase())?'active':['overdue','expired','exception','critical','cancelled','inactive'].includes(String(v).toLowerCase())?'overdue':['open','pending','draft','planned','quoted','booked','scheduled','accepted','shopping','delivering','investigating','monitoring'].includes(String(v).toLowerCase())?'pending':'draft';
function shell(){document.documentElement.classList.toggle('light',state.theme==='light');$('#company-select').innerHTML=state.companies.map(c=>`<option value="${c.id}" ${c.id===state.company?'selected':''}>${esc(c.name)}</option>`).join('');$('#main-nav').innerHTML=groups.map(g=>`<div class="nav-group">${g[0]}</div>${g.slice(1).map(k=>`<button class="nav-item ${state.page===k?'active':''}" data-page="${k}"><span class="nav-icon">${modules[k][1]}</span>${modules[k][0]}</button>`).join('')}`).join('');$('#page-title').textContent=modules[state.page]?.[0]||'ATLAS';$('#page-eyebrow').textContent=state.page==='dashboard'?'ATLAS CORE':'ATLAS ECOSYSTEM';$('#language-btn').textContent=state.lang;$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#company-select').onchange=e=>{state.company=e.target.value;state.page='dashboard';save();shell();render()}}
function go(p){state.page=p;save();shell();render();$('#sidebar').classList.remove('open')}
const kpi=(a,b,c='')=>`<article class="card kpi"><span class="kpi-label">${esc(a)}</span><div class="kpi-value">${esc(b)}</div><span class="kpi-trend">${esc(c)}</span></article>`;
function dashboard(){const d=data(),rev=d.invoices.reduce((a,x)=>a+(+x.total||0),0)+d.ride.reduce((a,x)=>a+(+x.gross||0)+(+x.tips||0),0),exp=d.expenses.reduce((a,x)=>a+(+x.amount||0),0)+d.ride.reduce((a,x)=>a+(+x.expense||0),0),ar=d.invoices.reduce((a,x)=>a+(+x.balance||0),0),expiring=d.wallet.filter(x=>{const z=x.expires?(new Date(x.expires)-new Date())/864e5:null;return z!==null&&z>=0&&z<=90}).length;return`<section class="hero"><div class="hero-content"><div><p class="eyebrow">ATLAS COMMAND CENTER</p><h1>${esc(company().name)}</h1><p>Finanzas, identidad digital, operaciones gig, marketplace, recompensas, logística, personas e impacto en una sola interfaz.</p><div class="hero-status"><span class="pill">● ${Object.values(d.modules).filter(Boolean).length} módulos activos</span><span class="pill">● Multiempresa</span><span class="pill">● Backup JSON</span><span class="pill">● CSV</span></div></div><div class="hero-actions"><button class="button primary" data-add="wallet">＋ Credencial</button><button class="button ghost" data-add="expenses">＋ Gasto</button></div></div></section><div class="grid kpi-grid">${kpi('Ingresos',money(rev),'Facturas + Ride')}${kpi('Por cobrar',money(ar),'Saldos abiertos')}${kpi('Gastos',money(exp),'Operación registrada')}${kpi('Wallet por vencer',String(expiring),'Próximos 90 días')}</div><div class="grid two-grid"><article class="card"><div class="card-head"><div><h3>Módulos restaurados</h3><p>Acceso directo a las capacidades principales.</p></div></div><div class="card-pad grid module-grid mini-modules">${['wallet','ride','marketplace','rewards','documents','accounting'].map(k=>`<button class="mini-module" data-page="${k}"><span>${modules[k][1]}</span><div><strong>${modules[k][0]}</strong><small>Functional MVP</small></div></button>`).join('')}</div></article><article class="card"><div class="card-head"><div><h3>Actividad reciente</h3></div></div><div class="activity">${activity(8)}</div></article></div>`}
function activity(n=500){return data().audit.slice(0,n).map(x=>`<div class="activity-row"><span class="activity-dot"></span><div><strong>${esc(x.a)}</strong><p>${esc(x.x)}</p></div><time>${new Date(x.t).toLocaleString()}</time></div>`).join('')||'<div class="empty-state">No hay actividad</div>'}
function val(row,[k,,f]){const v=row[k];if(f==='money')return money(v);if(f==='number')return num(v);if(f==='date')return v?new Date(`${v}T12:00`).toLocaleDateString():'—';if(['status','receiptStatus','priority'].includes(k))return`<span class="status ${statusClass(v)}">${esc(v||'—')}</span>`;const s=String(v??'—');return esc(s.length>70?s.slice(0,67)+'…':s)}
function stats(key,r){if(key==='wallet'){const ex=r.filter(x=>x.status==='expired').length;return`${kpi('Credenciales',r.length,'Total')}${kpi('Activas',r.filter(x=>x.status==='active').length,'Disponibles')}${kpi('Por vencer',r.filter(x=>x.status==='expiring').length,'Revisar')}${kpi('Vencidas',ex,'Acción requerida')}`}if(key==='ride'){const g=r.reduce((a,x)=>a+(+x.gross||0)+(+x.tips||0),0),e=r.reduce((a,x)=>a+(+x.expense||0),0);return`${kpi('Ingreso bruto',money(g),'Incluye propinas')}${kpi('Millas',num(r.reduce((a,x)=>a+(+x.miles||0),0)),'Registradas')}${kpi('Costos',money(e),'Asociados')}${kpi('Neto',money(g-e),'Antes de impuestos')}`}if(key==='marketplace'){return`${kpi('Órdenes',r.length,'Total')}${kpi('Compras',money(r.reduce((a,x)=>a+(+x.orderTotal||0),0)),'Volumen')}${kpi('Pago trabajador',money(r.reduce((a,x)=>a+(+x.workerPay||0),0)),'Ingresos')}${kpi('Recibos matched',r.filter(x=>x.receiptStatus==='matched').length,'Conciliados')}`}if(key==='rewards'){const p=r.filter(x=>x.status!=='reversed').reduce((a,x)=>a+(+x.points||0),0);return`${kpi('Balance',num(p),'Puntos')}${kpi('Ganados',num(r.filter(x=>+x.points>0).reduce((a,x)=>a+(+x.points||0),0)),'Acumulados')}${kpi('Canjeados',num(Math.abs(r.filter(x=>+x.points<0).reduce((a,x)=>a+(+x.points||0),0))),'Redenciones')}${kpi('Movimientos',r.length,'Historial')}`}return''}
function list(key){const s=schemas[key],r=data()[key];return`${stats(key,r)?`<div class="grid kpi-grid module-kpis">${stats(key,r)}</div>`:''}<div class="toolbar"><input data-filter placeholder="Buscar registros..."><div class="toolbar-actions"><button class="button ghost" data-csv="${key}">Exportar CSV</button><button class="button primary" data-add="${key}">＋ Agregar ${s.label}</button></div></div><div class="card table-wrap"><table class="data-table"><thead><tr>${s.cols.map(c=>`<th>${c[1]}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${r.map(x=>`<tr data-find="${esc(JSON.stringify(x))}">${s.cols.map(c=>`<td>${val(x,c)}</td>`).join('')}<td class="row-actions"><button class="button small ghost" data-edit="${key}" data-id="${x.id}">Editar</button><button class="button small danger" data-del="${key}" data-id="${x.id}">Eliminar</button></td></tr>`).join('')||`<tr><td colspan="${s.cols.length+1}"><div class="empty-state">No hay registros</div></td></tr>`}</tbody></table></div>`}
function intro(p){return`<section class="module-intro"><div><p class="eyebrow">ATLAS ECOSYSTEM</p><h1>${modules[p][0]}</h1><p>${modules[p][3]}</p></div><span class="status active">Functional MVP</span></section>`}
function wallet(){const r=data().wallet;return`${intro('wallet')}<div class="grid kpi-grid module-kpis">${stats('wallet',r)}</div><div class="toolbar"><input data-filter placeholder="Buscar credenciales..."><div class="toolbar-actions"><button class="button ghost" data-csv="wallet">Exportar CSV</button><button class="button primary" data-add="wallet">＋ Añadir credencial</button></div></div><div class="credential-grid">${r.map(x=>`<article class="credential-card" data-find="${esc(JSON.stringify(x))}"><div class="credential-media">${x.frontImage?`<img src="${esc(x.frontImage)}" alt="${esc(x.title)}">`:`<div class="credential-placeholder">◩</div>`}<span class="status ${statusClass(x.status)}">${esc(x.status)}</span></div><div class="credential-body"><span class="kpi-label">${esc(x.category)}</span><h3>${esc(x.title)}</h3><p>${esc(x.issuer)}</p><div class="credential-meta"><span>${esc(x.maskedId||'Sin identificador')}</span><span>${x.expires?'Vence '+new Date(`${x.expires}T12:00`).toLocaleDateString():'Sin vencimiento'}</span></div><div class="credential-actions"><button class="button small ghost" data-edit="wallet" data-id="${x.id}">Editar</button>${x.frontImage?`<button class="button small ghost" data-image="${x.id}">Ver</button>`:''}<button class="button small danger" data-del="wallet" data-id="${x.id}">Eliminar</button></div></div></article>`).join('')||'<div class="card empty-state">No hay credenciales</div>'}</div>`}
function reports(){const d=data(),rev=d.invoices.reduce((a,x)=>a+(+x.total||0),0)+d.ride.reduce((a,x)=>a+(+x.gross||0)+(+x.tips||0),0),exp=d.expenses.reduce((a,x)=>a+(+x.amount||0),0)+d.ride.reduce((a,x)=>a+(+x.expense||0),0);return`<div class="page-actions"><button class="button ghost" data-backup>Exportar respaldo JSON</button><button class="button primary" onclick="print()">Imprimir / PDF</button></div><section class="report-sheet"><p class="eyebrow">EXECUTIVE INTELLIGENCE</p><h2>${esc(company().name)}</h2><div class="report-metrics">${[['Ingresos',money(rev)],['Gastos',money(exp)],['Resultado',money(rev-exp)],['Wallet',d.wallet.length],['Marketplace',d.marketplace.length],['Rewards',num(d.rewards.reduce((a,x)=>a+(+x.points||0),0))]].map(x=>`<div class="report-metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div></section>`}
function moduleCenter(){return`${intro('modules')}<div class="grid module-grid">${Object.entries(modules).filter(([k])=>!['dashboard','reports','modules','audit','settings'].includes(k)).map(([k,m])=>`<article class="card module-card"><div class="module-top"><span class="module-icon">${m[1]}</span><span class="status ${data().modules[k]?'active':'draft'}">${data().modules[k]?'Activo':'Desactivado'}</span></div><h3>${m[0]}</h3><p>${m[3]}</p><div class="module-actions"><button class="button small ghost" data-page="${k}">Abrir</button><button class="button small ${data().modules[k]?'danger':'primary'}" data-module="${k}">${data().modules[k]?'Desactivar':'Activar'}</button></div></article>`).join('')}</div>`}
function settings(){const c=company();return`<div class="grid settings-grid"><article class="card card-pad"><p class="eyebrow">WORKSPACE</p><h3>Organización activa</h3><label>Nombre<input id="company-name" value="${esc(c.name)}"></label><label>Industria<input id="company-industry" value="${esc(c.industry)}"></label><div class="page-actions settings-actions"><button id="save-company" class="button primary">Guardar</button><button id="add-company" class="button ghost">Añadir empresa</button></div></article><article class="card card-pad"><p class="eyebrow">DATA CONTROL</p><h3>Respaldo y privacidad</h3><p class="muted">El MVP guarda datos localmente. Producción requiere cifrado, RLS y almacenamiento privado.</p><div class="stack-actions"><button class="button ghost" data-backup>Exportar respaldo JSON</button><label class="button ghost file-button">Importar respaldo<input id="restore-backup" type="file" accept="application/json"></label><button id="reset-demo" class="button danger">Restablecer demo</button></div></article></div>`}
function render(){const p=state.page;let h;if(p==='dashboard')h=dashboard();else if(p==='reports')h=reports();else if(p==='modules')h=moduleCenter();else if(p==='audit')h=`<article class="card"><div class="card-head"><div><h3>Audit Trail</h3></div><button class="button ghost" data-clear>Limpiar</button></div><div class="activity">${activity()}</div></article>`;else if(p==='settings')h=settings();else if(p==='wallet')h=wallet();else if(modules[p]?.[2])h=`${intro(p)}${list(modules[p][2])}`;else h=dashboard();$('#content').innerHTML=h;bind()}
function fieldHtml(f,v=''){const[k,l,t='text',req,opt]=f,r=req?'required':'';if(t==='select')return`<label>${l}<select name="${k}" ${r}>${opt.map(o=>`<option value="${o}" ${String(v)===o?'selected':''}>${o}</option>`).join('')}</select></label>`;if(t==='textarea')return`<label class="full-span">${l}<textarea name="${k}" rows="4" ${r}>${esc(v)}</textarea></label>`;if(t==='file')return`<label class="full-span">${l}<input name="${k}" type="file" accept="image/*"><small class="field-help">Máximo ${Math.round(MAX_IMG/1024)} KB. Solo local.</small>${v?`<img class="form-preview" src="${esc(v)}">`:''}</label>`;return`<label>${l}<input name="${k}" type="${t}" value="${esc(v)}" ${t==='number'?'step="0.01"':''} ${r}></label>`}
function modal(key,id){const s=schemas[key],row=id?data()[key].find(x=>x.id===id):null,m=document.createElement('div');m.className='modal-backdrop';m.innerHTML=`<form class="modal-card"><div class="modal-head"><div><p class="eyebrow">${s.label}</p><h3>${row?'Editar':'Agregar'} ${s.label}</h3></div><button type="button" class="icon-button" data-close>✕</button></div><div class="modal-body">${s.fields.map(f=>fieldHtml(f,row?.[f[0]]??((f[2]==='date'&&['date','issued'].includes(f[0]))?today():(f[2]==='select'?f[4][0]:'')))).join('')}</div><div class="modal-foot"><button type="button" class="button ghost" data-close>Cancelar</button><button class="button primary">Guardar</button></div></form>`;$('#modal-root').append(m);$$('[data-close]',m).forEach(b=>b.onclick=()=>m.remove());m.onclick=e=>{if(e.target===m)m.remove()};$('form',m).onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),obj={...(row||{}),id:row?.id||uid()};try{for(const f of s.fields){const[k,,t]=f;if(t==='file'){const file=fd.get(k);if(file?.size)obj[k]=await image(file);else if(!row)obj[k]=''}else obj[k]=t==='number'?+(fd.get(k)||0):String(fd.get(k)||'').trim()}const a=data()[key];if(row)a[a.findIndex(x=>x.id===row.id)]=obj;else a.unshift(obj);log(row?'record.updated':'record.created',`${s.label}: ${obj.title||obj.name||obj.number||obj.reference||obj.orderNumber||obj.vendor||obj.platform}`);m.remove();render();toast('Registro guardado')}catch(err){toast('No se pudo guardar',err.message)}}}
function image(f){return new Promise((ok,no)=>{if(!f.type.startsWith('image/'))return no(new Error('Solo imágenes'));if(f.size>MAX_IMG)return no(new Error('Imagen demasiado grande'));const r=new FileReader;r.onerror=()=>no(new Error('No se pudo leer'));r.onload=()=>ok(r.result);r.readAsDataURL(f)})}
function del(k,id){if(!confirm('¿Eliminar este registro?'))return;data()[k]=data()[k].filter(x=>x.id!==id);log('record.deleted',schemas[k].label);render()}
function csv(k){const s=schemas[k],fs=s.fields.filter(x=>x[2]!=='file'),q=v=>`"${String(v??'').replace(/"/g,'""')}"`,out=[fs.map(x=>q(x[1])).join(','),...data()[k].map(r=>fs.map(x=>q(r[x[0]])).join(','))].join('\n');download(new Blob(['\ufeff'+out],{type:'text/csv'}),`${k}-${today()}.csv`);log('export.csv',k)}
function backup(){download(new Blob([JSON.stringify({version:4,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),`atlas-backup-${today()}.json`);log('backup.exported','JSON')}
function download(b,n){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function viewImage(id){const x=data().wallet.find(r=>r.id===id);if(!x?.frontImage)return;const m=document.createElement('div');m.className='modal-backdrop image-viewer';m.innerHTML=`<div class="modal-card"><div class="modal-head"><h3>${esc(x.title)}</h3><button class="icon-button">✕</button></div><div class="image-viewer-body"><img src="${esc(x.frontImage)}"></div></div>`;$('#modal-root').append(m);$('button',m).onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()}}
function bind(){$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-add]').forEach(b=>b.onclick=()=>modal(b.dataset.add));$$('[data-edit]').forEach(b=>b.onclick=()=>modal(b.dataset.edit,b.dataset.id));$$('[data-del]').forEach(b=>b.onclick=()=>del(b.dataset.del,b.dataset.id));$$('[data-csv]').forEach(b=>b.onclick=()=>csv(b.dataset.csv));$$('[data-backup]').forEach(b=>b.onclick=backup);$$('[data-image]').forEach(b=>b.onclick=()=>viewImage(b.dataset.image));$$('[data-filter]').forEach(i=>i.oninput=e=>{const q=e.target.value.toLowerCase();$$('[data-find]').forEach(x=>x.style.display=x.dataset.find.toLowerCase().includes(q)?'':'none')});$$('[data-module]').forEach(b=>b.onclick=()=>{const k=b.dataset.module;data().modules[k]=!data().modules[k];log('module.toggled',k);render()});const c=$('[data-clear]');if(c)c.onclick=()=>{data().audit=[];save();render()};const sc=$('#save-company');if(sc)sc.onclick=()=>{company().name=$('#company-name').value||company().name;company().industry=$('#company-industry').value;log('company.updated',company().name);shell();render()};const ac=$('#add-company');if(ac)ac.onclick=()=>{const n=prompt('Nombre de la empresa');if(!n)return;const id=uid();state.companies.push({id,name:n,industry:''});state.data[id]=empty();state.company=id;save();shell();render()};const rs=$('#reset-demo');if(rs)rs.onclick=()=>{if(confirm('¿Restablecer todos los datos locales?')){state=initial();save();shell();render()}};const rb=$('#restore-backup');if(rb)rb.onchange=async e=>{try{const z=JSON.parse(await e.target.files[0].text());state=migrate(z.state||z);save();shell();render();toast('Respaldo restaurado')}catch{toast('Archivo inválido')}}}
function search(q){const a=[];for(const g of groups)for(const p of g.slice(1))a.push({t:modules[p][0],p,k:'Módulo'});for(const[k,s]of Object.entries(schemas)){const p=Object.keys(modules).find(x=>modules[x][2]===k)||'dashboard';for(const r of data()[k])a.push({t:r.title||r.name||r.number||r.reference||r.orderNumber||r.vendor||r.platform||s.label,p,k:s.label})}const z=a.filter(x=>`${x.t} ${x.k}`.toLowerCase().includes(q.toLowerCase())).slice(0,20);$('#search-results').innerHTML=z.map(x=>`<button class="search-result" data-search-page="${x.p}"><strong>${esc(x.t)}</strong><div class="muted">${x.k}</div></button>`).join('')||'<div class="empty-state">No hay resultados</div>';$$('[data-search-page]').forEach(b=>b.onclick=()=>{go(b.dataset.searchPage);$('#search-overlay').classList.add('hidden')})}
function globals(){$('#login-form').onsubmit=e=>{e.preventDefault();$('#login-form').classList.add('hidden');$('#otp-form').classList.remove('hidden')};$('#otp-form').onsubmit=e=>{e.preventDefault();if($('#otp-code').value!=='246810')return toast('Código incorrecto');state.auth=true;save();open()};$('#back-to-login').onclick=()=>{$('#otp-form').classList.add('hidden');$('#login-form').classList.remove('hidden')};$('#toggle-password').onclick=()=>{const x=$('#login-password');x.type=x.type==='password'?'text':'password'};$('#logout-btn').onclick=()=>{state.auth=false;save();$('#app-view').classList.add('hidden');$('#login-view').classList.remove('hidden')};$('#menu-btn').onclick=()=>$('#sidebar').classList.add('open');$('#sidebar-close').onclick=()=>$('#sidebar').classList.remove('open');$('#theme-btn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();shell()};$('#language-btn').onclick=()=>{state.lang=state.lang==='ES'?'EN':'ES';save();shell()};$('#global-search-btn').onclick=()=>{$('#search-overlay').classList.remove('hidden');$('#global-search-input').focus();search('')};$('#close-search').onclick=()=>$('#search-overlay').classList.add('hidden');$('#global-search-input').oninput=e=>search(e.target.value);$('#quick-add-btn').onclick=()=>modal('expenses');$('#notifications-btn').onclick=()=>toast('Alertas ATLAS','Wallet, conciliación y vencimientos');document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#global-search-btn').click()}if(e.key==='Escape'){$('#search-overlay').classList.add('hidden');$$('.modal-backdrop').forEach(x=>x.remove())}})}
function open(){$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');shell();render()}
globals();if(state.auth)open();
})();
