const json = (data, status = 200, headers = {}) =>
  new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", ...headers } });
const text = (body, status = 200, headers = {}) => new Response(body, { status, headers });
const enc = new TextEncoder();
function bytesToHex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function bytesToBase64(bytes){let binary="";const arr=new Uint8Array(bytes);for(let i=0;i<arr.byteLength;i++)binary+=String.fromCharCode(arr[i]);return btoa(binary)}
function base64ToBytes(value){const binary=atob(value);const out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)out[i]=binary.charCodeAt(i);return out}
async function sha256(value){return bytesToHex(await crypto.subtle.digest("SHA-256",typeof value==="string"?enc.encode(value):value))}
async function hashPassword(password,saltB64=null){const salt=saltB64?base64ToBytes(saltB64):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:210000,hash:"SHA-256"},key,256);return{salt:bytesToBase64(salt),hash:bytesToBase64(bits)}}
async function verifyPassword(password,salt,expected){return (await hashPassword(password,salt)).hash===expected}
function randomToken(bytes=32){return bytesToBase64(crypto.getRandomValues(new Uint8Array(bytes))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function slugify(input){return String(input||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,80)}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function pageHtml(page){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(page.title)}</title><style>body{margin:0;background:#07101d;color:#ecf5ff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:900px;margin:auto;padding:72px 24px}.shell{border:1px solid #203b5c;border-radius:24px;padding:32px;background:#0d1a2d}h1{font-size:42px;margin-top:0}p{line-height:1.7;color:#bed0e1}.mark{font-size:12px;letter-spacing:.18em;color:#5fdcff;text-transform:uppercase}</style></head><body><main><div class="shell"><div class="mark">ATLAS Pages</div><h1>${escapeHtml(page.title)}</h1><p>${escapeHtml(page.body).replace(/\n/g,"<br>")}</p></div></main></body></html>`}
async function readJson(request){try{return await request.json()}catch{return null}}
async function getSession(request,env){const auth=request.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return null;const tokenHash=await sha256(auth.slice(7));return env.DB.prepare(`SELECT s.id,s.user_id,s.expires_at,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at > datetime('now')`).bind(tokenHash).first()}
async function audit(env,actorUserId,action,entityType,entityId,metadata={}){await env.DB.prepare(`INSERT INTO audit_log(id,actor_user_id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,datetime('now'))`).bind(crypto.randomUUID(),actorUserId||null,action,entityType,entityId||null,JSON.stringify(metadata)).run()}
async function health(env){const d1=await env.DB.prepare("SELECT 1 as ok").first();const probeKey=`health/${Date.now()}.txt`;await env.BACKUPS.put(probeKey,"ok");const r2=await env.BACKUPS.get(probeKey);await env.BACKUPS.delete(probeKey);return{d1:d1?.ok===1,r2:(await r2?.text())==="ok"}}
async function bootstrap(request,env){if(!env.BOOTSTRAP_KEY)return json({error:"BOOTSTRAP_KEY_not_configured"},503);if(request.headers.get("x-atlas-bootstrap-key")!==env.BOOTSTRAP_KEY)return json({error:"unauthorized"},401);const existing=await env.DB.prepare("SELECT COUNT(*) count FROM users").first();if((existing?.count||0)>0)return json({error:"already_bootstrapped"},409);const body=await readJson(request);if(!body?.email||!body?.password||body.password.length<12)return json({error:"email_and_password_min_12_required"},400);const pw=await hashPassword(body.password);const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO users(id,email,password_salt,password_hash,role,created_at) VALUES(?,?,?,?, 'owner',datetime('now'))`).bind(id,body.email.toLowerCase(),pw.salt,pw.hash).run();await audit(env,id,"bootstrap_owner","user",id);return json({ok:true,user_id:id,email:body.email.toLowerCase()},201)}
async function login(request,env){const body=await readJson(request);if(!body?.email||!body?.password)return json({error:"credentials_required"},400);const user=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(body.email.toLowerCase()).first();if(!user||!(await verifyPassword(body.password,user.password_salt,user.password_hash)))return json({error:"invalid_credentials"},401);const token=randomToken();const sid=crypto.randomUUID();await env.DB.prepare(`INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,datetime('now','+12 hours'),datetime('now'))`).bind(sid,user.id,await sha256(token)).run();await audit(env,user.id,"login","session",sid);return json({token,expires_in_seconds:43200,user:{id:user.id,email:user.email,role:user.role}})}
async function createPage(request,env,session){const body=await readJson(request);if(!body?.title)return json({error:"title_required"},400);const slug=slugify(body.slug||body.title);if(!slug)return json({error:"invalid_slug"},400);const id=crypto.randomUUID();try{await env.DB.prepare(`INSERT INTO pages(id,slug,title,body,published,created_by,created_at,updated_at) VALUES(?,?,?,?,0,?,datetime('now'),datetime('now'))`).bind(id,slug,body.title,String(body.body||""),session.user_id).run()}catch(e){if(String(e).includes("UNIQUE"))return json({error:"slug_already_exists"},409);throw e}await audit(env,session.user_id,"create_page","page",id,{slug});return json({ok:true,page:{id,slug,title:body.title,published:false}},201)}
async function publishPage(env,session,id,origin){const page=await env.DB.prepare("SELECT * FROM pages WHERE id=?").bind(id).first();if(!page)return json({error:"not_found"},404);await env.DB.prepare("UPDATE pages SET published=1,published_at=datetime('now'),updated_at=datetime('now') WHERE id=?").bind(id).run();await audit(env,session.user_id,"publish_page","page",id,{slug:page.slug});return json({ok:true,url:`${origin}/p/${page.slug}`})}
async function publicPage(env,slug){const page=await env.DB.prepare("SELECT * FROM pages WHERE slug=? AND published=1").bind(slug).first();if(!page)return text("Not found",404,{"content-type":"text/plain; charset=utf-8"});return text(pageHtml(page),200,{"content-type":"text/html; charset=utf-8","cache-control":"public,max-age=60"})}
async function createBackup(env,session){const tables=["users","pages","audit_log"];const snapshot={version:1,created_at:new Date().toISOString(),tables:{}};for(const table of tables){const{results}=await env.DB.prepare(`SELECT * FROM ${table}`).all();snapshot.tables[table]=results}const payload=JSON.stringify(snapshot);const digest=await sha256(payload);const id=crypto.randomUUID();const key=`backups/${new Date().toISOString().replace(/[:.]/g,"-")}-${id}.json`;await env.BACKUPS.put(key,payload,{httpMetadata:{contentType:"application/json"},customMetadata:{sha256:digest,createdBy:session.user_id}});await env.DB.prepare(`INSERT INTO backups(id,r2_key,sha256,size_bytes,created_by,created_at) VALUES(?,?,?,?,?,datetime('now'))`).bind(id,key,digest,enc.encode(payload).byteLength,session.user_id).run();await audit(env,session.user_id,"create_backup","backup",id,{key,sha256:digest});return json({ok:true,backup:{id,key,sha256:digest,size_bytes:enc.encode(payload).byteLength}},201)}
export default{async fetch(request,env){try{const url=new URL(request.url),path=url.pathname;if(path==="/api/health"&&request.method==="GET"){const h=await health(env);return json({product:"ATLAS Operational Core",version:"0.1.0",modules:{authentication:{level:"service_real",healthy:h.d1},pages_database:{level:"service_real",healthy:h.d1},page_publication:{level:"service_real",healthy:h.d1},backups_r2:{level:"service_real",healthy:h.r2}},production_gate:h.d1&&h.r2?"infrastructure_connected":"blocked"})}if(path==="/api/bootstrap"&&request.method==="POST")return bootstrap(request,env);if(path==="/api/login"&&request.method==="POST")return login(request,env);if(path.startsWith("/p/")&&request.method==="GET")return publicPage(env,decodeURIComponent(path.slice(3)));if(path.startsWith("/api/")){const session=await getSession(request,env);if(!session)return json({error:"authentication_required"},401);if(path==="/api/pages"&&request.method==="POST")return createPage(request,env,session);const publishMatch=path.match(/^\/api\/pages\/([^/]+)\/publish$/);if(publishMatch&&request.method==="POST")return publishPage(env,session,publishMatch[1],url.origin);if(path==="/api/backups"&&request.method==="POST")return createBackup(env,session);return json({error:"api_not_found"},404)}return env.ASSETS.fetch(request)}catch(error){console.error(error);return json({error:"internal_error",request_id:crypto.randomUUID()},500)}}};