import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const src = path.join(root,'public');
const out = path.join(root,'dist');
fs.rmSync(out,{recursive:true,force:true});
fs.mkdirSync(out,{recursive:true});
fs.cpSync(src,out,{recursive:true});
fs.copyFileSync(path.join(root,'atlas.config.json'),path.join(out,'atlas.config.json'));
console.log('ATLAS build complete: dist/ ready for Cloudflare Pages.');
