import { mkdir, readFile, writeFile, stat, copyFile } from 'node:fs/promises';
import { createHash, randomUUID } from 'node:crypto';
import { basename, extname, resolve } from 'node:path';

const ROOT=resolve(process.cwd());
const BASE=resolve(ROOT,'.atlas','models','foundry');
const ARTIFACT_DIR=resolve(BASE,'artifacts');
const REGISTRY=resolve(BASE,'artifacts.json');
const RECIPES=resolve(BASE,'recipes.json');
const DATASETS=resolve(BASE,'datasets.json');
const JOBS=resolve(BASE,'jobs.json');
await Promise.all([mkdir(BASE,{recursive:true}),mkdir(ARTIFACT_DIR,{recursive:true})]);
const TASKS=['speech-to-text','voice-synthesis','voice-clone','phoneme-recognition','facial-lipsync','super-resolution','video-restyle'];
const JOB_STATES=['queued','running','succeeded','failed','cancelled'];
const ARTIFACT_STATES=['candidate','validated','rejected','retired'];
function output(value,code=0){console.log(JSON.stringify(value,null,2));process.exitCode=code}
function args(values){const positional=[],flags={};for(let i=0;i<values.length;i++){const v=values[i];if(!v.startsWith('--')){positional.push(v);continue}const k=v.slice(2);if(values[i+1]&&!values[i+1].startsWith('--'))flags[k]=values[++i];else flags[k]=true}return{positional,flags}}
function safeId(value,label='id'){const v=String(value||'');if(!/^[A-Za-z0-9_.-]{1,96}$/.test(v))throw new Error(`${label} must match ^[A-Za-z0-9_.-]{1,96}$`);return v}
function bool(value){return value===true||String(value).toLowerCase()==='true'||String(value)==='1'}
function jsonArg(value,label){try{return JSON.parse(String(value))}catch{throw new Error(`${label} must be valid JSON`)}}
async function readJson(path,fallback=[]){try{return JSON.parse(await readFile(path,'utf8'))}catch{return fallback}}
async function saveJson(path,value){await writeFile(path,JSON.stringify(value,null,2)+'\n','utf8')}
async function sha256File(path){return createHash('sha256').update(await readFile(path)).digest('hex')}
async function sha256Text(text){return createHash('sha256').update(text).digest('hex')}
function requireTask(value){if(!TASKS.includes(value))throw new Error(`task must be one of: ${TASKS.join(', ')}`);return value}
function now(){return new Date().toISOString()}
function findById(rows,id,label){const row=rows.find(x=>x.id===id);if(!row)throw new Error(`${label} not found: ${id}`);return row}
function workspacePath(path){const p=resolve(path);if(!(p===ROOT||p.startsWith(ROOT+'/')||p.startsWith(ROOT+'\\')))throw new Error('path must be inside the current ATLAS workspace');return p}
async function registerArtifact(flags){const source=workspacePath(String(flags.path||''));if(!flags.path)throw new Error('--path is required');const info=await stat(source);if(!info.isFile())throw new Error('artifact path must be a file');const task=requireTask(String(flags.task||'')),sha256=await sha256File(source),id=safeId(flags.id||`${task}-${sha256.slice(0,12)}`,'artifact id'),license=String(flags.license||'unspecified').slice(0,160),consentRequired=['voice-synthesis','voice-clone','facial-lipsync','video-restyle'].includes(task),consentAttested=bool(flags['consent-attested']);if(consentRequired&&!consentAttested)throw new Error(`${task} artifact registration requires --consent-attested true`);const rows=await readJson(REGISTRY,[]);if(rows.some(x=>x.id===id))throw new Error(`artifact already exists: ${id}`);const copy=bool(flags.copy),ext=extname(source).slice(0,16),stored=copy?resolve(ARTIFACT_DIR,sha256+ext):source,record={id,task,state:'candidate',sha256,sizeBytes:info.size,sourceFile:basename(source),storage:copy?'foundry-copy':'workspace-reference',path:stored,license,consentRequired,consentAttested,metrics:flags.metrics?jsonArg(flags.metrics,'--metrics'):null,createdAt:now(),updatedAt:now()};if(flags.apply){if(copy)await copyFile(source,stored);await saveJson(REGISTRY,[...rows,record])}return{apply:Boolean(flags.apply),artifact:record}}
async function verifyArtifact(id){const rows=await readJson(REGISTRY,[]),row=findById(rows,id,'artifact'),info=await stat(row.path),sha=await sha256File(row.path);return{id,exists:info.isFile(),sizeBytes:info.size,expectedSha256:row.sha256,actualSha256:sha,integrity:sha===row.sha256&&info.size===row.sizeBytes}}
async function promoteArtifact(id,flags){const rows=await readJson(REGISTRY,[]),index=rows.findIndex(x=>x.id===id);if(index<0)throw new Error(`artifact not found: ${id}`);const target=String(flags.state||'validated');if(!ARTIFACT_STATES.includes(target))throw new Error(`state must be one of: ${ARTIFACT_STATES.join(', ')}`);if(target==='validated'){const integrity=await verifyArtifact(id);if(!integrity.integrity)throw new Error('artifact integrity verification failed');if(!rows[index].metrics||typeof rows[index].metrics!=='object')throw new Error('validated artifacts require evaluation metrics');if(rows[index].consentRequired&&!rows[index].consentAttested)throw new Error('consent attestation missing')}const next={...rows[index],state:target,updatedAt:now()},out=[...rows];out[index]=next;if(flags.apply)await saveJson(REGISTRY,out);return{apply:Boolean(flags.apply),artifact:next}}
async function registerDataset(flags){if(!flags.manifest)throw new Error('--manifest is required');const path=workspacePath(String(flags.manifest)),raw=await readFile(path,'utf8'),manifest=JSON.parse(raw);if(!manifest||typeof manifest!=='object'||Array.isArray(manifest))throw new Error('dataset manifest must be a JSON object');const id=safeId(flags.id||manifest.id||`dataset-${(await sha256Text(raw)).slice(0,12)}`,'dataset id'),task=requireTask(String(flags.task||manifest.task||'')),items=Array.isArray(manifest.items)?manifest.items:[];if(!items.length)throw new Error('dataset manifest requires non-empty items array');const consentRequired=['voice-synthesis','voice-clone','facial-lipsync','video-restyle'].includes(task),consentAttested=bool(flags['consent-attested']||manifest.consentAttested);if(consentRequired&&!consentAttested)throw new Error(`${task} dataset requires consent attestation`);const record={id,task,manifestPath:path,sha256:await sha256Text(raw),itemCount:items.length,consentRequired,consentAttested,license:String(flags.license||manifest.license||'unspecified').slice(0,160),createdAt:now(),updatedAt:now()},rows=await readJson(DATASETS,[]);if(rows.some(x=>x.id===id))throw new Error(`dataset already exists: ${id}`);if(flags.apply)await saveJson(DATASETS,[...rows,record]);return{apply:Boolean(flags.apply),dataset:record}}
async function defineRecipe(flags){const recipe=flags.json?jsonArg(flags.json,'--json'):{},id=safeId(flags.id||recipe.id||randomUUID(),'recipe id'),task=requireTask(String(flags.task||recipe.task||'')),allowed=['architecture','optimizer','learningRate','batchSize','epochs','steps','seed','precision','input','output','loss','evaluation','checkpointEvery','notes'],config={};for(const k of allowed)if(k in recipe)config[k]=recipe[k];if(!Object.keys(config).length)throw new Error('recipe JSON contains no supported training fields');const record={id,task,config,configSha256:await sha256Text(JSON.stringify(config)),createdAt:now(),updatedAt:now()},rows=await readJson(RECIPES,[]);if(rows.some(x=>x.id===id))throw new Error(`recipe already exists: ${id}`);if(flags.apply)await saveJson(RECIPES,[...rows,record]);return{apply:Boolean(flags.apply),recipe:record}}
async function createJob(flags){const recipes=await readJson(RECIPES,[]),datasets=await readJson(DATASETS,[]),recipe=findById(recipes,safeId(flags.recipe,'recipe id'),'recipe'),dataset=findById(datasets,safeId(flags.dataset,'dataset id'),'dataset');if(recipe.task!==dataset.task)throw new Error('recipe and dataset tasks do not match');const baseArtifact=flags.base?findById(await readJson(REGISTRY,[]),safeId(flags.base,'base artifact id'),'artifact'):null;if(baseArtifact&&baseArtifact.state!=='validated')throw new Error('base artifact must be validated');const id=safeId(flags.id||`job-${randomUUID()}`,'job id'),record={id,task:recipe.task,recipeId:recipe.id,datasetId:dataset.id,baseArtifactId:baseArtifact?.id||null,state:'queued',executor:'not-configured',externalProviders:[],createdAt:now(),updatedAt:now(),history:[{state:'queued',at:now(),reason:'job-created'}]},rows=await readJson(JOBS,[]);if(rows.some(x=>x.id===id))throw new Error(`job already exists: ${id}`);if(flags.apply)await saveJson(JOBS,[...rows,record]);return{apply:Boolean(flags.apply),job:record,executionStarted:false,message:'Job manifest created. ATLAS GPU executor is not configured by Neural Foundry.'}}
async function transitionJob(id,flags){const rows=await readJson(JOBS,[]),i=rows.findIndex(x=>x.id===id);if(i<0)throw new Error(`job not found: ${id}`);const state=String(flags.state||'');if(!JOB_STATES.includes(state))throw new Error(`state must be one of: ${JOB_STATES.join(', ')}`);const executor=String(flags.executor||rows[i].executor||'not-configured').slice(0,160);if(state==='running'&&executor==='not-configured')throw new Error('running state requires a configured --executor identifier');const next={...rows[i],state,executor,updatedAt:now(),history:[...(rows[i].history||[]),{state,at:now(),reason:String(flags.reason||'manual-transition').slice(0,240)}]},out=[...rows];out[i]=next;if(flags.apply)await saveJson(JOBS,out);return{apply:Boolean(flags.apply),job:next}}
const [domain,action,...raw]=process.argv.slice(2),{positional,flags}=args(raw);
try{if(domain==='status'){const[artifacts,recipes,datasets,jobs]=await Promise.all([readJson(REGISTRY,[]),readJson(RECIPES,[]),readJson(DATASETS,[]),readJson(JOBS,[])]);output({service:'ATLAS Neural Foundry',version:1,storage:'.atlas/models/foundry',externalProviders:[],gpuExecutorConfigured:false,tasks:TASKS,counts:{artifacts:artifacts.length,validatedArtifacts:artifacts.filter(x=>x.state==='validated').length,recipes:recipes.length,datasets:datasets.length,jobs:jobs.length,runningJobs:jobs.filter(x=>x.state==='running').length},capabilities:['artifact.register','artifact.verify','artifact.promote','artifact.list','dataset.register','dataset.list','recipe.define','recipe.list','job.create','job.list','job.transition'],writesDryRunByDefault:true})}else if(domain==='artifact'&&action==='register')output(await registerArtifact(flags));else if(domain==='artifact'&&action==='verify')output(await verifyArtifact(safeId(positional[0],'artifact id')));else if(domain==='artifact'&&action==='promote')output(await promoteArtifact(safeId(positional[0],'artifact id'),flags));else if(domain==='artifact'&&action==='list')output({artifacts:await readJson(REGISTRY,[])});else if(domain==='dataset'&&action==='register')output(await registerDataset(flags));else if(domain==='dataset'&&action==='list')output({datasets:await readJson(DATASETS,[])});else if(domain==='recipe'&&action==='define')output(await defineRecipe(flags));else if(domain==='recipe'&&action==='list')output({recipes:await readJson(RECIPES,[])});else if(domain==='job'&&action==='create')output(await createJob(flags));else if(domain==='job'&&action==='list')output({jobs:await readJson(JOBS,[])});else if(domain==='job'&&action==='transition')output(await transitionJob(safeId(positional[0],'job id'),flags));else{console.error('ATLAS Neural Foundry: use status, artifact, dataset, recipe, or job commands. Foundry never starts GPU training by itself.');process.exitCode=2}}catch(error){output({service:'ATLAS Neural Foundry',ok:false,error:error instanceof Error?error.message:String(error)},1)}
